### ISSUE TITLE
FFMPEG AccessViolationException AAC codec

### ISSUE THREAD

**Issue by tw-easy** [ispysoftware/iSpy#100]
Hi,
I'm having some trouble with a FFMPEG RTSP stream audio/video, video work but audio doesn't.
I tried to separate audio and video stream so when I add audio stream System.AccessViolationException is throw by ffmpeg.swr_convert(...) in MediaStream.cs and then audio is disabled on catch.
Audio stream works fine with FFPlay so FFMPEG can decode that type of stream.

Audio codec is AAC LC 48.0kHz 2 channels but the exception can be reproduced also adding a microphone in FFMPEG tab and give a file with AAC codec.

**Comment by ispysoftware** [comment]
Are you able to port forward the stream so i can take a look at it?

**Comment by tw-easy** [comment]
Unfortunately I can't but as I said the problem is in the codec so you che reproduce che same exception feeding the file (created from the stream with FFMPEG bin) [audio.zip](https://github.com/ispysoftware/iSpy/files/4407760/audio.zip) as microphone to FFMPEG

**Comment by ispysoftware** [comment]
thanks will take a look

**Comment by ispysoftware** [comment]
are you building this from source?

**Comment by tw-easy** [comment]
Yes

**Comment by ispysoftware** [comment]
just pushed an update - please try that and let me know if it fixes things

**Comment by tw-easy** [comment]
I tried and now is working!
I was wondering if it would be possible to keep the quality and multiple channels of audio stream as the Agent DVR does

**Comment by ispysoftware** [comment]
ispy saves to a fixed format that works on mobile devices whereas agent restreams content according to what the client can handle, recording raw would break remote access on ispy unfortunately.

**Comment by ispysoftware** [comment]
should link to that page in the instructions.  Also note that 
export DEPOT_TOOLS_WIN_TOOLCHAIN_BASE_URL=<path/to/sdk/zip/file>
should be
export DEPOT_TOOLS_WIN_TOOLCHAIN_BASE_URL=<path/to/sdk/zip/folder>
.. cost me 6 hours of debugging!
