### ISSUE TITLE
Increase reconnect timer on disconnected cameras

### ISSUE THREAD

**Issue by asdf51022** [ispysoftware/iSpy#101]
I have dozens of cameras, but they are disconnected the vast majority of the time.
My log files max out in less than a minute as ispy attempts to reconnect to disconnected cameras every couple seconds.
My ispy app crashes constantly (but inconsistently), so I am thinking that all these reconnect attempts may be the culprit. I've looked in the logs, but there is never anything about why ispy crashed. However, this may be due to the fact that the logs have reached their maximum size. Sometimes it goes 2minutes and crashes, and sometimes 10+ hours. 
Is there a way to have have ispy to only reattempt the connection to each camera every 5-10min when disconnected?

**Comment by ispysoftware** [comment]
Hello check the system event log for application error messages.
Are you running iSpy from source?

**Comment by asdf51022** [comment]
Hello,
The log files max out at 100KB, so i miss the messages when it crashes. I would like to stop all these reconnects so the logs dont fill up so quickly. I would increase the size of the log file, but it would be GBs in no time and fill up the computer. It takes 20 seconds to get to the 100KB limit.

**Comment by ispysoftware** [comment]
look in the system event log (type "event" in the start menu)
