### ISSUE TITLE
Lower FPS on local attached camera (ispyserver)

### ISSUE THREAD

**Issue by asdf51022** [ispysoftware/iSpy#102]
I am wondering if there is a way of reducing the fps on a local camera (usb webcam) in ispyserver. I have a lot of options for resolution, but they are all 30fps.
I only need about 4fps. I am using a host to connect to this via mjpeg url, but reducing the stream to 4fps on only reduces cpu usage. Network utilization doesn't change at all if i set it to 4fps or 20fps. This leads me to believe that it is downloading the whole 30fps stream but only displaying/processing 4fps.
So this means I need a way of reducing the fps on the local ispyserver client side.

**Comment by ispysoftware** [comment]
USB devices only provide fixed framerates. You can ignore frames by setting
the max framerate when you edit the camera but there's no way to stop the
device sending the frame in the first place unfortunately.
