### ISSUE TITLE
Desktop stream inaccessible when run as scheduled task?

### ISSUE THREAD

**Issue by asdf51022** [ispysoftware/iSpy#103]
Windows 10 PC with usb camera attached. Attempting to stream usb video, microphone, and desktop screen display1.

iSpyServer's setting for start on boot up (this user only) does not work at all.

I created a scheduled task that starts ispyserver.exe at boot up as an administrator user with highest privileges. ispyserver.exe now runs successfully at start and I am able to access the video stream from my usb webcam and microphone. However, i am unable to access the desktop stream.
If i go to task manager, kill the background process ispyserver, then manually re-open the ispyserver app, it works perfectly. I have tried almost every combination and just can't access the desktop stream when starting under task scheduler.

I know i could just add the shortcut to shell:startup, but I would like to avoid having the user to have to yes/no the UAC prompt. I am also not willing to disable UAC.
The camera and microphone stream work perfectly when running under task scheduler. Is there a way of getting desktop stream to work as well?

**Comment by ispysoftware** [comment]
it needs to run under a user account to access the desktop - that's a windows thing unfortunately
