### ISSUE TITLE
Some motion doesn't trigger a recording

### ISSUE THREAD

**Issue by constantOut** [ispysoftware/iSpy#104]
Hello, thanks for a great software!
Somehow not all the motion is detected and changes in lighting conditions get detected as motion.
I'm using an Agent, does this repository contain it's sources ?

**Comment by ispysoftware** [comment]
Hello, Agent has a whole load of different motion detectors, see  the motion detector options when you edit the camera - you can detect on objects crossing trip wires or people detected or YOLO AI detected things like cats or cars.

If you are using the simple detector it just looks for changing pixels, which light changes cause in abundance.

If you are recording on Alert and not detect then there is a setting on the alerts tab that prevents multiple alerts in a 3 minute window called "Distinct Alert Interval" - change that if you are missing events or set it to record on detect instead.
