### ISSUE TITLE
Vritual Webcam Driver

### ISSUE THREAD

**Issue by ISimplifyComplexity** [ispysoftware/iSpy#105]
Hey, I tried to get the virtual webcam driver working. 

I ran the batch file with as admin, I even tried manually calling regasm myself. 

After a reboot the device doesn't seem to show anywhere. 

I'm using Windows 10. Can you confirm that this still works under Windows 10?

**Comment by ispysoftware** [comment]
Hello no i dont think it will - last time i used the virtual webcam driver was on windows 7. Microsoft changed a whole heap of driver related stuff with windows 10.

**Comment by ISimplifyComplexity** [comment]
Thanks for getting back to me.

That is a shame! I'm trying to figure out how I can feed images into a virtual webcam feed myself. 

I noticed that your library was written in C# with com interop. Many other sources state that .NET will not work with driver development yet you've somehow managed to over come this. 

How did you guys manage that? Are you coding against a generic driver? Is directshow giving you some sort of middleware option?

**Comment by ispysoftware** [comment]
I can't find the source code for it now but I think it was based off

https://www.codeproject.com/Articles/437617/DirectShow-Virtual-Video-Capture-Source-Filter-in

**Comment by ISimplifyComplexity** [comment]
You're a star! thank you. Would you like the source code? I can decompile the application for you if you like? I have JetBrains dotpeek.

**Comment by ispysoftware** [comment]
It's ok thanks - I've got it sitting on a hard drive somewhere round here!
If you get it working on Windows 10 please let me know.
