### ISSUE TITLE
Just installed on Ubuntu 18.04 fails to run see below

### ISSUE THREAD

**Issue by antonical** [ispysoftware/iSpy#106]
Just installed this software to trest whether to move from Motioneye.

Installed following this page https://www.ispyconnect.com/download.aspx Linux Tab
Installed dot net core following this page https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804

Tried running both without and with sudo. 

`sudo dotnet Agent.dll
Starting...
Initializing
Get com port list
Discover Onvif
Start network scan
IP addresses:
xxx.xxx.xxx.xxx
found xxx.xxx.xxx.xxx
Agent (v2.6.9.0)
Log start
Process is 64 bit
Init FFmpeg
ffmpeg path: /usr/lib/x86_64-linux-gnu
Initializing devices
Hardware Acceleration:
Hardware Support:
vdpau
cuda
vaapi
drm
opencl
call ffplay -f v4l2 -list_formats all /dev/video0
[video4linux2,v4l2 @ 0x7f5114000b80] raw       : bayer_grbg8 : 8-bit bayer grgr/bgbg : 320x240 640x480
call ffplay -f v4l2 -list_formats all /dev/video1
call arecord -l
Init Webrtc
Preloading Images
Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.CheckLibraryLoaded()
   at Emgu.CV.MatInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.MatInvoke.cveMatCreate()
   at CoreLogic.Utilities.Imaging.LoadStaticImages()
   at CoreLogic.Threads.StartUp()
   at AgentCore.Code.Initialize.Go()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted
`
So fails at first install and run. Can you advise either 1) How to get this running 2) How to clean up the mess of files installed by the above process.

Cheers
Spart

**Comment by ispysoftware** [comment]
have you tried (from the download page):

you can run ldd libcvextern.so to find out what's missing on your system.

you may need to install libtbb and libc6:
sudo apt-get install libtbb-dev
sudo apt-get install libc6-dev

to remove it just delete the directory

**Comment by antonical** [comment]
Brilliant, that allowed me to install lib-tbb and that then allowed the server to start.

Are you considering releasing a docker image as that is how I currently run Motioneye. Or maybe a snap for this as it seems very self contained.

Cheers
Spart

**Comment by scyto** [comment]
@ispysoftware I am getting the same error on Debian.  
I installed from your download page using https://ispyfiles.azureedge.net/downloads/Agent_Linux64_2_8_5_0.zip
Both libtbb and libc6 are installed and the output of ldd dd libcvextern.so just says"

``` ldd: ./libcvextern.so: No such file or directory

**Comment by ispysoftware** [comment]
didn't see the error message but i've updated the download instructions for linux and added a section for Debian.

https://www.ispyconnect.com/download.aspx

**Comment by scyto** [comment]
the error was identical to the OP but boiled down to "System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies."

New instructions seem to have helped. couple of things

1. I think you mean ``` sudo apt install multiarch-support``` not ```sudo apt install multi-arch support```

**Comment by ispysoftware** [comment]
ah ok - thanks, i copied/ pasted those commands from someone else that also ran into it, will update

**Comment by scyto** [comment]
@ispysoftware thanks for the prompt support, I didn't like the look of the docker container so I made my own in 3 hours, 2 hours of that was messing around with that error lol :-)

I will continue to play with the product tomorrow now I have it.  
I am retentive about small, optimized containers, what can I say.

If you are interested in my docker at all let me know....

![image](https://user-images.githubusercontent.com/11369180/88886041-87dc3a00-d1ee-11ea-875f-3bc36d8da984.png)

**Comment by ispysoftware** [comment]
sure, add a link if you like and i'll add it to the website.
