### ISSUE TITLE
Cannot connect to MJPEG stream with FFMPEG encoder

### ISSUE THREAD

**Issue by TheRolf** [ispysoftware/iSpy#110]
It works with interal encoder; it also works with FFMPEG encoder IF I provide the credentials in the link of the source (http://admin:password@x.x.x.x/mjpeg/video.mjpg). However seeing the password in plaintext bothers me.
Is this intended behaviour?

Using version 2.7.1.0. The relevant logs look like this on repeat:
`{"Created":"2020-05-15T12:52:48.6731644+02:00","Entry":"Cam4:CoreLogic.Sources.Combined.MediaStream:Reader: Cam4: OPEN_INPUT:Server returned 401 Unauthorized (authorization failed)","Type":"Error"},
{"Created":"2020-05-15T12:52:48.6731644+02:00","Entry":"Error: Cam4:CoreLogic.Sources.Combined.MediaStream:Reader: Cam4: OPEN_INPUT:Server returned 401 Unauthorized (authorization failed)","Type":"Message"},
{"Created":"2020-05-15T12:52:48.6731644+02:00","Entry":"Reconnecting Cam4  in 30s","Type":"Message"},
{"Created":"2020-05-15T12:53:19.2139112+02:00","Entry":"[http @ 00000000226f61c0] HTTP error 401 Unauthorized","Type":"Message"},
{"Created":"2020-05-15T12:53:19.2139112+02:00","Entry":"Cam4:CoreLogic.Sources.Combined.MediaStream:Reader: Cam4: OPEN_INPUT:Server returned 401 Unauthorized (authorization failed)","Type":"Error"},
{"Created":"2020-05-15T12:53:19.2139112+02:00","Entry":"Error: Cam4:CoreLogic.Sources.Combined.MediaStream:Reader: Cam4: OPEN_INPUT:Server returned 401 Unauthorized (authorization failed)","Type":"Message"},
{"Created":"2020-05-15T12:53:19.2139112+02:00","Entry":"Reconnecting Cam4  in 30s","Type":"Message"},
{"Created":"2020-05-15T12:53:49.9356684+02:00","Entry":"[http @ 00000000226f61c0] HTTP error 401 Unauthorized","Type":"Message"},
{"Created":"2020-05-15T12:53:49.9356684+02:00","Entry":"Cam4:CoreLogic.Sources.Combined.MediaStream:Reader: Cam4: OPEN_INPUT:Server returned 401 Unauthorized (authorization failed)","Type":"Error"},
{"Created":"2020-05-15T12:53:49.9356684+02:00","Entry":"Error: Cam4:CoreLogic.Sources.Combined.MediaStream:Reader: Cam4: OPEN_INPUT:Server returned 401 Unauthorized (authorization failed)","Type":"Message"},
{"Created":"2020-05-15T12:53:49.9356684+02:00","Entry":"Reconnecting Cam4  in 30s","Type":"Message"},
{"Created":"2020-05-15T12:54:10.2398297+02:00","Entry":"rtc:ondatachannelstatechange (download_1589540050237: Open)","Type":"Message"},
{"Created":"2020-05-15T12:54:10.2398297+02:00","Entry":"rtc: opened download_1589540050237","Type":"Message"},
{"Created":"2020-05-15T12:54:10.3398354+02:00","Entry":"rtc:ondatachannelstatechange (download_1589540050237: Closing)","Type":"Message"},
{"Created":"2020-05-15T12:54:10.3398354+02:00","Entry":"rtc:ondatachannelstatechange (download_1589540050237: Closed)","Type":"Message"},
{"Created":"2020-05-15T12:54:20.2374015+02:00","Entry":"[http @ 00000000226f61c0] HTTP error 401 Unauthorized","Type":"Message"}`

**Comment by ispysoftware** [comment]
That's the way usernames and passwords are passed to the ffmpeg library to play the streams. Unfortunately that's the only way to pass them in.

What's the problem with the logs? Are you saying it's not working on 2.7.1.0 or are you saying if you remove the login details you get 401 errors?

**Comment by TheRolf** [comment]
FFMPEG + http://admin:password@x.x.x.x/mjpeg/video.mjpg = works
Internal + http://x.x.x.x/mjpeg/video.mjpg + credentials in separate fields = works

FFMPEG +  http://x.x.x.x/mjpeg/video.mjpg + credentials in separate fields = doesn't work since 2.6.9.0, worked until 2.6.8.0

**Comment by ispysoftware** [comment]
I have no idea how that worked in 2.6.8.0, that means your camera was returning video without any username or password being passed into it. FFMPEG only takes credentials in that format, unless the URL had them appended to the end in some way.

**Comment by TheRolf** [comment]
Hmm, then I must've mixed up something. Thank you for the help!

**Comment by ispysoftware** [comment]
I can look into blocking out the credentials in the logs though. Prob a good idea.
