### ISSUE TITLE
Storage management (global) doesn't remove old recordings

### ISSUE THREAD

**Issue by TheRolf** [ispysoftware/iSpy#111]
I have a python code that puts all older recordings into subfolders every day. I used iSpy before, and storage management worked fine, it deleted the oldest recordings from these subfolders.
However now with Agent, the global storage management does not seem to work. 
The settings:
![image](https://user-images.githubusercontent.com/18666618/82056137-c9fee080-96c1-11ea-96c4-d0bd5a38af23.png)
And the logs:
`{"Created":"2020-05-15T15:18:11.746997+02:00","Entry":"Running storage management on d:\\Recordings\\","Type":"Message"},{"Created":"2020-05-15T15:18:15.1541919+02:00","Entry":"Storage monitor: 0 removed 0 failed","Type":"Message"}`

I have the old recordings under d:\\Recordings\\video\\Cam1\\archive\\ etc. The weird thing is, even newer recordings from the original folder d:\\Recordings\\video\\Cam1 are not deleted, even though the limit is clearly exceeded:
![image](https://user-images.githubusercontent.com/18666618/82056261-fadf1580-96c1-11ea-809b-db29daadf002.png)

I also tried setting a large limit for the individual cameras, and turning their own storage managements on, no luck. Using version 2.7.1.0.

**Comment by ispysoftware** [comment]
Do you have an archive location set?

**Comment by TheRolf** [comment]
No I don't. So this global storage management means how long recordings stay in the _archive_, and the individual ones mean when are they copied to the archive?

**Comment by ispysoftware** [comment]
no, stuff is only ever added to archive it's never deleted. It's just if
your archive is within your media folder then that would cause issues. I'm
not sure what's going on tbh, everything i'm testing here is working fine.
Could you zip up your Agent/Media/XML/config.xml and objects.xml file and
email it to me? sean at ispyconnect dot com

**Comment by ispysoftware** [comment]
I took a look at your config - it looks fine to me. I populated directories
with about 4gb of recordings (I don't have 1TB free space) and ran storage
management with the limit set to 100mb and it did exactly what it should be
doing... Running out of ideas on this one. Possibly it's something to do
with the culture code you have your system set to - what OS/ version are
you using and what's your OS culture set to?

**Comment by ispysoftware** [comment]
Also - it's possible there's a disk error on Drive D and the size it's returning in code isn't the size it's returning on windows - you could try running chkdsk on that drive

https://www.howtogeek.com/howto/windows-vista/guide-to-using-check-disk-in-windows-vista/

**Comment by TheRolf** [comment]
Weird indeed.
Chkdsk didn't show errors, I didn't do the /F /R options, but the error should be in the partition table or similar anyway.
Here's the OS culture info:
`Parent                         : sk
LCID                           : 1051
KeyboardLayoutId               : 1051
Name                           : sk-SK
IetfLanguageTag                : sk-SK
DisplayName                    : Slovak (Slovakia)
NativeName                     : slovenčina (Slovenská republika)
EnglishName                    : Slovak (Slovakia)
TwoLetterISOLanguageName       : sk
ThreeLetterISOLanguageName     : slk
ThreeLetterWindowsLanguageName : SKY
CompareInfo                    : CompareInfo - 1051
TextInfo                       : TextInfo - 1051
IsNeutralCulture               : False
CultureTypes                   : SpecificCultures, InstalledWin32Cultures, FrameworkCultures
NumberFormat                   : System.Globalization.NumberFormatInfo
DateTimeFormat                 : System.Globalization.DateTimeFormatInfo
Calendar                       : System.Globalization.GregorianCalendar
OptionalCalendars              : {System.Globalization.GregorianCalendar}
UseUserOverride                : True
IsReadOnly                     : False`

**Comment by ispysoftware** [comment]
I just uploaded an update that should log more details during storage management. If you could try debugging it yourself that would be good.. Create a new directory with one camera using it and a low limit with a us English name.. See if it works.. Add another camera.. See if you can figure out what is causing it.
