### ISSUE TITLE
Problems with nvidia encoder, strange errors

### ISSUE THREAD

**Issue by TheRolf** [ispysoftware/iSpy#112]
Agent seemingly randomly produces unplayable video files. It is not restricted to any camera, and it seems to randomly change over time. The unplayable files are ~7x smaller than the playable ones.
I noticed that the logs corresponding to the **normal** recordings have some error messages:
`{"Created":"2020-05-18T14:20:19.5217201+02:00","Entry":"Cam1: Recording Closed","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.604782+02:00","Entry":"[h264_nvenc @ 00000000005b5740] OpenEncodeSessionEx failed: out of memory (10): (no details)","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.6417841+02:00","Entry":"[h264_nvenc @ 00000000005b5740] No capable devices found","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.6417841+02:00","Entry":"Open Codec: Open Codec: Writer: Cam1: Open Codec:Generic error in an external library","Type":"Error"},`
`{"Created":"2020-05-18T14:20:20.6417841+02:00","Entry":"Error: Open Codec: Open Codec: Writer: Cam1: Open Codec:Generic error in an external library","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.6417841+02:00","Entry":"Open Codec:    at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code)\r\n   at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, HwEncoder gpu)","Type":"Error"},`
`{"Created":"2020-05-18T14:20:20.6417841+02:00","Entry":"Error: Open Codec:    at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code)\r\n   at CoreLogic.RealTime.MediaWriter.TryOpenVideoCodec(AVCodecID baseCodec, HwEncoder gpu)","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.6417841+02:00","Entry":"Writer: Cam1: Open Codec:Generic error in an external library","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.6427842+02:00","Entry":"Update graphics driver to use nvidia encoder","Type":"Message"},`
`{"Created":"2020-05-18T14:20:20.6657855+02:00","Entry":"using software encoder","Type":"Message"},`

However the **faulty** recordings have one single line in the log:
`{"Created":"2020-05-18T14:50:00.0655614+02:00","Entry":"Cam2: Recording Closed","Type":"Message"},`
I checked and have enough HDD storage, >1GB free RAM, >512MB free video memory at all times. I have a Geforce GT 730 with the latest nvidia drivers installed.
A faster CPU is on the way, but I was hoping I can get at least 5*5fps recrodings going until then, but maybe that's the issue? Currently having an Intel Celeron 2.30GHz.

**Comment by ispysoftware** [comment]
I'm guessing that the GPU encoder can only support a certain number of
simultaneous recordings. Is there a reason you aren't using the raw encoder?

**Comment by ispysoftware** [comment]
Think i've fixed this.. will be in next update.

**Comment by TheRolf** [comment]
In 7.2.3.0 it's fixed, successfully switches to software encoder if nvidia is not available.
My GPU should work in theory, however even then only 2 concurrent streams, so I don't bother debugging. Here's a list on nvidia GPU encoding/decoding capabilities:
https://developer.nvidia.com/video-encode-decode-gpu-support-matrix
