### ISSUE TITLE
Agent DVR Download

### ISSUE THREAD

**Issue by Urodela** [ispysoftware/iSpy#113]
I have a question about Agent DVR.
I am currently using Agent DVR on an intel NUC that is only connected to my PC via network but has no internet connection.

Agent DVR gets updates quite often and it is always a bit complicated to get the new version on the NUC. I use a VM that is online and install Agent DVR there and then copy the files to the NUC.

The Linux and also the MacOS version are both downloadable as binary versions, will this also apply to the Windows version at some point? That would be much easier than an installer that has to go online.

Thanks for reading and have a good day!

----
By the way, is there an ispy forum or is github the only way to communicate?

**Comment by ispysoftware** [comment]
Hello! Just github at the moment, we had forums but were dealing with too much spam.
you can download directly using

https://ispyfiles.azureedge.net/downloads/Agent_Windows64_2_7_9_0.zip

- just change the version number

**Comment by Urodela** [comment]
Awesome! Thanks a lot. This will make things much easier!
Have a nice day!
