### ISSUE TITLE
Problem getting Video URL for ONVIF cameras

### ISSUE THREAD

**Issue by setterlee** [ispysoftware/iSpy#114]
I have this issue while trying add ONVIF camera:

> Error: ONVIF Discovery: Failed getting device time - using system UTC time
> Error: ONVIF Device: ONVIF Device: An error occurred while sending the request.
> Error: ONVIF Device:    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
> --- End of stack trace from previous location where exception was thrown ---
>    at CoreLogic.Onvif.ONVIFDevice.GetDeviceCapabilities()
>    at CoreLogic.Onvif.ONVIFDevice.Connect()
> Error: inner:: An error occurred while sending the request.
> Error: inner:: The response ended prematurely.
> The response ended prematurely.
> Error: Failed to connect
> Error:    at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String cmd, String data, RTCSession session)
> Failed to connect

Steps to reproduce:

1. Add device
2. ONVIF
3. Configure (all options by default) -> OK
4. Source type -> ONVIF -> (specifying correct username and password and this for service URL: http://{my ip camera}:{service port that in my case is 5000})
5. the other options by default
6. get video URLs

 

Agent DVR version: 2.8.0
Environment: ubuntu 18.04
Camera: Generic managed with Yoosee with onvif support.

**Comment by ispysoftware** [comment]
Does it work on "onvif device manager" ? Are you able yo port forward the camera and send me a login do I can debug it from here?

**Comment by setterlee** [comment]
"onvif devive manager"? the app? yep, with that app can access to my cameras... I have two of then with the same model.

I sent you info via email for debug... thanks

**Comment by ispysoftware** [comment]
Hello, make sure you have 

http://x.x.x.x:5000/onvif/device_service

in service url, then select advanced from the drop down at the top (where it says Video Source) and change the RTSP mode to UDP.

That got it working ok here.

**Comment by setterlee** [comment]
Sean, 

works very well on windows but in ubuntu still drop the same error...

> Starting...
> Initializing
> Get com port list
> Discover Onvif
> Start network scan
> IP addresses:
> 192.168.155.2
> found 192.168.155.1
> found 192.168.155.2
> found 192.168.155.3
> found 192.168.155.6
> found 192.168.155.8
> found 192.168.155.10
> found 192.168.155.12
> found 192.168.155.13
> found 192.168.155.9
> found 192.168.155.35
> found 192.168.155.7
> found 192.168.155.34
> found 192.168.155.41
> found 192.168.155.120
> found 192.168.155.123
> found 192.168.155.30
> found 192.168.155.169
> found 192.168.155.229
> found 192.168.155.226
> found 192.168.155.128
> Agent (v2.8.0.0)
> Log start
> Process is 64 bit
> Init FFmpeg
> ffmpeg path: /usr/lib/x86_64-linux-gnu
> Initializing devices
> Hardware Acceleration:
> Hardware Support:
> vdpau
> cuda
> vaapi
> drm
> opencl
> call ffplay -f v4l2 -list_formats all /dev/video0
> call arecord -l
> Error: No audio devices found
> Init Webrtc
> Preloading Images
> MQTT not configured or enabled
> Loaded 0 cameras and 0 mics from /opt/agent/Media/XML/objects.xml
> Using default port (8090)
> Local Server running on port 8090
> ZeroConf: ZeroConf Service Started
> Running at http://localhost:8090
> rtc:added servers
> rtc:inited peer connection (True)
> rtc:set flag
> rtc:onsuccessanswer
> ICE state: Checking
> ICE state: Connected
> rtc:ondatachannelstatechange (serverdata: Open)
> rtc: opened serverdata
> rtc:ondatachannelstatechange (talk: Open)
> rtc: opened talk
> Error: ONVIF Discovery: Failed getting device time - using system UTC time
> Error: ONVIF Device: ONVIF Device: An error occurred while sending the request.
> Error: ONVIF Device:    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
>    at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
> --- End of stack trace from previous location where exception was thrown ---
>    at CoreLogic.Onvif.ONVIFDevice.GetDeviceCapabilities()
>    at CoreLogic.Onvif.ONVIFDevice.Connect()
> Error: inner:: An error occurred while sending the request.
> Error: inner:: The response ended prematurely.
> The response ended prematurely.
> Error: Failed to connect
> Error:    at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String cmd, String data, RTCSession session)
> Failed to connect

Is weird that work in windows on udp port because nmap just show me tcp port open for the camera with the local ip address. 

> Starting Nmap 7.80 ( https://nmap.org ) at 2020-07-01 22:17 -04
> Nmap scan report for 192.168.155.41
> Host is up (0.039s latency).
> Not shown: 998 closed ports
> PORT     STATE SERVICE
> 554/tcp  open  rtsp
> 5000/tcp open  upnp
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.97 seconds

**Comment by ispysoftware** [comment]
ok please leave the camera up, will investigate with ubuntu

**Comment by ispysoftware** [comment]
I think i've found the issue - netcore is ignoring the expect100continue setting in the .net framework and is sending it to the camera which is then not responding - I need to write some middleware to remove the header, hopefully that will fix it.

**Comment by ispysoftware** [comment]
i've uploaded an update - i can connect to your camera from ubuntu with that and get the media endpoints but i can't actually stream video from it - i think because ubuntu is running on a VM and the UDP packets aren't being forwarded. It's all working fine on the host (windows) machine.

**Comment by setterlee** [comment]
I just tested on my linux server and it works...! And tested with a Docker VM and didn't work but that is a issue related with the VM, I will investigate that but the app is ok... thanks a lot Sean!!!

**Comment by setterlee** [comment]
Sean, 

if I understand, the app send request to the camera via udp port, the camera send back something to the software via udp in a different port? because inside a VM, the traffic from the VM to the world is open, the restriction are from the world to the VM. 

Maybe if we have (i say "we" because i know that there is a lot of people using this app in docker containers) the port that we must open on the container, could solve the problem... After monitoring the ports inside the VM, i saw different upd ports movement on each instance

one case:

> 
> tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      1/dotnet            
> tcp        0      0 192.168.99.100:42597    0.0.0.0:*               LISTEN      1/dotnet            
> tcp        0      0 10.0.2.15:36525         0.0.0.0:*               LISTEN      1/dotnet            
> udp        0      0 192.168.99.100:5353     0.0.0.0:*                           1/dotnet            
> udp        0      0 10.0.2.15:5353          0.0.0.0:*                           1/dotnet            
> udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1/dotnet            
> udp        0      0 192.168.99.100:43328    0.0.0.0:*                           1/dotnet            
> udp        0      0 10.0.2.15:59734         0.0.0.0:*                           1/dotnet            
> udp        0      0 0.0.0.0:32796           0.0.0.0:*                           1/dotnet            
> udp        0      0 0.0.0.0:32797           0.0.0.0:*                           1/dotnet            
> udp        0      0 0.0.0.0:32798           0.0.0.0:*                           1/dotnet            
> udp        0      0 0.0.0.0:32799           0.0.0.0:*                           1/dotnet            
> udp6       0      0 :::5353                 :::*                                1/dotnet     

Other case:

> 
> root@default:/# netstat -plnt --udp | grep dotnet
> tcp        0      0 10.0.2.15:49811         0.0.0.0:*               LISTEN      1/dotnet            
> tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      1/dotnet            
> tcp        0      0 192.168.99.100:60613    0.0.0.0:*               LISTEN      1/dotnet            
> udp        0      0 10.0.2.15:59595         0.0.0.0:*                           1/dotnet            
> udp        0      0 192.168.99.100:5353     0.0.0.0:*                           1/dotnet            
> udp        0      0 10.0.2.15:5353          0.0.0.0:*                           1/dotnet            
> udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1/dotnet            
> udp        0      0 192.168.99.100:48067    0.0.0.0:*                           1/dotnet            
> udp6       0      0 :::5353                 :::*                                1/dotnet

**Comment by ispysoftware** [comment]
Yes this port forwarding issue is also why the webrtc stuff isn't working over docker. We basically need open traffic back to the vm. Running in host mode should fix it but unfortunately that isn't available cross platform. https://docs.docker.com/network/host/

**Comment by ispysoftware** [comment]
there are some potential workarounds here:
https://forums.docker.com/t/unable-to-get-container-to-recieve-udp-port-traffic-from-host/29762
