### ISSUE TITLE
Can not view Form in Design mode

### ISSUE THREAD

**Issue by bearmen** [ispysoftware/iSpy#115]
Sorry for bother you but i need your help.
I can build and run ispy without error, but when i view form in design mode (all form have iSpyApplication.Controls....), i always got error "Could not find type ..."
What should i do ?
Thank you.
p/s: i got error when build it in x86 so i build it in x64

![2020-07-07_09-29-35](https://user-images.githubusercontent.com/67936790/86693535-f46f7900-c034-11ea-9c75-bc3d5d555bbf.jpg)

**Comment by ispysoftware** [comment]
close the designer (don't save changes) and make sure it's been built in debug mode then reopen the designer. I get the same error sometimes and have to restart visual studio to get it to load - not sure what causes it.

**Comment by bearmen** [comment]
Ah thank you for advice.
i solved it.
- First, i rebuilt it in x64 debug mode (still got error)
- Then, i rebuilt it in x86 debug mode (got another error about Interop.NETWORKLIST)
- So i remove it and add reference another NETWORKLIST dll. Unfortunately, in your DLLS/x86 folder not have this DLL. So i search on inernet and found NETWORKLIST dll for x86 mode.
i attach NETWORKLIST dll file for someone got same error with me :)
[Interop.NETWORKLIST.zip](https://github.com/ispysoftware/iSpy/files/4888058/Interop.NETWORKLIST.zip)
![image](https://user-images.githubusercontent.com/67936790/86867016-416a5280-c0fc-11ea-8b1c-a931441346a8.png)

**Comment by ispysoftware** [comment]
thanks have added that to the repo
