### ISSUE TITLE
H264 running insane frame with Local Video File / VLC GPU decoding doesn't work

### ISSUE THREAD

**Issue by Zeliper** [ispysoftware/iSpy#116]
Sry for my bad english

Hi I'm studient from Korea
Your iSpy is very helpful for my RTSP Projects. TY for you Greate Works
But I have some problem.

If I use H264(ffmpeg) decoder for my rtsp Stream with GPU that works nice.
But if I use H264 decoder for my local video file like(C;\4.mp4) with GPU, the decoder get frame too fast.(ex:when video fps is 30, decoder get 260 fps and get lagging at display)

So I tried load video with VLC Plugin, But VLC doesn't use my GPU, also i typed arguments(--ffmpeg-hw)

How can i solve this problem?

I need help that H264 decoder get local video correctly

Image is when I get local video on H264 decoder(it gets over 320 fps)
![iSpy_4VegTXQiP1](https://user-images.githubusercontent.com/24862471/88007149-468dbf80-cb48-11ea-934d-f985e949aa09.jpg)

spec :
- CPU : i7-9750H
- GPU : RTX 2060
- RAM: 32GB
- OS : Windows 10 x64

**Comment by ispysoftware** [comment]
hello iSpy doesn't support file video with ffmpeg, just with VLC, ffmpeg will process it as fast as possible (as if it were a real-time stream). You could try using our new platform, Agent, which does support file video via ffmpeg.
http://www.ispyconnect.com/download.aspx

**Comment by Zeliper** [comment]
TY for reply.
Can you advise to ffmpeg decoder get file video correctly?
Is get frame that same method as use av_read_frame() in file video?

You don't must answer this comment.
But There are not enough materials to study that ffmpeg/rtsp stream processing. 
Need some help XD

**Comment by ispysoftware** [comment]
You need to add code to mediastream.cs to delay the playback to make it
match the timestamps in the streams, for example:

long _bestEffortTimestamp,  _firstTimestamp = 0;
var start = DateTime.UtcNow;

after avcodec_receive_frame:

 _bestEffortTimestamp = vf->best_effort_timestamp;
                                if (_firstTimestamp == 0)
                                    _firstTimestamp = _bestEffortTimestamp;

before end of read frames loop:

 if (isFile && _firstTimestamp>0)
                        {
                            var pts = _bestEffortTimestamp *

(Convert.ToDouble(_videoStream->time_base.num) /
Convert.ToDouble(_videoStream->time_base.den)) *
                                      1000;
                            var ptsref = _firstTimestamp *

 (Convert.ToDouble(_videoStream->time_base.num) /
Convert.ToDouble(_videoStream->time_base.den)) *
                                         1000;

                            var ms = (DateTime.UtcNow -
start).TotalMilliseconds;
                            var msSleep = (pts - ptsref)- ms;
                            if (msSleep < 500)
                            {
                                if (msSleep > 0)
                                    Task.Delay((int)msSleep).Wait();
                                ret = 0;
                            }
                            else
                            {
                                start = start.AddMilliseconds(0-msSleep);
                            }
                        }
