### ISSUE TITLE
Agent Server on Ubuntu 18.04

### ISSUE THREAD

**Issue by jholden19** [ispysoftware/iSpy#117]
I have installed the Agent Server on Ubuntu 18.04. When running the Agent.dll, I receive the following error message: Error: Unable to load DLL 'avutil.56': The specified module could not be found.

I have searched my installation and cannot find either avutil.56 or avutil-56.dll.

Here is the agent output:

Starting...
Initializing
Get com port list
Discover Onvif
Start network scan
IP addresses:
found 10.10.10.145
Agent (v2.8.5.0)
Log start
Process is 64 bit
Init FFmpeg
ffmpeg path: /usr/lib/x86_64-linux-gnu
Error: Unable to load DLL 'avutil.56': The specified module could not be found.
Error:    at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_604(Int32 level)
   at FFmpeg.AutoGen.ffmpeg.av_log_set_level(Int32 level)
   at CoreLogic.FFmpeg.SetFfmpegLogging(Int32 loglevel)
   at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Unable to load DLL 'avutil.56': The specified module could not be found.
Install FFMPEG (v4.2) using the terminal. Run 'sudo apt install ffmpeg'
Killed

**Comment by ispysoftware** [comment]
you need to install ffmpeg - see the instructions on
https://www.ispyconnect.com/download.aspx

**Comment by jholden19** [comment]
Hi Sean.. Thank you for your response.

I followed these instructions and have ffmpeg version 4.3 installed. Is it
required to be version 4.2?

Jonathan

**Comment by ispysoftware** [comment]
im not sure about that, i've only tested it with 4.2, might work - give it a go and let me know.

**Comment by jholden19** [comment]
Thanks Sean. I followed the installation instructions on the website and
that is how version 4.3 was installed. If you need 4.2, those instructions
should be updated.

On your Ubuntu installation, which directory is the file avutil.56 in? Do
you see a file avutil-56.dll anywhere? What about avutil-55?

Also do you know where I can get ffmpeg version 4.2 to install?

Thanks again for your help.

Jonathan

**Comment by ispysoftware** [comment]
I think 4.3 should be fine, looking at it there hasn't been a version bump on avutil, it's still 56
on my ubuntu it's in /usr/lib/x86_64-linux-gnu/libavutil.so.56

**Comment by jholden19** [comment]
Hey Sean

When I search my installation, libavutil.so.56 is located in
/usr/lib/aarch64-linux-gnu.

/usr/lib/x86_64-linux-gnu is a file on my installation and not a directory.

ubuntu@ubuntu:/usr/lib$ stat x86_64-linux-gnu
  File: x86_64-linux-gnu
  Size: 671232          Blocks: 1312       IO Block: 4096   regular file
Device: b302h/45826d    Inode: 7330        Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-07-26 02:31:22.025169006 +0000
Modify: 2020-07-24 00:04:24.195049526 +0000
Change: 2020-07-24 00:04:24.195049526 +0000
 Birth: -

Should I try deleting the x86_64-linux-gnu file and create symbolic link
that points x86_64-linux-gnu to my aarch64-linux-gnu directory?

Jonathan

**Comment by jholden19** [comment]
Hi Sean

The symbolic link got me around the ffmpeg issue I was having.

When running Agent.dll, I am now getting an error with
jingle_peerconnection_so. Do you know what this might be about?

Here is the full information:

Init Webrtc
Unhandled exception. System.TypeInitializationException: The type
initializer for 'Pixiv.Rtc.ThreadManager' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library
'jingle_peerconnection_so' or one of its dependencies. In order to help
diagnose loading problems, consider setting the LD_DEBUG environment
variable: libjingle_peerconnection_so: cannot open shared object file: No
such file or directory
   at Pixiv.Rtc.ThreadManager.rtcThreadManagerInstance()
   at Pixiv.Rtc.ThreadManager..cctor()
   --- End of inner exception stack trace ---
   at Pixiv.Rtc.ThreadManager.get_Instance()
   at CoreLogic.Threads.StartUp()
   at AgentCore.Code.Initialize.Go()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)


I have the jingle_peerconnection_so.so file installed.

The message references setting the LD_DEBUG variable. Should I set this
variable? If so, where would I do this?

Do you have any other recommendations for me to try?

Thanks
Jonathan

**Comment by ispysoftware** [comment]
Hello, i'm not sure what's going on here, possibly it's something to do with you having aarch64 instead of x86_64? A clean run of the install instructions on ubuntu 18.04 here is working fine (i know that's not much help!)

When I've had these issues in the past I've found ldd to be of great help with tracking down what's missing on the system

https://www.lifewire.com/find-shared-libraries-ldd-command-4017941
