### ISSUE TITLE
need support for JCBP -  jvc PTZ control over serial (RS485)

### ISSUE THREAD

**Issue by mtamarsky** [ispysoftware/iSpy#118]
i have JVC TK-C676E, this cam have  JCBP -  jvc PTZ control over serial (RS485).
Does any body have description of JCBP ?  Or have some patch for this protocol?
Can anybody make trace of signals from compatible RM-P2580 controller ?

**Comment by ispysoftware** [comment]
ispy has support for pelco cameras which use RS485 serial port comms
it's taken from:
https://www.codeproject.com/Articles/8034/Pelco-P-and-D-protocol-implementation-in-C
not sure if this is compatible with your JVC camera but it would be a good starting point if not.

**Comment by mtamarsky** [comment]
pelco is not compatible with JCBP, 
does any body have or can make sniff serial port command for basic PTZ-z like  UP/DOWN LEFT/RIGHT ZOOM  FOCUS and IRIS and may be other ?

**Comment by mtamarsky** [comment]
JCBP have short commands without any crypto or hard defined fields..

**Comment by ispysoftware** [comment]
hmm I had a good look and didn't have much luck finding any description of JCBP online - if you have a camera of theirs your best bet is to email JVC and ask them for an SDK or API for their cameras. They must have one as some other software has it listed.

**Comment by mtamarsky** [comment]
Now, i have this information:
Each command have 7/6 byte long.
HEX,  
NN - cam addr zero based(real addr -1)
XX - parameter - speed or preset number
B101NN834500XX  right
B101NN834501XX  left
B101NN834503XX  up
B101NN834504XX  down

B101NN83450C02  zoom in
B101NN83450D02  zoom out

B101NN83451F     autofocus on
B101NN83450A02  focus out
B101NN83450902  focus in

B101NN8342XX       go preset 
B101NN834528XX   set peset

B101NN834502  stop,  what to stop ?
B101NN834505  stop,  what to stop ?
B101NN83450E  stop,  what to stop ?
B101NN83450B  stop,  what to stop ?
