### ISSUE TITLE
Update on plans to open source agent

### ISSUE THREAD

**Issue by mjbedford2017** [ispysoftware/iSpy#122]
Hello Sean, any update on plans to open source agent? I saw a closed topic where you said you would consider it if there is enough demand. Has there been enough? I am certainly interested, mainly because I would like to correct a few things and extend some capability. 

Thanks!

**Comment by ispysoftware** [comment]
Hello, no not really. I recently found that several competing closed source products have taken massive chunks of the ispy and website code base and are selling them / using them for seo which has put me off open sourcing agent quite a bit. If you have bug reports or feature requests I'm happy to hear them.. Or I could add you to the private repo if it's something extensive.

**Comment by mjbedford2017** [comment]
Hello Sean. Well, that really pisses me off, as I am sure it does you. Even though source code can be open source, as you have so graciously done with iSpy, it is still stealing to do what others have done and it hurts open source for what open source is meant to be. It really ruins it for everyone else. I don't expect you to do this but I would love if you released a list of these "competing" products so we can get the word out and avoid them at all costs. Anyway, enough of that stuff. Here is the thing, I have some feature requests and we can do that as well. However, one of the beauties of open source, as you know, is time by having many different people improving, bug fixing, adding features, etc.. for the good of the project. I am happy to do the work instead of having to explain it and have you have to do the work. So, it is your call at this point. I can list it all out, explain it, etc.. or if you want to add me to the private repo, that would be cool too and I would be happy to do a PR and make the changes myself and you can then decide if they are worthy enough to merge in. Thanks Sean!

**Comment by ispysoftware** [comment]
sent you a pm

**Comment by mjbedford2017** [comment]
I got it. Will get going on it in the next day or so.

Thank you!!

I do have two questions:
1. What do you mean by agent "min"? Is this a light or minimum version of
agent?
2. Most importantly, does agent support the use of "Plugins" like iSpy
does? I have a plugin that I developed to use with iSpy and I was wondering
if that plugin would work out of the box with agent as well.

Thanks!

**Comment by ispysoftware** [comment]
min is just that agent has a whole load of orbitting projects that are built for it that i've included there as pre-built binaries for win x64 specifically. The whole solution building for all platforms with all projects is enormous.

it does support plugins although I don't have an example plugin project I can share with you right now. The plugins for iSpy are windows forms based plugins so would need to be updated to use the web rendering engine instead.
