### ISSUE TITLE
Center Object when click on Screen using PTZ

### ISSUE THREAD

**Issue by bearmen** [ispysoftware/iSpy#125]
Sorry for bother you but i need your help.
How to use PTZ to center the object when clicking on the screen?

my idea is move an angle (up right/down right/up left/down left), then send stop and move on line (left, right, up, down).
but the problem is: **How do i define the time to send stop command?**

**Comment by ispysoftware** [comment]
hello generally it repeatedly sends the movement command until mouse-up when it sends the stop command

**Comment by bearmen** [comment]
thank for reply. But user not click on PTZ control, they click (not hold) on camera and PTZ will move ultil clicked point on camera is center.
i saw [this post](https://stackoverflow.com/questions/60203938/converting-x-y-values-from-on-screen-click-to-onvif-ptz-pan-tilt-values) but i don't know how to do that :(

**Comment by ispysoftware** [comment]
hello this isn't really an issue with iSpy - it's more of a request to add a feature - it's open source so you are welcome to modify the code to do this.
