### ISSUE TITLE
ieGeek Solar Powered Battery IP Camera

### ISSUE THREAD

**Issue by dsEngineer** [ispysoftware/iSpy#126]
Hey kind folks,

I'm new to GitHub and do not know where to leave a general question. So I'm posting it here :)

I downloaded the VS solution and built the executable for Windows. I attempted to get the iSpy exe to work with an ieGeek Solar Powered Battery IP Camera. I could not get it to work. I contacted the company to ask if it was rtsp/html/miscIP compliant. they stated that it wasn't and that they were focused on 'mobile' platforms. So I've had to return the camera unit.

So my question is this. What new cameras have people verified that works with iSpy desktop application?

Ideally I would want a wireless camera. If it's solar powered, even better. This is the camera that I had to return: 

https://www.amazon.com/Wireless-Rechargeable-Surveillance-Detection-Waterproof/dp/B082KWD94W/ref=sr_1_3?crid=5K12LZ2KBAWZ&dchild=1&keywords=legeek+security+camera&qid=1602556061&sprefix=leGeek%2Celectronics%2C798&sr=8-3

thanks

**Comment by ispysoftware** [comment]
hello any onvif compatible camera should be compatible with ispy/ agent
-just avoid ones that are tied into proprietary services like nest. D-link
and Foscam cameras should work fine as well as long as they haven't decided
to go the proprietary route. Check https://www.ispyconnect.com/sources.aspx
for a full list

**Comment by dsEngineer** [comment]
Thanks!
I ordered this ONVIF compliant camera. 
https://www.amazon.com/Wireless-Security-Waterproof-Protocol-Surveillance/dp/B07YWFP8WG/ref=sr_1_14?dchild=1&keywords=camera+ONVIF&qid=1602608678&s=electronics&sr=1-14
Will let you guys know if it works when I receive it. Thanks!
