### ISSUE TITLE
Request: Replace downloadable WiX with MSVS WiX extensions.

### ISSUE THREAD

**Issue by tolginator** [ispysoftware/iSpy#13]
Bootstrap64, iSpy64Setup, and WiXCA fail to load in MSVS 2015 even when the WiX MSVS extensions is installed. It doesn't make a lot of sense to require a separate install from some unknown source instead of building on the WiX extension.

**Comment by ispysoftware** [comment]
Loads fine in my VS 2015 - what errors are you getting?

**Comment by tolginator** [comment]
I don't have the separate WiX installed indicated by the instructions, but only the VS WiX extension. It is the usual VS modal error dialog: "One or more projects in the solution were not loaded corectly. Please see the Output for details", and the output says the following:

C:\Users\DevUser\Documents\iSpy\iSpy\Wix\iSpy64\iSpy64Setup.wixproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\DevUser\Documents\iSpy\iSpy\Wix\iSpy64\iSpy64Setup.wixproj
C:\Users\DevUser\Documents\iSpy\iSpy\Wix\Bootstrap64\Bootstrap64.wixproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\DevUser\Documents\iSpy\iSpy\Wix\Bootstrap64\Bootstrap64.wixproj
C:\Users\DevUser\Documents\iSpy\iSpy\Wix\WixCA\WixCA.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\DevUser\Documents\iSpy\iSpy\Wix\WixCA\WixCA.csproj

**Comment by ispysoftware** [comment]
Have you installed the wix toolset?

http://wixtoolset.org/

**Comment by tolginator** [comment]
Well, that's the idea: don't install a stand-alone tool, and only get it done with VSTS extensions. I get it if that is too much of a hassle.
