### ISSUE TITLE
Cycle delay in GridView

### ISSUE THREAD

**Issue by ahghygy** [ispysoftware/iSpy#133]
Hi Guys,

the Cycle delay in GridView default value is 4, so anyone know how to set the value.

And I find gridview is slower than main camera window, when max the gridview camera window, more slow.

**Comment by ahghygy** [comment]
![1](https://user-images.githubusercontent.com/25763592/99782859-acb93c00-2b54-11eb-9d16-6f4ebfa1aabc.png)

**Comment by ispysoftware** [comment]
it sounds like your video card is struggling - you could try in ispy click view - layout - minimized and see if that helps. I'm not sure what you mean about setting the cycle delay - you just need to select a few cameras (using ctrl or shift click) and then change that value to something else..

**Comment by ahghygy** [comment]
So，what is  "cycle delay " ?  how it effect?
For example , if I set the value =4  or I set the value=100, i can not find any different between 4 and 100.
So, waht is the real function of the "cycle delay "

**Comment by ispysoftware** [comment]
it's the delay in seconds between cycling between cameras when there is
more than one camera in a grid position. If you only have one camera in a
grid position it will have no effect.
