### ISSUE TITLE
PTZ for v380 Shenzhen IP Camera

### ISSUE THREAD

**Issue by drtanzil** [ispysoftware/iSpy#136]
v380 (Chinese) / Shenzhen camera is not listed on iSpy
I was able to connect v380 with rtsp both FFMPEG & VLC & video works OK with iSpy
However PTZ is not working.
I've tried ONVIF device manager & PTZ is working OK there.

Could you please let me know how to configure PTZ for v380 ?

v380 camera has TCP port open: 554, 8899, 8800 & 9800

Thanks in advance.

**Comment by bearmen** [comment]
maybe you should check and change videoSourceIndex = 9 when connect your CAM

**Comment by ispysoftware** [comment]
see Adding PTZ Support for Unlisted Cameras
https://www.ispyconnect.com/userguide-ptz.aspx

if it supports onvif then add it as an onvif device instead and ptz should work

**Comment by drtanzil** [comment]
@ispysoftware : On that link, instruction is not clear. There's no example how to make custom XML file for new camera, no documentation what different parameter mean on PTZ2.xml.

I'm not quite familiar with camera firmware platform. However v380 has opensource SDK on git & expert programmer like you can easily include the PTZ for iSpy. the src is [here](https://github.com/brusdev/V380-SDK/blob/master/nvsdk_demo/app/src/main/java/com/macrovideo/demo/DemoPlayActivity.java) 

Thanks again for the support & great work!

**Comment by ispysoftware** [comment]
the xml is pretty self explanatory - any questions just ask - did you try with onvif?

**Comment by drtanzil** [comment]
@ispysoftware : yes I tried ONVIF from iSpy and not working.

I've found a python source code which control PZT. But can't figure it out how to use that XML on iSpy. I'm pasting it here-

PZT control URL for RTSP:

`http://192.168.0.131:8899/onvif/ptz', data=xml`

XML for left

```
<s:Envelope
        xmlns:s="http://www.w3.org/2003/05/soap-envelope">
        <s:Body
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <ContinuousMove
                xmlns="http://www.onvif.org/ver20/ptz/wsdl">
                <ProfileToken>
                    stream0_0
                    </ProfileToken>
                <Velocity>
                    <PanTilt
                        x="0.5"
                        y="0"
                        xmlns="http://www.onvif.org/ver10/schema"/>
                    </Velocity>
                </ContinuousMove>
            </s:Body>
        </s:Envelope>
```

XML For Right

```
<s:Envelope
        xmlns:s="http://www.w3.org/2003/05/soap-envelope">
        <s:Body
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <ContinuousMove
                xmlns="http://www.onvif.org/ver20/ptz/wsdl">
                <ProfileToken>
                    stream0_0
                    </ProfileToken>
                <Velocity>
                    <PanTilt
                        x="-0.5"
                        y="0"
                        xmlns="http://www.onvif.org/ver10/schema"/>
                    </Velocity>
                </ContinuousMove>
            </s:Body>
        </s:Envelope>
```

XML for Up

```
<s:Envelope
        xmlns:s="http://www.w3.org/2003/05/soap-envelope">
        <s:Body
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <ContinuousMove
                xmlns="http://www.onvif.org/ver20/ptz/wsdl">
                <ProfileToken>
                    stream0_0
                    </ProfileToken>
                <Velocity>
                    <PanTilt
                        x="0"
                        y="0.5"
                        xmlns="http://www.onvif.org/ver10/schema"/>
                    </Velocity>
                </ContinuousMove>
            </s:Body>
        </s:Envelope>
```

XML for down

```
<s:Envelope
        xmlns:s="http://www.w3.org/2003/05/soap-envelope">
        <s:Body
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <ContinuousMove
                xmlns="http://www.onvif.org/ver20/ptz/wsdl">
                <ProfileToken>
                    stream0_0
                    </ProfileToken>
                <Velocity>
                    <PanTilt
                        x="0"
                        y="-0.5"
                        xmlns="http://www.onvif.org/ver10/schema"/>
                    </Velocity>
                </ContinuousMove>
            </s:Body>
        </s:Envelope>
```

Here is the git link for v380 control: [https://github.com/Gowresh7/V380_Python](https://github.com/Gowresh7/V380_Python)

**Comment by drtanzil** [comment]
I've tested on Fiddler. Posting

```
<s:Envelope
        xmlns:s="http://www.w3.org/2003/05/soap-envelope">
        <s:Body
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <ContinuousMove
                xmlns="http://www.onvif.org/ver20/ptz/wsdl">
                <ProfileToken>
                    stream0_0
                    </ProfileToken>
                <Velocity>
                    <PanTilt
                        x="0.5"
                        y="0"
                        xmlns="http://www.onvif.org/ver10/schema"/>
                    </Velocity>
                </ContinuousMove>
            </s:Body>
        </s:Envelope>
```

is moving the camera to left. Code is working. Now stuck at how to implement it on iSpy's PTZ2.xml.

**Comment by ispysoftware** [comment]
Those are onvif commands. You should be using the onvif source type and
make sure that onvif is selected on the PTZ tab. Our new platform Agent has
new onvif code that you could try.

**Comment by drtanzil** [comment]
@ispysoftware : Thanks a lot. Finally its been solved.
1. Camera src need to ONVIF
2. PTZ need to ONVIF

That works! I was trying to make it work since last 3 days and finally it worked! Thanks!
Can we control Movement speed?

**Comment by 0zoon0** [comment]
@drtanzil how did you add this camera using ONVIF? 
@ispysoftware the thing is that this camera implements few PTZ endpoints only (looks like ContinousMove, AbsoluteMove and Stop), but no other ONVIF endpoints. So when I'm trying to add it as ONVIF camera iSpy is checking /onvif/device_service endpoint and there is no good response from the camera. So it keeps saying "Please select the camera". I cannot add it as ONVIF camera. But I can add it using wizard as it has rtsp endpoint. Then I go to PTZ configuration, choose ONVIF, input port 8899 (because /onvif/ptz endpoint is responding on that port), but iSpy is not sending SOAP any PTZ requests to the camera. And it looks like I cannot define a new PTZ model for SOAP requests. Is there anything else I can do to have PTZ workingas ONVIF when camera is not registered as ONVIF camera?
Thank you so much.

**Comment by ispysoftware** [comment]
yeah it wont work unless the whole connection to the camera is onvif. The
video source sets up the connection and the ptz then piggy backs off that
for commands.
you might need to check the port it's using for onvif, frequently it's not
the same port as for general web access.

**Comment by 0zoon0** [comment]
> you might need to check the port it's using for onvif, frequently it's not the same port as for general web access.
Running nmap gives me 554, 8800, 8899. 554 this is rtsp, 8800 is closing the connection without any response for any SOAP requests, and 8899 is returning 400 Bad Request for any path except for /onvif/ptz.
So, I believe it has no onvif/device_service enpoint implemented.

I hope @drtanzil would tell us how he managed to add it to ispy.

Thank you for quick reply.

**Comment by shahriarsaem** [comment]
Can anyone tell me how to check which ports are open in v380 camera?
