### ISSUE TITLE
Startup Messages in Ubuntu LTS 20.4 Focal

### ISSUE THREAD

**Issue by OS4F** [ispysoftware/iSpy#137]
Hi,

I have installed the iSpy Agent on Ubuntu 20.4 Focal, and everything seems to be working.  However I do see the following messages in "/var/log/syslog" regarding libopencv. Are these messages something I should be concerned about, and is it something that I need to fix?

	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_videoio_ffmpeg420_64.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_core420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_imgproc420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_video420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_flann420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_ml420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_imgcodecs420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_videoio420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_highgui420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_objdetect420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_features2d420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_calib3d420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudaarithm420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudawarping420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudafilters420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudaimgproc420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudalegacy420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudaoptflow420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudastereo420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudabgsegm420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudafeatures2d420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudacodec420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudaobjdetect420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_photo420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_superres420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_videostab420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_shape420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_cudev420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_face420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_ximgproc420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_xobjdetect420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_xfeatures2d420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_xphoto420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_bgsegm420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_optflow420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_stitching420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_plot420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_dnn420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_dnn_objdetect420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_dnn_superres420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_aruco420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_fuzzy420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_viz420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_bioinspired420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_text420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_tracking420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_dpm420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_saliency420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_img_hash420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_phase_unwrapping420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_freetype420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_hfs420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_quality420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_stereo420.so do not exist.
	Dec  5 17:24:21 blazeagator dotnet: File /home/dotnetuser/iSpy/libopencv_surface_matching420.so do not exist.

CML Startup
	root@blazeagator:~# dotnet /home/dotnetuser/iSpy/Agent.dll
	Starting...
	Creating temp path for opencv in /tmp/
	Get com port list
	Discover Onvif
	Start network scan
	IP addresses:
	192.168.0.208
	found 192.168.0.1
	found 192.168.0.4
	found 192.168.0.2
	found 192.168.0.3
	found 192.168.0.15
	found 192.168.0.11
	found 192.168.0.16
	found 192.168.0.8
	found 192.168.0.18
	found 192.168.0.5
	found 192.168.0.199
	found 192.168.0.208
	found 192.168.0.239
	found 192.168.0.247
	found 192.168.0.100
	found 192.168.0.9
	found 192.168.0.7
	Agent (v3.0.2.0)
	Log start
	Process is 64 bit
	Init FFmpeg
	ffmpeg path: /usr/lib/x86_64-linux-gnu
	Initializing devices
	Hardware Support:
	vdpau
	cuda
	vaapi
	qsv
	drm
	opencl
	call ffplay -nodisp -f v4l2 -list_formats all /dev/video0
	[video4linux2,v4l2 @ 0x7f6f24000bc0] cannot open video device /dev/video0: no such file or directory
	call arecord -l
	Error: No audio devices found
	Init Webrtc
	Preloading Images
	Turn Server accepting connections at 127.0.1.1:3478 using range 50000-50010)
	Loaded 2 cameras and 2 mics from /home/dotnetuser/iSpy/Media/XML/objects.xml
	Enable: Dolly mic: Start audio
	Enable: Camera 2 mic: Start audio
	Using default port (8090)
	Local Server running on port 8090
	ZeroConf: ZeroConf Service Started
	Running at http://localhost:8090
	MQTT not configured or enabled

Ubuntu Version
	root@blazeagator:~# lsb_release -a
	No LSB modules are available.
	Distributor ID: Ubuntu
	Description:    Ubuntu 20.04.1 LTS
	Release:        20.04
	Codename:       focal

Thanks in advance for any guidance!

Rob

**Comment by ispysoftware** [comment]
No that's just the opencv libraries not needed by agent list
