### ISSUE TITLE
HWTransfer:Input/output error

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [ispysoftware/iSpy#138]
`5: Using hardware decoder: AV_HWDEVICE_TYPE_VAAPI
[AVHWFramesContext @ 0x7fa52c832100] Failed to sync surface 0x13: 1 (operation failed).
Error: MediaStream: MediaStream: Reader: 5: HWTransfer:Input/output error
Error: MediaStream:    at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code)
   at CoreLogic.Sources.Combined.MediaStream.ReadFrames()
Reader: 5: HWTransfer:Input/output error`

I use intel i5 cpu and no graphics card , install Agent in ubuntu system. these is a persistent errors in terminal. how fix it?

**Comment by ispysoftware** [comment]
Set the decoder to auto or CPU instead of gpu on the first tab when you edit the camera

**Comment by smallworld-network-wupeng** [comment]
which graphics card can accelerate Agent in ubuntu ? Nvidia or AMD? There are 20s IP cameras .

**Comment by ispysoftware** [comment]
Any. The problem is that the gpu isn't being forwarded into the container. If you can forward the gpu device in it should work or you can set it up natively instead (use the Linux instructions on the download page) and it will be able to access the hardware
