### ISSUE TITLE
Feature/contribution requests

### ISSUE THREAD

**Issue by kdub454** [ispysoftware/iSpy#139]
Hey Sean,

After giving Agent a test spin this weekend, there were a few things I thought would be useful to add: 
- MQTT connection test
- Web-based log file viewer

I have a decent amount of C# experience and was planning to implement them myself, but understand if you would prefer not to add too many people to the private repo (code-pirates and all).

**Comment by ispysoftware** [comment]
hello, there's a local html version of the logs at
http://localhost:8090/logs.html
doing some work on mqtt at the moment

**Comment by ispysoftware** [comment]
also, not sure if you're aware but Agent supports plugins and there's a demo project to get you started here:
https://www.ispyconnect.com/userguide-agent-plugins.aspx

**Comment by kdub454** [comment]
Nice! I’ll definitely check it out
