### ISSUE TITLE
OPEN_INPUT:Invalid data found when processing input

### ISSUE THREAD

**Issue by elliotbc** [ispysoftware/iSpy#141]
I'm running iSpy agent in a docker container on an Ubuntu box, and I'm having trouble connecting my Ubiquiti Flex cameras. 

I've been able to add the cameras to SecuritySpy, so I believe that the cameras are functioning, and that I have a correct username and password. 

Examining the logs showed some error messages, and I'm not sure what to make of them.

[Log Snippet](https://github.com/ispysoftware/iSpy/files/5833552/files_and_config.txt)

<img width="808" alt="Screen Shot 2021-01-18 at 9 03 07 PM" src="https://user-images.githubusercontent.com/11757760/104986649-b2a29080-59d0-11eb-88e4-ecf0eccf6cca.png">
<img width="807" alt="Screen Shot 2021-01-18 at 9 02 14 PM" src="https://user-images.githubusercontent.com/11757760/104986653-b46c5400-59d0-11eb-9b1d-a8044bf7a4a7.png">

**Comment by ispysoftware** [comment]
what are the error messages?

**Comment by ispysoftware** [comment]
try those url's in VLC - like rtsp://username:password@192.168.1.156/live/ch00_0 and see if they work there. Or if you can get the URL that security spy is using try that in Agent.

**Comment by elliotbc** [comment]
I had the wrong URL. I found that when you log into the camera directly, it will show the RTSP URL.

The correct URL ended up being: `rtsp://192.168.1.156:554/s0`

Where did the `ch00_0` paths come from? Did iSpy suggest that itself? If so, perhaps it could also offer `s0` as an option for the Ubiquiti Flex cameras.

**Comment by ispysoftware** [comment]
ok cool - will add that to the database.
