### ISSUE TITLE
Unable to embed into website

### ISSUE THREAD

**Issue by kb9gxk** [ispysoftware/iSpy#145]
I created an internal website at work to access some of our cameras using the format:
http://10.x.x.x:8080/video.mjpg?OID=y&keepAR=true&overlay=true

This was working until Chromium was updated only to allow HTTPS connections in iframes.

**Comment by ispysoftware** [comment]
you'll need to either:
use a different browser
install an SSL cert on your computer
use a different method of getting frames like FTP or RTMP streaming (Agent)
