### ISSUE TITLE
can not add camera on windows 10 64bit

### ISSUE THREAD

**Issue by bearmen** [ispysoftware/iSpy#146]
hello and sorry about noob question
i'm developing on win7 64 bit with platform target is: x86 (everything is ok)
![image](https://user-images.githubusercontent.com/67936790/109475240-09a78500-7aa8-11eb-827c-5c4c5e027309.png)

but when i build and install on machine with win10 64bit. it always restart when i add camera. i checked and it show "the type initializer for 'ispyApplication.AddCamera' threw an exception" 
when running line (in file MainForm_Configuration.cs)
var ac = new AddCamera { CameraControl = cw, MainClass = this };

do you know why ?

**Comment by ispysoftware** [comment]
I think it needs to be built first. I get the same thing sometimes. Think it's a bug in visual studio. It builds and runs OK.

**Comment by bearmen** [comment]
execuse me but what should I build first?
On the development machine it ran very well, I used ispysetup to create the installation file, but when installing this file on other machines, the error is as above. Does it lack any library?

**Comment by bearmen** [comment]
thank for your reply. i did it :)
