### ISSUE TITLE
After editing the UI, build solution, the resulting UI does not change

### ISSUE THREAD

**Issue by li0128** [ispysoftware/iSpy#147]
![微信图片_20210314212330](https://user-images.githubusercontent.com/16174528/111070219-8f491d00-850b-11eb-869d-7ea980bec931.png)

![微信图片_20210314212203](https://user-images.githubusercontent.com/16174528/111070280-01216680-850c-11eb-81a2-e3b6e683c93e.png)

**Comment by ispysoftware** [comment]
Remove the post build events and see the readme.txt
