### ISSUE TITLE
AgentDVR

### ISSUE THREAD

**Issue by MeisterLone** [ispysoftware/iSpy#149]
Hi there

I would like to write a script to make changes to the detector screen, this is part of a little project of mine. 

1. Is agentdvr open source?
2. how can I modify the detector screen outside of the browser?? 

For example, every few days I want motion detection in a different part of the video feed.

Much appreciated, thank you!

**Comment by ispysoftware** [comment]
1) no it's not - only ispy is at this stage
2) do you mean the area agent is looking for motion? you can update this via the API but it's complicated - best option would be to add the camera multiple times with multiple different detector zone configurations then enable/ disable the cameras using the scheduler.

**Comment by fritz-net** [comment]
@ispysoftware will the agent become open source at one point? or at least the frontend? I'm interested in an option to playback multiple cameras in the timeline at once (and synced)

**Comment by ispysoftware** [comment]
hello you can't at the moment but the easiest way to do this would be to
add the camera multiple times with different configurations and then
enable/ disable the devices on a schedule.
