### ISSUE TITLE
Error on adding Sricam Device in ONVIF

### ISSUE THREAD

**Issue by stephennacion06** [ispysoftware/iSpy#150]
![image](https://user-images.githubusercontent.com/32524849/113725513-f7afa680-9725-11eb-9fa6-e1f1b9c50e6b.png)
I got this error when adding Sricam SP014 in ONVIF

**Comment by stephennacion06** [comment]
But I can view the ip camera using python and opencv

**Comment by ispysoftware** [comment]
Are you sure it's onvif compatible? What url are you using for the onvif discovery address? Have you tried adding it as a regular ip camera using the add camera wizard?

**Comment by stephennacion06** [comment]
Yes I tried. I think it is onvif compatible since it is in the list of sricam to ispy cameras
![image](https://user-images.githubusercontent.com/32524849/114157585-5e1b0b80-9956-11eb-8e7e-3d16dcafc80b.png)

**Comment by stephennacion06** [comment]
I can also access it in VLC media player
![image](https://user-images.githubusercontent.com/32524849/114159720-a9361e00-9958-11eb-87a0-2c340714ab59.png)

**Comment by ispysoftware** [comment]
You should just be able to add it as a regular ip camera then instead of using onvif. Just use the same url. If it doesn't connect then change the decoder on general tab to use vlc.
