### ISSUE TITLE
Schedule Days of Week show "dowmat" instead of "Sat"

### ISSUE THREAD

**Issue by davelillie** [ispysoftware/iSpy#153]
This is not a new problem but it is one which is unresolved years after first being noted. 

I have an x86 installation. The calendar for scheduling cameras show in the  Days of Week "dowmat" instead of "Sat".  The translate.xml is correct in the "DowSat -> Sat" line.

**Comment by ispysoftware** [comment]
Hello this has been fixed in the source code version
