### ISSUE TITLE
error in building release mode vs2019

### ISSUE THREAD

**Issue by masgh021** [ispysoftware/iSpy#154]
when i build in debug mode 
it is ok but after i build in release mode
i got this error 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "xcopy "C:\Users\mas\Desktop\job\ispy1\iSpy-master2\iSpy-master\dlls\x64\*.*" "C:\Users\mas\Desktop\job\ispy1\iSpy-master2\iSpy-master\bin\x64\Release\" /Y
if "Release" == "Release" (
    del C:\Users\mas\Desktop\job\ispy1\iSpy-master2\iSpy-master\bin\x64\Release\*.pdb"
    del "C:\Users\mas\Desktop\job\ispy1\iSpy-master2\iSpy-master\bin\x64\Release\*.vshost.exe"
    call "C:\Users\mas\Desktop\job\ispy1\iSpy-master2\iSpy-master\signing\iSpyx64.bat"
)" exited with code 1.	iSpy			

anyone can help me ???

**Comment by ispysoftware** [comment]
See the readme. You need to remove the post build steps
