### ISSUE TITLE
get current frame for image process

### ISSUE THREAD

**Issue by masgh021** [ispysoftware/iSpy#155]
I am beginner in ispy ,
how get current frame from every camera for 
image processing  ?
which file and function ?

**Comment by ispysoftware** [comment]
Camera.cs newframe event

**Comment by masgh021** [comment]
thanks @ispysoftware  ,
how find newframe is for which camera ???

**Comment by ispysoftware** [comment]
https://github.com/ispysoftware/iSpy/blob/33fcaf4a8b6fe5b59ad07ac6d8f1c1c1b1fb8efc/Controls/CameraWindow.cs#L2967

**Comment by masgh21** [comment]
@ispysoftware 
Hello I cant find camera name or camera Index 
In this function .
https://github.com/ispysoftware/iSpy/blob/33fcaf4a8b6fe5b59ad07ac6d8f1c1c1b1fb8efc/Controls/CameraWindow.cs#L2967

Can you explain more ?

**Comment by ispysoftware** [comment]
property ObjectName and ObjectID

**Comment by masgh21** [comment]
Hello @ispysoftware 
thanks. 
can you help me how process every frame ?
using buffer or another way ??
I am student and I want process every frame but
I don't know how reduce cpu usage .

**Comment by ispysoftware** [comment]
you'll want to use unsafe and access the memory directly
https://csharpexamples.com/tag/unsafe-bitmap-access/

**Comment by masgh21** [comment]
thanks
@ispysoftware 
i test it but  I have a new problem
can you help me ?
I clone e.frame like this. is this way ok ???
**   
Bitmap processedBitmap2 =  (Bitmap)e.Frame.Clone() ;
>>> my process 
processedBitmap2.dispose();
**
after my process , I dispose  processedBitmap2 .
But my ram usage take up to the 1 Gigabyte ,  after 2 minutes with 3 cameras .

**Comment by ispysoftware** [comment]
you're going to be better off asking programming questions on stackoverflow

**Comment by masgh21** [comment]
thanks .
I have 2 simple question . 
1- how change tray icon ?
2- how add language in menu ,  (language package) .
