### ISSUE TITLE
Can not open "CaneraWindow.cs" for edit in VS2019

### ISSUE THREAD

**Issue by liumarcus70s** [ispysoftware/iSpy#157]
As is:
![image](https://user-images.githubusercontent.com/8784986/125393050-d07a0c80-e3d9-11eb-9e30-4db0591417d6.png)
The same problem is "MainForm.cs"
![image](https://user-images.githubusercontent.com/8784986/125393154-fc958d80-e3d9-11eb-848c-aa5cf926a3da.png)
but there is an "Ignore" button.
So, somebody helps me.

**Comment by liumarcus70s** [comment]
After clean and rebuild the project, I had settled down the problem.

**Comment by Miracle-doctor** [comment]
I have also this problem. I can not enter MainForm in Construction mode. After rebuild and compile same problem.
