### ISSUE TITLE
[Update] Apple Silicon support

### ISSUE THREAD

**Issue by mkikets99** [ispysoftware/iSpy#159]
Apple recently changed processor architecture from x86/64 to ARM with their M1 chip...

After this update not only dotnet solution didn't work...
even docker container is not compatible....

Is there any thoughts on updating to Silicon?

**Comment by ispysoftware** [comment]
Ive got one. Seems to work fibe on it. M1 has x64 emulation. What errors do you get?

**Comment by ispysoftware** [comment]
... Should work with the Mac version on the download page.
