### ISSUE TITLE
thread leak

### ISSUE THREAD

**Issue by tigros** [ispysoftware/iSpy#164]
When using the video viewer then closing the window there's a thread leak, other resources too. The thread count was increasing by about 25, so if you view alot of videos it gets in the 100's.

Anyway i found a fix, in PlayerVLC.cs

        private void Player_FormClosing(object sender, FormClosingEventArgs e)
        {
            videoView1.MediaPlayer.Media.Dispose();
            videoView1.MediaPlayer.Media = null;
            videoView1.MediaPlayer.Dispose();
            videoView1.MediaPlayer = null;
            videoView1.Dispose();
            videoView1 = null;
        }

in Mainform.cs i put a  _player.Dispose() in PlayerClosed(...) for good measure.

**Comment by ispysoftware** [comment]
Hello thanks for this - there is/was a bug in VLC where calling dispose on the mediaplayer either caused a thread lock or an accessviolationexception. Could you let me know if you see that happening?

**Comment by tigros** [comment]
nope, haven't seen any issues. Actually i did see something like that if you remove the 1st 2 Dispose() i remember adding them made my day :)
