### ISSUE TITLE
FFmpeg issue

### ISSUE THREAD

**Issue by djdoubleg** [ispysoftware/iSpy#166]
Can not install ffmpeg.
Folowing issue i have:
Error: Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56
ZeroConf: ZeroConf Service Started
Error:    at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56

Manual install:
root@nas:~/AgentDVR/ffmpeg-build# curl -s -L "https://raw.githubusercontent.com/ispysoftware/agent-install-scripts/main/ffmpeg_build.sh" | bash -s -- --build --enable-gpl-and-non-free
ffmpeg-build-script v1.33
=========================

Using 8 make jobs simultaneously.
With GPL and non-free codecs
cargo not installed. rav1e encoder will not be available.

building giflib - version 5.2.1
=======================
Downloading https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz as giflib-5.2.1.tar.gz

Failed to download https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz. Exitcode 60. Retrying in 10 seconds

Failed to download https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz. Exitcode 60

**Comment by ispysoftware** [comment]
hello looks like that download is working now - must have been some outage at sourceforge

**Comment by djdoubleg** [comment]
I try it again:
![kép](https://user-images.githubusercontent.com/83548720/146878114-a88f9d1c-4654-4e3e-aef1-cf4da845dec8.png)
But not works.

**Comment by ispysoftware** [comment]
can you log an issue on the right github page?
https://github.com/ispysoftware/agent-install-scripts/issues/new?assignees=&labels=&template=report-a-bug-with-the-install-script.md&title=
