### ISSUE TITLE
playback section

### ISSUE THREAD

**Issue by masgh21** [ispysoftware/iSpy#167]
Hello 
does ispy have playback section like dvr devices ? 
search playbacks with date for every camera .

**Comment by ispysoftware** [comment]
@masgh21 yes

**Comment by masgh21** [comment]
@ispysoftware 
which menu ?
where is it ???

1- I have two question
Is there a role management for user ?
for give access to use menu  .

2-  can _pnlCameras configure to show camera as grid ???
for example 4X4 ?

**Comment by ispysoftware** [comment]
1) yes see media panel in ui. See settings / permissions
2) see grid views via view menu

**Comment by masgh21** [comment]
@ispysoftware 
Hello 
where is  playback section?
can you help me ?
I can't find it .
