### ISSUE TITLE
Sricam SP012: OPEN_INPUT:Invalid data found when processing input

### ISSUE THREAD

**Issue by askrinnik** [ispysoftware/iSpy#172]
Dear developer,

I have 3 IP cameras in my network. Two of them (Reolink) work fine with iSpy and AgentDVR applications.

But I faced an issue with connecting my third IP camera **Sricam SP012**
My camera is located on IP address: 192.168.0.90
VLC player plays properly with addresses:
rtsp://192.168.0.90:554/onvif1
rtsp://192.168.0.90:554/onvif2
Onvif Device manager Tool detects the camera correctly.

Then I tried to add the camera to iSpy and AgentDVR applications.
The camera was found on http://192.168.0.90:5000
It returns the following connections:
```
ONVIF     http://192.168.0.90:5000/onvif/device_service
IP Camera	rtsp://192.168.0.90:554/onvif1	
IP Camera	rtsp://192.168.0.90:554/rtsp_live1	
IP Camera	rtsp://192.168.0.90:554/onvif2	
IP Camera	rtsp://192.168.0.90:554/11	
IP Camera	rtsp://192.168.0.90:554/live/mpeg4	
MJPEG	    rtsp://192.168.0.90:554/profile0	
IP Camera	rtsp://192.168.0.90:554/ucast/11
IP Camera	rtsp://192.168.0.90:554/ucast/12
MJPEG	    rtsp://192.168.0.90:554/1/h264major
IP Camera	rtsp://192.168.0.90:554/1
IP Camera	rtsp://192.168.0.90:554/mpeg4/media.amp?resolution=640x480
IP Camera	rtsp://192.168.0.90:554/cam1/mpeg4?user=****&pwd=***
IP Camera	rtsp://192.168.0.90:554/cam1/mpeg4
```

When I tried to use any of the links above in Agent DVR I got an error:
```
14:37:31	[rtsp @ 000002b674789180] Nonmatching transport in server reply
14:37:31	DoStart: DoStart: Reader: Camera 3: OPEN_INPUT:Invalid data found when processing input
14:37:31	Error: DoStart: DoStart: Reader: Camera 3: OPEN_INPUT:Invalid data found when processing input
14:37:31	DoStart: в CoreLogic.Sources.Combined.MediaStream.DoStart()
14:37:31	Error: DoStart: в CoreLogic.Sources.Combined.MediaStream.DoStart()
14:37:31	Reader: Camera 3: OPEN_INPUT:Invalid data found when processing input
14:37:31	SourceError: Camera 3: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 3: OPEN_INPUT:Invalid data found when processing input
14:37:31	Error: SourceError: Camera 3: CoreLogic.Sources.Combined.MediaStream:Reader: Camera 3: OPEN_INPUT:Invalid data found when processing input
14:37:31	SourcePlayingFinished: Camera 3: Playing finished (SourceError)
```
When I put the link http://192.168.0.90:5000/onvif/device_service to iSpy I got an error: no media endpoints found.
![image](https://user-images.githubusercontent.com/1359187/153757510-4220fa6f-4a81-4dce-ba3d-8dc776c92123.png)

I found an overview of the camera here: https://mysku.ru/blog/china-stores/41168.html (russian)
It was said that the author managed to connect to the camera as an ONVIF device:
Here is a screenshot from the article:
![image](https://user-images.githubusercontent.com/1359187/153757578-082092a4-47df-4340-a238-baa9e62a52be.png)

But I see that UI is a little bit different in comparing with the current version

So, I played with this stuff in many ways: as ONVIF and the manufactured IP Camera, but no luck.

Could you help me to understand the root cause of the issue?

Thank you in advance.

**Comment by ispysoftware** [comment]
hello, hard to tell without access to the camera - are you able to port forward the onvif discovery port and message me the details so i can try connecting from here?

**Comment by askrinnik** [comment]
Thank you for the quick response. 

Yes, I did that. 
My IP: 109.86.246.38
I forwarded: 
5000 -> 5000
554 -> 554

**Comment by askrinnik** [comment]
Actually, there is an RTSP link that can be put to the VLC player.
rtsp://109.86.246.38:554/onvif1
It works now

**Comment by ispysoftware** [comment]
hello you might want to email me those details instead of putting them publicly online - could you send me the login as well?
sean at ispyconnect dot com.

**Comment by askrinnik** [comment]
I've sent you an email with details
Thanks again :)

**Comment by ispysoftware** [comment]
issue was using tcp instead of udp, added code to auto switch
