### ISSUE TITLE
Tokens: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by noctarius** [ispysoftware/iSpy#173]
After updating to the latest version my cameras only connect sporadically. I first tried to update on top of the previous installation and thought something went wrong. Therefore, I renamed the old directory and ran a new installation, reimporting the three configuration files from the previous installation. Same issue happens for all 5 cameras (Reolink 1x 510WA, 4x 822A). All of them are connected through the Reolink NVR (since I'm still testing iSpy).

From the error log I'd expect it to fail to run the login 

OS: Linux (Debian 10.11)
uname: Linux ispy 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
Virtualized on top of TrueNAS (VM with bhyve)
Agent Version: v3.7.9.0
Camera configuration: IP Camera, `rtmp://172.16.25.1:1935/bcs/channel3_sub.bcs?token=[TOKEN]&channel=0&stream=1` 

Error log:
````
7:24:09 PM | Reconnect: Office: Reconnecting in 30s
-- | --
7:24:22 PM | intervals: Balcony: Reconnecting
7:24:22 PM | intervals: Balcony: Reconnect Exit
7:24:22 PM | Tokens: Tokens: Cannot perform runtime binding on a null reference
7:24:22 PM | Error: Tokens: Tokens: Cannot perform runtime binding on a null reference
7:24:22 PM | Tokens: at CallSite.Target(Closure , CallSite , Object ) at CoreLogic.Sources.Combined.Tokeniser.GetLoginToken()
7:24:22 PM | Error: Tokens: at CallSite.Target(Closure , CallSite , Object ) at CoreLogic.Sources.Combined.Tokeniser.GetLoginToken()
7:24:22 PM | Cannot perform runtime binding on a null reference
7:24:22 PM | DoStart: DoStart: Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | Error: DoStart: DoStart: Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
7:24:22 PM | Error: DoStart: at CoreLogic.Sources.Combined.MediaStream.DoStart()
7:24:22 PM | Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | SourceError: Balcony: CoreLogic.Sources.Combined.MediaStream:Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | Error: SourceError: Balcony: CoreLogic.Sources.Combined.MediaStream:Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | SourceError: Camera 2 mic: CoreLogic.Sources.Combined.MediaStream:Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | Error: SourceError: Camera 2 mic: CoreLogic.Sources.Combined.MediaStream:Reader: Balcony: OPEN_INPUT:Input/output error
7:24:22 PM | SourcePlayingFinished: Balcony: Playing finished (SourceError)
7:24:22 PM | Reconnect: Balcony: Reconnecting in 30s
````

**Comment by ispysoftware** [comment]
which version were you using before?

**Comment by noctarius** [comment]
Thanks for the quick reply. The previous version was whatever was installed just a few days ago. It worked great.

After removing and reading username / password a few times I can get all of them to connect again, but restarting the service brings the issue back and the remove(add game starts all over.

From the error message I thought maybe there was maybe a deserialization issue when reading the confirmation, but I seem to be the only one to have that issue. Maybe I try setting up all cameras all over.

**Comment by ispysoftware** [comment]
it's replacing a [TOKEN] element in the videosource url with a token it's trying to get from the camera.
The JSON that it's getting back from the camera isn't containing a token - this error is basically saying that.
If you can forward the port i can tell you what the camera is responding with  - or wait for the next update because i've added that to logging.

**Comment by noctarius** [comment]
Let's wait for the next release :) Thanks for looking into it!

**Comment by noctarius** [comment]
Alright I think I know what the actual issue is. Reolink devices have a pretty low number of possible concurrent connections. Using the reolink nvr in between probably makes it even worse. Seems like there is a specific logout URL to kill unused tokens (like when the connecting service restarts). Do you think there's a chance to get support for stuff like that into the code? Happy to help out with the code :-)

Here's the error message from the log:
```
Error: Couldn't get Token (response: [
   {
      "cmd" : "Login",
      "code" : 1,
      "error" : {
         "detail" : "max session",
         "rspCode" : -5
      }
   }
])
```

**Comment by noctarius** [comment]
PS: Here's where I found the logout url: https://gist.github.com/bdlow/5553b43037e2fcaacfa8b82a2e78e639

**Comment by ispysoftware** [comment]
i'll update it so it will logout the last used token before trying to login.

**Comment by noctarius** [comment]
Awesome! Thanks a lot!

**Comment by ispysoftware** [comment]
should be fixed
