### ISSUE TITLE
Crash on Chrome

### ISSUE THREAD

**Issue by blackPantherOS** [ispysoftware/iSpy#175]
Unusable with Google Chrome 98.0.4758.102 

![Screenshot_20220301_231409](https://user-images.githubusercontent.com/12883566/156258179-ea0b1ba1-a032-48a1-8d3a-53abe28ffd85.png)

**Comment by ispysoftware** [comment]
.. not much i can do about it, it's a bug in chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=1240237
