### ISSUE TITLE
How to Agent DVR API PTZ Preset Onvif?

### ISSUE THREAD

**Issue by jurijzahn8019** [ispysoftware/iSpy#176]
Hi there!

I was trying to go to a PTZ Preset for a cam via ptz.cgi.
The PTZ is configured via ONVIF, and i was not able to do it.

Is there a way to call a PTZ Preset for an ONVIF Cam via api?

Thanks :smile:

**Comment by ispysoftware** [comment]
hello you'll need to pass in the token for the ptz preset like:

ptz.cgi?oid=1&cmd=<token>

the token is usually the name of the preset but if not you can find it by adding a ptz schedule to the camera and looking in the camera ptzschedule entries in the objects.xml file from server menu - backup/ restore/ download devices
