### ISSUE TITLE
iSpy crashes when recording buffer is set to 120s

### ISSUE THREAD

**Issue by robhubi** [ispysoftware/iSpy#178]
### My System
Win 7 Home Premium 64 bit; CPU i3 @ 3.4GHz, 4GB RAM, 256GB SSD 
iSpy v 7.2.1.0; .net v 4.5.2

### Description
A microphone records the starting noise of an engine and triggers the recording of 2 video cameras. The recording starts 5s before the trigger (buffer=5s). This works.

For a longer pre-recording I set buffer=120s. This did not work. The preview window periodically goes dark and after a while iSpy crashed. Message: "iSpy has stopped working ..."

### Steps to Reproduce

Setting on 20 February 2022 between 11:24 and 14:14

```
USB-Micro1
	Alerts enabled
		Actions On Alert:
			Trigger Alert On Cam1
			Trigger Alert On Cam3
		Intervalls 600s
	Recording -

USB-Cam1 and USB-Cam3
	Alerts –
	Recording
		Record On Alert
			Buffer = 120s
			Inactivity Record = 120s
			Min Record Time = 0s
			Max Record Time = 126s
```
### Actual Result
After a while iSpy crashes with: "iSpy has stopped working ..."

### Expected Result
Video recording without error message 

### Attachment
OK-Setting; Is01_rec_Mano_Tube.ispy
Error Log: Is01_log_20022022.zip
[Is01_log_20022022.zip](https://github.com/ispysoftware/iSpy/files/8292466/Is01_log_20022022.zip)
[Is01_rec_Mano_Tube.zip](https://github.com/ispysoftware/iSpy/files/8292515/Is01_rec_Mano_Tube.zip)

**Comment by ispysoftware** [comment]
Have you checked it's not running out of memory?

**Comment by robhubi** [comment]
The usage of the physical memory remains below 70 %. See screenshot at time of crash.
![Is01_ScSh01](https://user-images.githubusercontent.com/38103976/159025898-5042e208-b0de-48db-8cf9-da815d23e741.jpg)

**Comment by ispysoftware** [comment]
That's 32 bit iSpy
https://en.wikipedia.org/wiki/2_GB_limit

**Comment by robhubi** [comment]
Thanks for the clarification.
