### ISSUE TITLE
Cant record with Audio

### ISSUE THREAD

**Issue by Urodela** [ispysoftware/iSpy#18]
Hello and sorry for my English!

I have a Problem since 6.6.3.0 (tried everything till 6.7.5.0) with AVI recordings. I cant record with Audio that coming from the Microphone. Without Audio everything is working fine. Heres the Error that appears in the Log file:

----

Error  08:17:37  Door: unable to write audio frame. ( bei iSpyApplication.Realtime.MediaWriter.AddAudioSamples(Byte[] soundBuffer, Int32 soundBufferSize, Int64 msOffset) bei iSpyApplication.Realtime.MediaWriter.WriteAudio(Byte[] soundBuffer, Int32 soundBufferSize, Int32 level, Int64 msOffset) bei iSpyApplication.Controls.CameraWindow.WriteFrame(FrameAction fa, DateTime recordingStart, Int64& lastvideopts, Double& maxAlarm, Nullable`1& peakFrame, Int64& lastaudiopts) bei iSpyApplication.Controls.CameraWindow.Record())

Error  08:17:38  Door Micro: paired recording aborted as the camera is already recording

----

Im using 2 USB Cams and one Microphone (connected with soundcard) which is cloned to use it for both Cams. But i also tried to do a clean setup with just one Cam and the Microphone, the results are the same. No File is created. But MP4 (h264) is recording with sound, it just happens with AVI. Any Ideas? Thanks for reading.

**Comment by ispysoftware** [comment]
Hello, thanks for that, have fixed it and will be in next update.

Sean

**Comment by Urodela** [comment]
Thanks for answering! :) I will try it out and let you know if it works! Thanks!

**Comment by Urodela** [comment]
Alright, the new Version (6.7.6.0) is working fine! Thanks alot for fixing this issue! :) Have a nice Day!

**Comment by Urodela** [comment]
Still working, so can be closed!
