### ISSUE TITLE
Onvif presets use preset name as token. 

### ISSUE THREAD

**Issue by elyakimw** [ispysoftware/iSpy#180]
i use some encoder that predefine some presets (pelcod like...)  for misc operations. 
he define the name and token separately, so when iSpy  send GoToPreset he didn't understand what the name means, it expect a token!

**Comment by elyakimw** [comment]
the problem is across presets use, PTZTool &  AddCamera and also by Tours at  PTZScheduler & CameraWindow
our encoder work properly with ISpay Agent, that why i assume it  is a bug

**Comment by ispysoftware** [comment]
sorry you mean it works OK in Agent and not in iSpy?

**Comment by elyakimw** [comment]
> 

i don't know, i need it for disconnected use, so agent wasn't an option for me.

**Comment by elyakimw** [comment]
today i notice that i forgotten to use the token on repeat option of Scheduler.
can you reopen this issue, or i need to open an other one?

**Comment by ispysoftware** [comment]
" i need it for disconnected use, so agent wasn't an option for me."
Agent runs fine disconnected
