### ISSUE TITLE
Error  load    MainFram.cs [Design]     

### ISSUE THREAD

**Issue by masgh21** [ispysoftware/iSpy#188]
i want to open MainFram.cs [Design]  today But i got this Error Page ,
Everything was good yesterday .
App run correctly But i can't Open this File .

![image](https://user-images.githubusercontent.com/90691672/166565678-77017e94-a723-4d0c-84de-17d26ee9cd65.png)

**Comment by ispysoftware** [comment]
you need to build it so visual studio can open it, try x86
