### ISSUE TITLE
Support PTZ commands with absolute PTZURL

### ISSUE THREAD

**Issue by mythgarr** [ispysoftware/iSpy#19]
Not sure if this is the right place to submit feature requests. I'm planning to put together a pull request for this feature later but it was also requested at http://community.ispyconnect.com/ispybb2/viewtopic.php?t=5538

If an RTSP url is used for the video source (eg: with the Amcrest IP2M-841, something like rtsp://user:password@mycamera/cam/realmonitor?channel=1&subtype=0) PTZ functionality will be disabled. PTZ settings support specifying a different URL (in the above example http://mycamera/cgi-bin/) but in this configuration command information is ignored (see PTZController.cs line 1365).

A possible workaround is to define a different "camera" for each attached device in PTZ2.xml (each using absolute URLs) but this leads to maintenance issues.

**Comment by ispysoftware** [comment]
in ispy if you click the "..." button next to the camera model dropdown on the PTZ tab when editing the camera you can change the PTZ URL to be an absolute URL there (add http://... to the beginning on the URL)

**Comment by mythgarr** [comment]
This issue has NOT been resolved - see the initial request:

> PTZ settings support specifying a different URL (in the above example http://mycamera/cgi-bin/) but in this configuration command information is ignored (see PTZController.cs line 1365).

In other words, if an absolute URL is used iSpy will no longer add the command information.

**Comment by ispysoftware** [comment]
oh i see what you mean - will get it fixed.

**Comment by ispysoftware** [comment]
i've checked in some updates please let me know if this resolves the issue.

**Comment by mythgarr** [comment]
I meant to leave a comment - it looks like the changes might be included in version 6.8.4.0. Is there somewhere I can see which revision of the code was used to build each installer?

**Comment by ispysoftware** [comment]
yeah there's a bug in wix where it's not updating one file - working on that - you'll need to build from source to see the changes. I'll upload a new version today.

**Comment by mythgarr** [comment]
The latest version seems to correctly build a URL for PTZ control. I'm running into an unrelated issue due to our configuration - our cameras apparently no longer support basic authentication for PTZ. This was fixed back in version August 2015 with version 1.3.6.0 ("Added digest authentication support to PTZ") but I can't find the option to enable it.

**Comment by ispysoftware** [comment]
If you want to port forward the camera and send me a login i can take a look. It should try digest automagically if basic fails

**Comment by mythgarr** [comment]
I was able to get it working with a few small bug fixes. Submitted a pull request with the fixes.
https://github.com/ispysoftware/iSpy/pull/28
