### ISSUE TITLE
need help in zoom of Digital camera 

### ISSUE THREAD

**Issue by slmanali** [ispysoftware/iSpy#195]
I use my laptop camera and I want to know the exact area of the image depending on the zoom value, I try to modify the STEPPED_ZOOM value in file "PTZ2.XML"  but there is no changes in the speed of the zoom
they were 
      <ZoomIn>/cgi-bin/encoder?USER=[USERNAME]&amp;PWD=[PASSWORD]&amp;STEPPED_ZOOM=TELE,200</ZoomIn>
      <ZoomOut>/cgi-bin/encoder?USER=[USERNAME]&amp;PWD=[PASSWORD]&amp;STEPPED_ZOOM=WIDE,200</ZoomOut>
i put them
      <ZoomIn>/cgi-bin/encoder?USER=[USERNAME]&amp;PWD=[PASSWORD]&amp;STEPPED_ZOOM=TELE,1</ZoomIn>
      <ZoomOut>/cgi-bin/encoder?USER=[USERNAME]&amp;PWD=[PASSWORD]&amp;STEPPED_ZOOM=WIDE,1</ZoomOut>

**Comment by ispysoftware** [comment]
you would need to restart the application to load it back in again

**Comment by slmanali** [comment]
thanks, it works fine.
can I know the new dimension with the new zoom?

**Comment by ispysoftware** [comment]
sorry i don't really know what you mean - that parameter is just passed through to the camera, it's up to the camera to move - I have no idea how far it moves - there's no feedback to the code that calls it.

**Comment by slmanali** [comment]
sorry, I didn't express it very well.
but I figure it out.
thanks for your help.
