### ISSUE TITLE
Use LAN IP when available

### ISSUE THREAD

**Issue by nyukers** [ispysoftware/iSpy#199]
I don`t view checkbox "Use LAN IP when available" on my account page iSpyConnect.
Where is it now?

**Comment by ispysoftware** [comment]
Click on the Server name on /monitor/app/summary

![image](https://user-images.githubusercontent.com/800093/170904091-3742c90a-0b74-4464-8631-99598e9b893f.png)

**Comment by nyukers** [comment]
Yes, you are right. Thanks. But it's not free feature.)
