### ISSUE TITLE
Very high cpu usage all of a sudden

### ISSUE THREAD

**Issue by dustin-auby** [ispysoftware/iSpy#202]
Hi all,
I have been running Agent DVR for a while now and today my CPU usage spiked from 13% to 60% and is staying like that. i am running 5 1080p cameras on a server that  has a Ryzen 5 with 22gb ram and a R9280x GPU. all the cameras are limited to 10 fps and detection is disabled on all of them. they are all recording constantly. any ideas what could cause this spike. 
Agent DVR version:  v3.9.0.0
Operating System: Ubuntu server.
Anny assistance would be greatly appreciated

**Comment by ispysoftware** [comment]
you'll need to restart it and check the logs at /logs.html
probably a gpu driver update/ issue
also please post either here **or** on reddit.

**Comment by dustin-auby** [comment]
Apologies only found the git repo after i posted on redit. i have checked the logs after a reset and dont see any driver errors from what i can see. these errors do occur though.

`<html><body>


10:01:05 | Discovery: Lounge: Using Media Version 2
-- | --
10:01:05 | Value cannot be null. (Parameter 'source')
10:01:05 | Error: Value cannot be null. (Parameter 'source')
10:01:05 | at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at CoreLogic.Onvif.ONVIFDevice.ProcessMedia2Client(EndpointAddress ep, CancellationTokenSource cts)    at CoreLogic.Onvif.ONVIFDevice.Connect()
10:01:05 | Error:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at CoreLogic.Onvif.ONVIFDevice.ProcessMedia2Client(EndpointAddress ep, CancellationTokenSource cts)    at CoreLogic.Onvif.ONVIFDevice.Connect()
10:01:05 | Value cannot be null. (Parameter 'source')
10:01:05 | ONVIF Discovery: Lounge: Trying Media v1
10:01:06 | Value cannot be null. (Parameter 'source')
10:01:06 | Error: Value cannot be null. (Parameter 'source')
10:01:06 | at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at CoreLogic.Onvif.ONVIFDevice.ProcessMedia2Client(EndpointAddress ep, CancellationTokenSource cts)    at CoreLogic.Onvif.ONVIFDevice.Connect()
10:01:06 | Error:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at CoreLogic.Onvif.ONVIFDevice.ProcessMedia2Client(EndpointAddress ep, CancellationTokenSource cts)    at CoreLogic.Onvif.ONVIFDevice.Connect()


</body>
</html>`

the other error i do see is this one

`ffmpegbase: Lounge: Couldn't create AV_HWDEVICE_TYPE_CUDA decoder. Using CPU instead.`

**Comment by ispysoftware** [comment]
probably a gpu driver update or issue - if it cant access the gpu it falls
back to the cpu
