### ISSUE TITLE
Cannot get latest Docker Version

### ISSUE THREAD

**Issue by al-geeker** [ispysoftware/iSpy#203]
I used doitandbedone/ispyagentdvr:latest to get the latest version of Agent DVR.

But when I check the version, I see 4.0.0.0

Is the Docker image up to date?

**Comment by al-geeker** [comment]
I think this might be the issue. The latest tag was last updated 21 days ago.

![image](https://user-images.githubusercontent.com/32320831/174664055-b9e6ca55-26be-476a-916b-843ab41facff.png)

**Comment by ispysoftware** [comment]
you'll need to log an issue on the docker github
https://github.com/doitandbedone/ispyagentdvr-docker
