### ISSUE TITLE
TP-Link Tapo C200 PTZ

### ISSUE THREAD

**Issue by juanpc2018** [ispysoftware/iSpy#205]
https://community.home-assistant.io/t/use-pan-tilt-function-for-tp-link-tapo-c200-from-home-assistant/170143/18

https://community.tp-link.com/en/smart-home/forum/topic/194486?replyId=1106858

https://community.tp-link.com/en/home/forum/topic/194486?page=3

https://community.tp-link.com/en/home/forum/topic/194486?page=4

----

PTZ works with ONVIF.

The problem with the Tapo Android App, is that does Not have Dark Mode...
when you are in your bed, and want to see in total darkness, 
even with the cellphone screen totally dim,
its too bright and hurts the eyes.
The app is totally useless, unless you buy a ND filter 0.6 for the cellphone screen.

https://www.tp-link.com/us/home-networking/cloud-camera/tapo-c200/

https://play.google.com/store/apps/details?id=com.alexvas.dvr&hl=en&gl=US

**Comment by ispysoftware** [comment]
sorry what was the issue?

**Comment by juanpc2018** [comment]
sorry, i was Not clear...

There is No issue when camera is set-up properly,
problem is setting the camera properly,
too many options, 
presets dont shine enough light on the right direction..
i need to read all internet to find the answer. 

my 2 cents,
c200 cameras are very popular here...
