### ISSUE TITLE
Is it possible to port or compile on a FreedBSD OS?

### ISSUE THREAD

**Issue by rajhlinux** [ispysoftware/iSpy#206]
Hello, was wondering if I can compile or port iSPY to FreeBSD 13 OS.

Is it possible?

Thanks.

**Comment by ispysoftware** [comment]
Sure as long as it runs the .net core 3.1 framework - you'd just need to modify the setup scripts in the install repo to get the dependencies
https://github.com/ispysoftware/agent-install-scripts
