### ISSUE TITLE
Cannot compile on Linux nor run with dotnet > 3.1

### ISSUE THREAD

**Issue by Xinayder** [ispysoftware/iSpy#208]
I've tried to install Agent DVR on a fresh Ubuntu 22.04 install and I cannot succeed.

The install script for some reason installs `dotnet 3.1.300` and requires `dotnet-hostfxr` to run. If I try to install those packages from the Microsoft repos, I cannot install because they require `libssl1.1` which was updated by Ubuntu to a more recent version. And if I try to run the Agent with the latest LTS version of dotnet, it says it cannot run because the required version is `3.1.0`.

I also tried to compile the project on my Linux server and it's impossible to do so, mainly because of all the .NET Framework dependencies and the NuGet packages not using the new `dotnet` structure where package references are defined in the project/solution file and not the `packages.config` file.

**Comment by ispysoftware** [comment]
https://www.reddit.com/r/ispyconnect/comments/ucbcsq/starting_agentdvr_on_ubuntu_2204_jammy_fails_due/

**Comment by Xinayder** [comment]
Although this workaround exists, it's far from ideal and not recommended. Using an outdated `libssl` in Ubuntu 22.04 might break the system as `libssl3` isn't totally compatible with version 1.1. Another workaround could be to downgrade the system to Ubuntu 20.04, but that's also not that ideal to go through all the trouble of running an outdated system version just to run a single software.

Is there a reason why Agent DVR is compiled with .NET Framework, are there hardcoded Windows dependencies? How is the Linux package compiled? It would be a huge help if there were steps to compile the software on Linux so I could explore and try to get it working with .NET Core 6.

**Comment by ispysoftware** [comment]
i'm working on a .net core 6 update at the moment
