### ISSUE TITLE
Not able to find ffmpeg

### ISSUE THREAD

**Issue by sebbi08** [ispysoftware/iSpy#209]
Hi trying to set up agentDVR on my PI.

Somehow I need to build FFmpeg from sources to get the latest version but still it gives me the error that it could not found it

![image](https://user-images.githubusercontent.com/9070136/182365985-7be0fa73-8113-4ee5-8d13-dff9a4b13f1d.png)

**Comment by ispysoftware** [comment]
did you run the install script?
I'm going to update it later on in the week to use ffmpeg v5

**Comment by sebbi08** [comment]
I run the scrip by that time I had V3 installed and afterwards installed the new ffmpeg version. Do I need to rerun the installation ?

**Comment by ispysoftware** [comment]
the install script will install a compatible version - version 3 isn't compatible with Agent DVR. It needs version 4.

**Comment by sebbi08** [comment]
AH ok so i had v3 and then installed v5 so I skipped the compatible version :D
