### ISSUE TITLE
Upgrade to 6.8.1.0 from 6.6.7.0 results in crash System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by CollinChaffin** [ispysoftware/iSpy#21]
Just upgraded my working x64 v6.6.7 on WIN7x64 and upon relaunch cannot run ispy and get a crash with this error indicating some file is not being found:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	iSpy.exe
  Problem Signature 02:	6.8.1.0
  Problem Signature 03:	595a0a6e
  Problem Signature 04:	iSpy
  Problem Signature 05:	6.8.1.0
  Problem Signature 06:	595a0a6e
  Problem Signature 07:	102e
  Problem Signature 08:	2a4
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	fc55
  Additional Information 2:	fc55eb82e8d541916b6fa8e0fc757d3a
  Additional Information 3:	acd8
  Additional Information 4:	acd89f8868feb271d2e1db93bb483850

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Any idea what file it is looking for how I can determine what's going on?

**Comment by CollinChaffin** [comment]
I was able to attach with Studio 2017 to debug and determine it is looking for this (NAudio.Lame, Version=1.0.3.3048)

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'NAudio.Lame, Version=1.0.3.3048, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=iSpy
  StackTrace:
   at iSpyApplication.Controls.VolumeLevel.AudioDeviceDataAvailable(Object sender, DataAvailableEventArgs e)
   at iSpyApplication.Sources.Video.MediaStream.ReadFrames()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

So why did this happen on a successful upgrade and how do I fix it?

**Comment by CollinChaffin** [comment]
I did a full uninstall, manually then deleted all ispy files from program files and all appdata, only then was I able to reinstall fresh without this error.  Again, this was a working prior version that I had actually just been running and shut down to upgrade, so I'm not sure if it's just maybe a bug in the installer process only in an upgrade does that one assembly not get upgraded correctly, etc. but just be aware this happened.

**Comment by ispysoftware** [comment]
thanks yes i've had a few reports - not sure what is preventing it from
copying, will look into it
