### ISSUE TITLE
*Agent DVR* Erase option missing/not available when drawing detection area

### ISSUE THREAD

**Issue by Tornadoalley** [ispysoftware/iSpy#211]
There appears to be no erase or undo button for drawing paths via the Detection Area. I find this very frustrating since even a small mistake like drawing the box wrong will force me to reset the entire path just to make a correction. It is not a browser issue as I used Firefox, Edge, and Chrome and got the same results. No extensions are modifying the page such as U Block Origin (all disabled). See attachment.
![image](https://user-images.githubusercontent.com/73433060/183969314-59e62883-ea30-4f3d-80a3-543ba4160f3a.png)

**Comment by ispysoftware** [comment]
use right mouse button
