### ISSUE TITLE
Manually Added Plugins not showing up in Agent DVR 

### ISSUE THREAD

**Issue by Tornadoalley** [ispysoftware/iSpy#212]
Likely my user error but when I created a folder via the Agent directory within program files, I named it "Plugins" as the instructions specified. However, upon restarting agent, the plugins still do not appear.
![image](https://user-images.githubusercontent.com/73433060/183970348-e7c5f545-62af-4290-947f-2445f6701d0e.png)
![image](https://user-images.githubusercontent.com/73433060/183970376-16a11534-2bef-499d-a188-5dec7e6ddc44.png)
![image](https://user-images.githubusercontent.com/73433060/183970421-ef53c306-f6b3-4f0a-bff4-09dc39a081fd.png)

**Comment by ispysoftware** [comment]
duplicate
