### ISSUE TITLE
AgentDVR File naming errors

### ISSUE THREAD

**Issue by Sponsoredby** [ispysoftware/iSpy#213]
I am using the AgentDVR on a pi, on the photos page I am using 

<img width="644" alt="2022-08-16 23_55_14-Agent_ Agent DVR - Brave" src="https://user-images.githubusercontent.com/74147554/184999053-920cb667-78df-4a3a-9a04-d211c2103e81.png">

However, the filenames are been written as follows

<img width="175" alt="2022-08-16 23_57_43-_G__tapo_video_KNKWH_grabs__ 08-16 - Everything" src="https://user-images.githubusercontent.com/74147554/184999305-e4b1f74b-239f-44c6-8d04-c332b0293cf4.png">

cant quite figure out what is going on here

**Comment by ispysoftware** [comment]
it's thinking t is the first character of AM or PM, use
{0:yyy=MM-dd_HH-mm-ss_fff}_tapo.jpg
