### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by charleskhenry** [ispysoftware/iSpy#214]
Are there any known memory leaks in iSpy?

**Comment by ispysoftware** [comment]
nope

**Comment by hucker75** [comment]
I just had mine go up to 76GB on my 96GB computer, which then crashed all sorts of things (I have no pagefile to save NVME space and stupid Windows couldn't handle it), and it did it in only 7 minutes.  I'm running Windows 11.  Nothing has changed recently, and it's never done it before, but twice today.  I only run one 2592x1944 security camera via USB.

![image](https://github.com/ispysoftware/iSpy/assets/66015018/51655333-2b6e-4747-a1b4-251e72ad7ea5)

The steep upward slope is ispy taking loads of memory, and when I killed it you can see how much it dropped by.

**Comment by ispysoftware** [comment]
ispy or Agent? have you checked the logs?

**Comment by hucker75** [comment]
ispy.  Where are the logs?  I cant find them.

**Comment by ispysoftware** [comment]
view - logs

**Comment by hucker75** [comment]
At the time in question I have a mass of these:
"Error | 02:24:11 AM | Front door: A generic error occurred in GDI+."

**Comment by ispysoftware** [comment]
usually that would be something like your graphics card updating it's driver or a hardware device issue

**Comment by hucker75** [comment]
I run Boinc (scientific computing) non-stop on the graphics card.  It's possible it interfered with it, especially as I'm running a beta app from Asteroids@Home just now.  Hasn't happened before.
