### ISSUE TITLE
Agent DVR File overwrite

### ISSUE THREAD

**Issue by Tornadoalley** [ispysoftware/iSpy#215]
How do I configure a camera to record continuously and overwrite old footage after a certain period or when the drive becomes full?

**Comment by ispysoftware** [comment]
wrong repo
for questions about Agent DVR see https://www.reddit.com/r/ispyconnect

just click record, set storage limits in storage settings when you edit the device

https://www.ispyconnect.com/userguide-agent-storage-management.aspx
