### ISSUE TITLE
Suggestion: Bulk Settings *Agent DVR*

### ISSUE THREAD

**Issue by Tornadoalley** [ispysoftware/iSpy#216]
Can you add a feature to bulk edit settings on multiple cameras? For example, I have 16 cameras that I need all to record at 30fps but it would take a while to change all of the settings individually. A bulk feature would allow you to apply the recording settings or any other setting to multiple cameras at once. Thank you for your help!

**Comment by ispysoftware** [comment]
wrong repo

you can do this by using the server menu, copy settings
