### ISSUE TITLE
VLC delay not working

### ISSUE THREAD

**Issue by Tornadoalley** [ispysoftware/iSpy#218]
Hello, I am having an issue with streaming my RTSP camera via Agent DVR. It appears to be very stuttery compared to the original network stream. I have tried many fixes such as the following:
1. Increase/Decrease FPS
2. Configure VLC caching to higher/lower (anything past 1000 does not appear to make the stream any delayed)
3. Increase/Decrease resolution
4. Modify encoding to VLC/CPU/GPU/None
5. Change User Agent browser from Chrome/Edge/Firefox
6. Enable/disable http 1.0
7. Modify Buffer Time
Note that Agent DVR is the only application running and does not occupy more than 50% of my system resources. I streamed from both the camera and Agent DVR using the same browser, device, and internet, all at the same time. No other cameras were running in Agent DVR at the time. See the attached video to see the differences. Agent DVR appears to load the stream quicker only because the split screen was stitched incorrectly

https://user-images.githubusercontent.com/73433060/185727653-7ed54dcc-d9a7-4610-8b95-9bb6157cbca5.mp4

.

**Comment by ispysoftware** [comment]
wrong repo,
only use VLC if you are unable to connect with anything else as it's not hardware accelerated. Use CPU or GPU to decode.

see stuttering video
https://www.ispyconnect.com/userguide-agent-DVR.aspx#troubleshooting

make sure you're using the latest version
