### ISSUE TITLE
Issues with signing post and missing libraries!

### ISSUE THREAD

**Issue by xsamir** [ispysoftware/iSpy#219]
Hi,

I'm stuck in this part: " _Remove the signing post build event command as the code signing certificate is not part of the source code of the project._ "

Where's the signing post location?

What I tried is deleting the previous build & make sure that I unchecked the (Sign the ClickOnce manifest)!
Also, I faced another problems like: _CS0246 The type or namespace name 'NETWORKLIST' could not be found_

Thanks

**Comment by ispysoftware** [comment]
it's in the post build event list

NETWORKLIST - check the references - you'll be missing an interop.NMetFwTypeLib or similar reference

**Comment by xsamir** [comment]
Thanks a lot, the problem solved
