### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by infinity277** [ispysoftware/iSpy#22]
Hi, why I get this error when I tried to compile the project?

This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=317567.	iSpyApplication	C:\Users\User\Downloads\Compressed\ispyconnect-master\iSpyApplication\iSpyApplication.csproj	1685

**Comment by mirh** [comment]
Close and reopen VS
Sometimes it fails to load nuget stuff that has just been downloaded

**Comment by infinity277** [comment]
I still get the error after i restart my visual studio
