### ISSUE TITLE
Agent DVR - "Call URL" in Actions

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#220]
Very useful feature!!... but it would be even more useful if you could choose the content-type since nowadays the use of a JSON body is quite common.

Is there a trick to do it? :-)

**Comment by ispysoftware** [comment]
I'll add a Headers parameter - you could also do this with a proxy server or just ignore the default content type on the receiving service

**Comment by alexbn71** [comment]
Unfortunately the receiving side isn't under my control

**Comment by alexbn71** [comment]
Thank for this new feature in 4.1.9
