### ISSUE TITLE
Agent DVR: Action Commands issue

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#221]
Currently this is what AgentDVR do when calling commands (log file):

`executecmd: /bin/bash -c "/agent/Commands/myscript.sh"`

you should use single quotes for -c parameter otherwise is a problem to pass string arguments to the shell script, it should be

`executecmd: /bin/bash -c '/agent/Commands/myscript.sh'`

so with parameters would become

`executecmd: /bin/bash -c '/agent/Commands/myscript.sh "param1" "param2"'`

Thanks

**Comment by ispysoftware** [comment]
hello any reason you closed this?
