### ISSUE TITLE
AgentDVR Issue: Time Machine/Timeline/Recording

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#223]
After an upgrade from 4.1.3 to 4.1.8

I don't know if I activated something by mistake ... but all the playbacks of the videos are speeded up so much ... 15 minutes are seen in a few seconds

If I go into the time machine and I start a 15 minute piece ... in the preview it shows me everything in a few seconds at 10x and more while the time machine bar moves at the right speed. The time machine is still playing the same piece while the movie is finished and a gray video camera icon appears in the preview box.

I've played the 15 minutes .mp4 file with a VLC and it shows correctly

If I playback in "Recordings" I can't slow down the playback... numpad + and - have no effect

I've noticed that "raw" file are played correctly... only encoded one has this issue during playback in AgentDVR

**Comment by alexbn71** [comment]
If I go into the time machine and I start a 15 minute piece ... in the preview it shows me everything in a few seconds at 10x and more while the time machine bar moves at the right speed. The time machine is still playing the same piece while the movie is finished and a gray video camera icon appears in the preview box

**Comment by ispysoftware** [comment]
this is a bug with motion adaptive encode playback - fix will be in next update

**Comment by alexbn71** [comment]
Thanks, it works now on 4.1.9
