### ISSUE TITLE
AgentDVR issue: Actions - "Copy From"

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#224]
Version 4.1.8. It seems that this function is not working.

I click on "Copy From" then select the "from" camera... and nothing happen. No actions copied.

Thanks
Alex

**Comment by ispysoftware** [comment]
seems to be working ok here - what actions are you copying and have you checked the logs for errors (at /logs.html)

**Comment by alexbn71** [comment]
This is the error:

`<html>
<body>


08:29:19 | JSON Processor: JSON Processor: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
-- | --
08:29:19 | Error: JSON Processor: JSON Processor: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
08:29:19 | JSON Processor: at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream , Object ) at CoreLogic.Statics.DeepClone(Object obj) at CoreLogic.Utilities.DeviceCopier.CopySection(IAgentControl source, IAgentControl dest, String section, Boolean merge) at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String command, String fullcmd, String data, RTCSession session)
08:29:19 | Error: JSON Processor: at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream , Object ) at CoreLogic.Statics.DeepClone(Object obj) at CoreLogic.Utilities.DeviceCopier.CopySection(IAgentControl source, IAgentControl dest, String section, Boolean merge) at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String command, String fullcmd, String data, RTCSession session)
08:29:19 | BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.


</body>
</html>`

**Comment by ispysoftware** [comment]
well that's a new one what OS is this?

**Comment by ispysoftware** [comment]
fix in next update

**Comment by alexbn71** [comment]
> well that's a new one what OS is this?

Docker image
