### ISSUE TITLE
AgentDVR Issue: Port Forwarding Access

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#226]
Hi, I have an "Agent DVR Business License" but something doesn't work with my remote access. 
I've forwared these ports 8090, 3478, 50000-50010 but remotly I get this error: "Try another browser or check firewall isn't blocking ports. See server menu (locally) for remote access.".

Could you help me to troubleshoot this issue?

<html>
<body>

08:51:16 | rtc:added servers
-- | --
08:51:16 | rtc:inited peer connection (True)
08:51:16 | rtc:set flag
08:51:16 | rtc:onsuccessanswer
08:51:16 | ICE state: Checking
08:51:31 | ICE state: Failed

</body>
</html>

**Comment by alexbn71** [comment]
I found the problem... port 3478 is UDP not TCP. Here https://www.ispyconnect.com/userguide-agent-dvr.aspx#:~:text=To%20access%20Agent%20over%20your,1.2). isn't specified.

**Comment by ispysoftware** [comment]
updated docs
