### ISSUE TITLE
AgentDVR issue: ONVIF version - PTZ and Presets

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#228]
I'm curious to understand how ONVIF devices capabilities are discovered. I have a cam that analysed with "ONVIF Device Manager" report "ONVIF version: 2.01". 

If I look at AgentDVR log file I see this:

<html>
<body>

07:58:51 | Sala Pranzo: Recording Opened
-- | --
08:00:46 | Discovery (GetServices): ONVIF v2.1
08:00:46 | Discovery: Using Media Version 1
08:00:46 | Discovery: Events available at http://192.168.178.76:8000/onvif/event_service

</body>
</html>

Why AgentDVR it's using 2.1 version? instead of 2.0?

The issue is that sometimes (but rare) Agent catch the correct presets list and PTZ controls and everything works but the major of times not... no presets and PTZ does not work. It's seems a very unstable behaviour

**Comment by ispysoftware** [comment]
it's calling an endpoint in the onvif spec that it looks like not all cameras support
i've added code to fall back to the original endpoint in case of failure
let me know if it persists after update
