### ISSUE TITLE
AgentDVR Dlink-DCS-5222L issue with PTZ

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#229]
In the list of PTZ cameras this model is present. With this the camera motion controls works fine but not the presets list. I see a list of two items that are not really defined ("Go Preset 1" and  "Go Preset 2"). If i set PTZ with a generic "ONVIF" the presets are ok (the list is correct) but it doesn't work the motion. When I hit a direction the camera instead of doing a step start moving until reachs the end.

Any suggestion?

**Comment by ispysoftware** [comment]
try the dlink option for model DCS-5230 Series

see
https://www.ispyconnect.com/userguide-ptz.aspx
Adding PTZ Support for Unlisted Cameras

**Comment by alexbn71** [comment]
Same behaviour with DCS-5230.

About Fiddler... the difficulty is that I have to discover how the camera web interface retrieve the presets list but the web interface don't have an action that do this job. Is differet from sniffing camera motion clicking on the direction keys. The command for adding a new preset is easy to catch since there is a "Add" button that make exactly only that request. The preset list instead is returned calling the path "/eng/mainFrame.cgi?nav=Setup#" and this request does not contain the command for the presets.

**Comment by alexbn71** [comment]
The first mistake in PTZ2.xml for DCS-5222L

`    <Makes>
      <Make Name="DLink" Model="DCS-5222L Series" />
    </Makes>
    <CommandURL>
    </CommandURL>
    <Commands>
      <Center>/cgi/ptdc.cgi?command=go_home</Center>
      <Left>/cgi/ptdc.cgi?command=set_relative_pos&amp;posX=-10&amp;posY=0</Left>
      <Right>/cgi/ptdc.cgi?command=set_relative_pos&amp;posX=10&amp;posY=0</Right>
      <Up>/cgi/ptdc.cgi?command=set_relative_pos&amp;posX=0&amp;posY=10</Up>
      <Down>/cgi/ptdc.cgi?command=set_relative_pos&amp;posX=0&amp;posY=-10</Down>
    </Commands>
    <ExtendedCommands>
      <Command Name="Go Preset 1">/cgi/ptdc.cgi?command=goto_preset_position&amp;presetId=0</Command>
      <Command Name="Go Preset 2">/cgi/ptdc.cgi?command=goto_preset_position&amp;presetId=1</Command>
    </ExtendedCommands>`

the correct command to request a preset is: /cgi/ptdc.cgi?command=goto_preset_position&index=0

**Comment by alexbn71** [comment]
I found a post that helped to find the command to get preset list and it works on my DCS-5222L

/config/ptz_preset_list.cgi  

the responde in my case is:

`presets=Porta_Ingresso,Finestrone,Cucina,Divano
Porta_Ingresso=92,79
Finestrone=212,89
Cucina=102,79
Divano=122,69`

**Comment by ispysoftware** [comment]
yeah you'd just need to edit the xml/ptz2.xml and restart agent  - but be aware that file will be overwritten when you update it.
I'm guessing index 0 = Porta_Ingresso ?

It'd be better to fix the issue with ONVIF - if you want to port forward the camera and send me the details I can take a look at doing that instead

**Comment by alexbn71** [comment]
I agree with you, it is better to fix ONVIF as the presets are handled better
