### ISSUE TITLE
How to get the CameraWindow instance in the MainForm.cs

### ISSUE THREAD

**Issue by MyYaYa** [ispysoftware/iSpy#23]
I want to know where the instance of CameraWindow showing on the MainForm is. To be exact, I open a local camera, I need to do some operations on the camera, but in the MainForm.cs, I cannot find the variable representing the CameraWindow I opened.
I know the variable '_cameras' in the MainForm_Configuration.cs, but I don't how to get the specific instance.
Thanks!

**Comment by ispysoftware** [comment]
controls/camerawindow.cs
