### ISSUE TITLE
AgentDVR issue: SSL

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#230]
I own a "Business License" and I've configured "SSL Port" to 8091. I know that this can be used only on local network but it doesn't work, chrome returns "ERR_CONNECTION_CLOSED" for address https://myserver:8091

This from log:

<html>
<body>

21:23:32 | Listening for SSL connections on port 8091. Check troubleshooting on https://www.ispyconnect.com/userguide-agent-ssl.aspx if you are unable to access.
-- | --
21:23:32 | Accepting http connections at http://*:8090/

</body>
</html>

**Comment by ispysoftware** [comment]
did you go through the steps to bind an SSL cert to your port?
https://www.ispyconnect.com/userguide-agent-ssl.aspx

**Comment by alexbn71** [comment]
> did you go through the steps to bind an SSL cert to your port?
SSL cert isn't mandatory I force chrome to go further

> you might need to access it via IP instead of host name

Same issue with IP although I don't think this is mandatory. AgentDVR is installed on unRAID NAS and I access it through SSL and a local domain name without issues (bypassing the certificate verification on chrome). 

The problem for now seems to be AgentDVR but I don't know how to analyze the problem since the log in this case does not help. Any suggestion?

**Comment by alexbn71** [comment]
I'noticed that config.xml has "<RequireLANSSL>false</RequireLANSSL>" what does means this flag?

**Comment by ispysoftware** [comment]
it's unenforced, was part of ispy.
have you tried it in other browsers (firefox)? Chrome has stringent requirements on certificate encryption levels.

**Comment by alexbn71** [comment]
Tried now, same issue on firefox: PR_END_OF_FILE_ERROR. 
With fireforx I can navigate the same unRAID server and the nginx instance with https and no certificate installed bypassing the certificate verification like on chrome.

**Comment by alexbn71** [comment]
I've tried a new fresh install of AgentDVR installed natively on Ubuntu (no docker) and the issue is still there. Are you sure that SSL works also on linux build of AgentDVR?

**Comment by ispysoftware** [comment]
for linux you need a reverse proxy for ssl
https://www.scaleway.com/en/docs/how-to-configure-nginx-reverse-proxy/
i haven't done that myself - only tested ssl on windows but i've heard from others that it works ok

**Comment by alexbn71** [comment]
Sorry, but something it's not clear. A reverse proxy is often used to access from outside a server in you network that does not support SSL natively. So in this case from outside you estabilish an SSL connetcion and the reverse proxy forward the request to your application via HTTP since does not support HTTPS. Is this your case?

> i've heard from others that it works ok

Yes but if they use a reverse proxy your application just needs to run in HTTP ... and that's what it looks like at the moment

**Comment by ispysoftware** [comment]
on linux it's using the .net http listener which doesn't have native support for SSL - it does on windows

**Comment by alexbn71** [comment]
now it's clear :-)  You should specify better on this page: https://www.ispyconnect.com/licensing/agent.aspx that SSL support is not  natively supported on Linu as it mattered when I chose to pay for this license

**Comment by ispysoftware** [comment]
https://www.ispyconnect.com/userguide-agent-ssl.aspx

SSL install on Unix (Linux/ Mac)
Setting up SSL on Unix is different to Windows. You will need to use a reverse proxy. See [NGINX Reverse Proxy](https://www.scaleway.com/en/docs/how-to-configure-nginx-reverse-proxy/) for an example.

**Comment by ispysoftware** [comment]
yeah it's more of a request for microsoft to add support for SSL to
httplistener in net core - it's not something I wrote. I could move it over
to asp.net and use kestrel but that is quite a major change - will look
into it though
