### ISSUE TITLE
Start RTMP streaming of view by Agent command

### ISSUE THREAD

**Issue by drlight17** [ispysoftware/iSpy#232]
Hello! Is there any way to run RTMP streaming of view by command or script? Or maybe to schedule start of view streaming?
For now I found only an ability to schedule start of RTMP streaming of selected device, but not the entire view.
My task is to start RTMP streaming of view with the start of agent dvr service (for example, in case of service or server reboot).
Thank you for the answer and great software!

**Comment by ispysoftware** [comment]
will be in next update, call it like:
q.json?cmd=start-rtmp-view&ind=0
where ind is the index of the view

**Comment by drlight17** [comment]
> 

Thank you!
I've upgraded to 4.2.6.0 and created the following command file, but it doens't work:
`REM ispy-internal
start-rtmp-view&ind=0`

As I understand it's because such commands appended to command.cgi?cmd= and not q.json?cmd= ?

**Comment by ispysoftware** [comment]
yeah you'll need to just use a regular batch file and call the local server

https://curl.se/windows/

curl http://localhost:8090/q.json?cmd=start-rtmp-view&ind=0

**Comment by drlight17** [comment]
Ok, thanks!
