### ISSUE TITLE
AgentDVR Memory Leak?

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#233]
I've noticed that the service start consuming 4GB (for 7 IP cams in my case).... and this value grows up in the following hours/days reaching at least 12GB. 

I've started the service 5 hours ago... from 4GB we are now at 6.5GB and the trend is to grow further. Is it normal?

**Comment by ispysoftware** [comment]
no doesn't sound normal, you'd need to check the logs though, not aware of a memory leak in it

**Comment by ispysoftware** [comment]
.. also you'd need to do some testing - install another instance, connect to one camera and enable functionality until you see a memory increase

**Comment by alexbn71** [comment]
...now, after about 24h the memory consumption reached 9GB. (32GB installed)

on an i7 similar to the one where I have this problem but with only 6GB installed the machine became unusable after a few hours, with an the identical cam configuration. Do you see something strange in the log?
[log.txt](https://github.com/ispysoftware/iSpy/files/9651714/log.txt)

**Comment by ispysoftware** [comment]
log looks ok, any particular reason you are encoding and not raw recording? should get much better performance recording from the raw feed.

**Comment by alexbn71** [comment]
> any particular reason you are encoding and not raw recording?

wouldn't the space occupied by the recordings increase dramatically?

**Comment by ispysoftware** [comment]
It depends really on your cameras and the encoding profile.

I've been testing the motion adaptive encode and can't find a leak in it - possibly it's something specific to do with your config. If you can narrow down what is causing it that would help.

**Comment by alexbn71** [comment]
update, currently consumption 10.5GB... I want to see where it stops

> Possibly it's hardware related, like your computer can't encode 7 cams simultaneously and is buffering video

the CPU load is stable at 25% and this machine has 32GB of RAM... how can I suspect an issue on encoding?

**Comment by ispysoftware** [comment]
try saving raw and see if you have the same problem

**Comment by alexbn71** [comment]
I've converted all recordings to raw. The CPU decreased a little from 25% to 20%... memory consumption from 10GB to about 8GB. I've still not restarted AgentDVR for now.

**Comment by alexbn71** [comment]
on the other server  i7 (6GB RAM) I noticed that starting one cam at time what's changed is the CPU load but the memory consumption remained constant. The strange things is that on this maschine 7 cams in raw mode are using only 1.3GB of RAM. 

On the main server i7 (32GB RAM) the conversion of all cams to raw (without restarting AgentDVR) has decreased the consumption by 2GB from the 10GB. The suspect is that if I restart AgentDVR on this server the consummption will collapse to 
costant 1/2 GB like on other server.

this shows that there were several GB of RAM occupied by? ... at least 6

**Comment by alexbn71** [comment]
it is almost certain that something remains resident in memory of no longer needed.

Try this: start with a cam configured as "motion encoded" and take note of the memory consumption. Now change the same cam to "raw" without restarting agentdvr. You will notice that the memory does not change... does not decrease. Now keep the cam configured as "raw" and restart Agentdvr.... You should see that the memory allocated is far less.

**Comment by ispysoftware** [comment]
yeah i did that, didn't find an issue with it - all memory is disposed of when the recording is closed.
could you save your object list (server menu - backup/ restore - download devices) and send it to me?

sean at ispyconnect dot com

also, what OS is this?

**Comment by alexbn71** [comment]
The OS is Linux. The same issue it seems present both with a native and Docker installation

PS Devices sent by mail...

**Comment by alexbn71** [comment]
The RAM management on Linux is seems very buggy.

![image](https://user-images.githubusercontent.com/20998190/192691545-47b1d5c6-312b-4cda-bed8-02ff338dd0fc.png)

This is the RAM consumption after a disk full issue... 4GB of RAM when normally the value is .5GB. After a clean of all recording, the RAM hasn't changed. I had to restart AgentDVR for it to return to normal

![image](https://user-images.githubusercontent.com/20998190/192692034-cc22041d-3ffd-4e41-b81a-a6a3c7b2b31d.png)

**Comment by alexbn71** [comment]
This is the RAM when I change only one cam from raw to motion adaptive:

![image](https://user-images.githubusercontent.com/20998190/192692619-bd756a0b-a3b6-4120-8b83-db5dd9e642d6.png)

and this is when I switch back to raw for the same cam:

![image](https://user-images.githubusercontent.com/20998190/192693032-18505204-476e-4513-9859-dc4e3b5cda43.png)

in this case RAM decreas but not at the value when I start AgentDVR with the same cam already on raw mode.

**Comment by alexbn71** [comment]
I've found a process that dimostrate a memory leak at least on Linux.

Configure a cam as "motion adaptive" recording. Then start AgentDVR and take note of the memory used ( when stabilized) by the process (in my case about .5GB).  Now simply use API to restart recording multiple time on this cam: /q.json?cmd=recordRestart&ot=2&oid=12 letting the RAM to stabilize. You will see that each itaration keeps about 50MB not  deallocated, so every start stop of recording it increases the RAM consumption progressively at each restart of the recording

**Comment by ispysoftware** [comment]
this sounds like a bug in ffmpeg's encoder on linux - did you install ffmpeg v5 from a package manager or build it using the Agent build script?

**Comment by alexbn71** [comment]
...from a package manager on Linux native install.... and if I'm not wrong also in the Docker version it's installed from package manager.

**Comment by ispysoftware** [comment]
If it wasn't deallocated then windows would have the same issue. They both use the same code base.
Everything is deallocated explicitly.
what are you using to monitor memory on a native linux install?

**Comment by ispysoftware** [comment]
Yes, I'm seeing the same thing - but leaving it for a while the memory usage drops back down again - suspect it's something to do with the way dotnet core is doing memory management. I'll take a look.

**Comment by ispysoftware** [comment]
can you try, in bash setting:
export MALLOC_TRIM_THRESHOLD_=100000
then start agent from the same terminal window

**Comment by alexbn71** [comment]
> but leaving it for a while the memory usage drops back down again

Unfortunately, not in my case after 12h the situation is this:

![image](https://user-images.githubusercontent.com/20998190/193192829-5f7542d5-ed3f-4c1c-a385-be5336f26168.png)

very close to where I left it yesterday

**Comment by ispysoftware** [comment]
export MALLOC_TRIM_THRESHOLD_=100000

completely resolves the issue on my linux box

**Comment by alexbn71** [comment]
> MALLOC_TRIM_THRESHOLD_

Yes this workaround works... but how to apply this only for AgentDVR and not the whole system on reboot?

**Comment by ispysoftware** [comment]
I added

Enviroment="MALLOC_TRIM_THRESHOLD_=100000"

to the service definition file
https://github.com/ispysoftware/agent-install-scripts/blob/main/v2/AgentDVR.service

I *think* that only affects the Agent process, not 100% sure as this isn't really my area.

**Comment by alexbn71** [comment]
Yes it seems working and not affecting the system since "env" doesn't report this enviroment variable.

Now I'll let my cams as "motion adaptive" for a day to see what happen... thank you.

**Comment by ispysoftware** [comment]
make sure it's Enviro*n*ment not Enviroment - there was a typo in it earlier

**Comment by alexbn71** [comment]
> make sure it's Enviro*n*ment not Enviroment - there was a typo in it earlier

Yes it's correct since I copied and pasted from the script on github and tested again with cmd=recordRestart to be sure that the service had received the new variable.

**Comment by alexbn71** [comment]
I've noticed that the whole consumption for 7 cams in "motion adaptive" is far less of the 4GB of the previous situation... now about 2.5GB. I hope that the fixed value for new MALLOC_TRIM_THRESHOLD doesn't impact performance in an appreciable way.

**Comment by alexbn71** [comment]
Sean, this change should be passed to the mantainer of the Docker image since in that case Agent isn't started as registered service.

**Comment by ispysoftware** [comment]
yeah i was going to see how yours went with it before doing that

**Comment by alexbn71** [comment]
Mine is going well... oscillates between 44-45% and never exceeded the value of 45%

![image](https://user-images.githubusercontent.com/20998190/193241257-77693be5-5fac-454e-9b3f-f37bdb13a4ef.png)
