### ISSUE TITLE
Feature: enhance zoom capability on portrait view on small screens

### ISSUE THREAD

**Issue by timmeh87** [ispysoftware/iSpy#234]
Right now if a widescreen, horizontal camera is viewed full-screen on a vertical device (ie phone) screen by clicking on it, it shows up as a small viewable area which is a limitation of having to rotate the wide image on a vertical screen:

![image](https://user-images.githubusercontent.com/31858838/192384260-ad8b0fbc-68be-4298-82a2-84a111572ec1.png)

Which is normal. However, when the image is zoomed in, the original limits remain in place, which is not the expected experience when zooming

![image](https://user-images.githubusercontent.com/31858838/192384402-4332746f-da10-437b-bc74-737d46465603.png)

It should be possible to fill the whole screen with the zoomed image instead of artificially cropping it, which would be a big improvement for those who wish to use zoom on device screens

**Comment by ispysoftware** [comment]
i've been thinking about this for a while - it's far more complicated than you might imagine to calculate properly. I think i've got it working though - will be in next update

**Comment by timmeh87** [comment]
Thank you for this, I just caught the latest update and it works for me
