### ISSUE TITLE
No predefined command .bat files for AgentDVR Docker

### ISSUE THREAD

**Issue by alexbn71** [ispysoftware/iSpy#236]
Hi, what do you think about this? Do you think it is possible to find a solution on the software side? since via Docker there doesn't seem to be ...

https://github.com/doitandbedone/ispyagentdvr-docker/issues/495

at worst you could make the .bat commands downloadable as .zip, which each one then copies into its own commands folder.

**Comment by ispysoftware** [comment]
i did see that comment
