### ISSUE TITLE
CPU Affinity

### ISSUE THREAD

**Issue by Urodela** [ispysoftware/iSpy#24]
Hi there, i have a question and maybe github is a good place to ask... so here it is:

Is there any way to stop ispy.exe using CPU Core or Thread #0? Changing the CPU Affinity in Windows does not work as intended.

On a i7-5960X (8 Cores, 16 threads) and ispy CPU Affinity set to use only the last 4 Cores (8 threads) ispy still uses Core#0 with qcap.dll, LcProxy2.ax, CinVPU.dll and vcomp90.dll.

Maybe its FFmpeg codec library avcodec-56.dll which running on the First Core? Anyway, is there a way to stop ispy.exe using the first Core?

Alright, thanks for reading and have a good day!

**Comment by ispysoftware** [comment]
Hello i'm not sure - sounds like something (a driver)? is starting up and
using a different app domain. You could set the max cpu in settings which
should have a similar effect.
