### ISSUE TITLE
Agent DVR: crash when opening photos

### ISSUE THREAD

**Issue by AMD-NICK** [ispysoftware/iSpy#246]
I use agent dvr 4.5.2 via docker (but the problem started about half a year ago). For a long period of time I didn't log into agent until I ran out of space on my hard drive and accumulated a huge amount of videos and photos.

I wanted to clean up the photos, but the ispy just crashes when I open the page with them.

```
ispy-ispy-1 | Unhandled exception. Emgu.CV.Util.CvException: OpenCV: !buf.empty()
ispy-ispy-1 | at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
ispy-ispy-1 exited with code 139
```

There are thousands of photos stored there and I can't clean them because of this error...

https://user-images.githubusercontent.com/9200174/219899761-53356d7d-0315-444d-a411-b929cf5412ad.mp4

**Comment by ispysoftware** [comment]
This looks like a disk/ io error to me, like opencv can't read the image or a file pointer is bad on the disk and it's taking down the process. 
You can manually delete them though just delete the content from the drive
agent\Media\WebServerRoot\Media\video
and then the various camera directories are under that and the grabs/ photos are in there

**Comment by AMD-NICK** [comment]
I have 6 cameras. The /grabs files count 😮:
1 cam (space gate): 11940 files
2 cam (space outer): 3390 files
3 cam (elen): 710 files
4 cam (dacha road): 278 files
5 cam (dacha corner): 160 files
6 cam (dacha gorod): 204 files

Deleted all unnecessary files and the problem has been fixed

I was worried that there would be some entries in the .db file about the screenshots, so I was scared to delete them
