### ISSUE TITLE
Power failure setting reset

### ISSUE THREAD

**Issue by koeks** [ispysoftware/iSpy#248]
Hi,

Due to constant power interruptions in my country the server constantly dies and when it reboots it comes back factory reset sometimes and I have to upload backup files each time.

**Comment by ispysoftware** [comment]
Errm I'm not sure what i'm supposed to do about that - maybe you need a UPS?

**Comment by koeks** [comment]
UPS is unfortunately not viable (dies eventually) due to countries lack of power generation. Thought maybe something code wise could be resolved to assist with issue. If not will have to look at other solution to restore. Thank you

**Comment by koeks** [comment]
I assumed factory reset but it lost settings yeah. After power failure again this morning I got this. Looks like the config file is corrupt after power dropping.

08:08:17	Load Objects: Load Objects: There is an error in XML document (0, 0).
08:08:17	Error: Load Objects: Load Objects: There is an error in XML document (0, 0).
08:08:17	Load Objects: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at CoreLogic.Statics.GetObjects(String path)
08:08:17	Error: Load Objects: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at CoreLogic.Statics.GetObjects(String path)
08:08:17	Load Objects: Load Objects: Root element is missing.
08:08:17	Error: Load Objects: Load Objects: Root element is missing.
08:08:17	Load Objects: at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read58_objects()
08:08:17	Error: Load Objects: at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read58_objects()
08:08:17	Root element is missing.
08:08:17	Retrying...
08:08:18	Connected to MQTT server
08:08:19	Subscribed to Agent/commands
08:08:19	Load Objects: Load Objects: There is an error in XML document (0, 0).
08:08:19	Error: Load Objects: Load Objects: There is an error in XML document (0, 0).
08:08:19	Load Objects: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at CoreLogic.Statics.GetObjects(String path)
08:08:19	Error: Load Objects: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at CoreLogic.Statics.GetObjects(String path)
08:08:19	Load Objects: Load Objects: Root element is missing.
08:08:19	Error: Load Objects: Load Objects: Root element is missing.
08:08:19	Load Objects: at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read58_objects()
08:08:19	Error: Load Objects: at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read58_objects()
08:08:19	Root element is missing.
08:08:19	Retrying...
08:08:21	Load Objects: Load Objects: There is an error in XML document (0, 0).
08:08:21	Error: Load Objects: Load Objects: There is an error in XML document (0, 0).
08:08:21	Load Objects: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at CoreLogic.Statics.GetObjects(String path)
08:08:21	Error: Load Objects: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at CoreLogic.Statics.GetObjects(String path)
08:08:21	Load Objects: Load Objects: Root element is missing.
08:08:21	Error: Load Objects: Load Objects: Root element is missing.
08:08:21	Load Objects: at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read58_objects()
08:08:21	Error: Load Objects: at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read58_objects()
08:08:21	Root element is missing.
08:08:21	Retrying...
08:08:21	Backed up file to C:\Program Files\Agent\Media\XML\objects.xml.bak

**Comment by ispysoftware** [comment]
Ah ok, I can make it revert to a backup file in that case, will be in next
update

**Comment by koeks** [comment]
<3

**Comment by koeks** [comment]
Looks like the issue still persists unfortunately after v4.6.9.0.

**Comment by koeks** [comment]
<html><body>


22:19:21 | Load Objects: Load Objects: There is an error in XML document (0, 0).
-- | --
22:19:21 | Error: Load Objects: Load Objects: There is an error in XML document (0, 0).
22:19:21 | Load  Objects:    at  System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader,  String encodingStyle, XmlDeserializationEvents events)    at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader  textReader)    at CoreLogic.Statics.GetObjects(String path)
22:19:21 | Error:  Load Objects:    at  System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader,  String encodingStyle, XmlDeserializationEvents events)    at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader  textReader)    at CoreLogic.Statics.GetObjects(String path)
22:19:21 | Load Objects: Load Objects: Root element is missing.
22:19:21 | Error: Load Objects: Load Objects: Root element is missing.
22:19:21 | Load Objects:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()    at System.Xml.XmlReader.MoveToContent()    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read62_objects()
22:19:21 | Error: Load Objects:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()    at System.Xml.XmlReader.MoveToContent()    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read62_objects()
22:19:21 | Root element is missing.
22:19:21 | Retrying...
22:19:21 | Load Objects from Backup: Load Objects from Backup: There is an error in XML document (0, 0).
22:19:21 | Error: Load Objects from Backup: Load Objects from Backup: There is an error in XML document (0, 0).
22:19:21 | Load  Objects from Backup:    at  System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader,  String encodingStyle, XmlDeserializationEvents events)    at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader  textReader)    at CoreLogic.Statics.GetObjects(String path)
22:19:21 | Error:  Load Objects from Backup:    at  System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader,  String encodingStyle, XmlDeserializationEvents events)    at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader  textReader)    at CoreLogic.Statics.GetObjects(String path)
22:19:21 | Load Objects from Backup: Load Objects from Backup: Root element is missing.
22:19:21 | Error: Load Objects from Backup: Load Objects from Backup: Root element is missing.
22:19:21 | Load Objects from Backup:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()    at System.Xml.XmlReader.MoveToContent()    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read62_objects()
22:19:21 | Error: Load Objects from Backup:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()    at System.Xml.XmlReader.MoveToContent()    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderobjects.Read62_objects()
22:19:21 | Root element is missing.


</body>
</html>

**Comment by ispysoftware** [comment]
those messages are saying that it can't load in the backup file either. I think you'll need to run some disk checking tools
