### ISSUE TITLE
Feature request: Choose video stream for photo capture

### ISSUE THREAD

**Issue by MiCkSoftware** [ispysoftware/iSpy#249]
Hi,

Currently there is an option to use a jpeg url for photos but no option to use recording stream which has a higher definition.
It would be helpful to have this option.

Cheers
Mick.

**Comment by ispysoftware** [comment]
the recording stream isn't decoded so is unavailable. If you want to use the recording stream for photos you'd need to make it the live (decoded) stream.

**Comment by MiCkSoftware** [comment]
Hi !
Yes I know.
But I wish I could use SD stream on live view and high res stream for photo capture...
Cheers.
Mick.
