### ISSUE TITLE
Local use - Enabling SSL

### ISSUE THREAD

**Issue by georgev93** [ispysoftware/iSpy#250]
I would like to use AgentDVR locally via SSL. However, I see that that is a feature that's only accessed through a "business license"?

Am I missing something here? If this is open source software, is there some closed source portion of code that would prevent me from just setting a "businessLicenseIsPresent" variable to true? I think it is likely that I'm misunderstanding the business license enabling SSL functionality and it is instead providing access to some cloud-based resource that would make sense to pay for. In that case: how do I set up SSL access on my local network? And for that matter, is there an easy way to move the http port from 8090 to another port?

**Comment by ispysoftware** [comment]
Agent DVR isn't open source, iSpy is.
You can change the server port in server settings.
