### ISSUE TITLE
How can I use iSpy to record 1080p MP4 video?

### ISSUE THREAD

**Issue by zaijianbch** [ispysoftware/iSpy#251]
Hello:
I use iSpy to record long time video.
OS : windows 7 (No independent video card)
USB Camera : Logitech C920 （I can use this camera on windows 10 to record 1080p video,with windows 10 built-in camera software）

I set the camera Video resolution :1920*1080 24 bit, but when I record the vedio,the vedio's frame height and frame width is 640*360.
I tried to change the image quality, the video quality, nothing worked. The data rate and total bit rate of the video increased, but the frame height and frame width did not change.

So,please help me , how can I record a 1080p MP4 video,the frame height and frame width 1920*1080.

**Comment by ispysoftware** [comment]
uncheck resize

**Comment by zaijianbch** [comment]
> uncheck resize

May I ask where I can set the resize for the recoding video?
I didn't find it.

**Comment by ispysoftware** [comment]
On the Camera tab under Source when you edit the device.
