### ISSUE TITLE
Does iSpy support timed recording function?

### ISSUE THREAD

**Issue by zaijianbch** [ispysoftware/iSpy#253]
Hello:
May I ask if ispy supports automatic scheduled recording?

 I hope ispy can automatically start recording at 9am every day and stop recording at 19pm.

Where can I make such settings?

**Comment by ispysoftware** [comment]
yes in the scheduler
https://www.ispyconnect.com/userguide-agent-editing-cameras.aspx#schedule

**Comment by zaijianbch** [comment]
> yes in the scheduler https://www.ispyconnect.com/userguide-agent-editing-cameras.aspx#schedule

So , Agent DVR has this funciton , but iSpy dosn't has ?

**Comment by ispysoftware** [comment]
in ispy edit the camera, see the scheduler tab
