### ISSUE TITLE
Contact Issues

### ISSUE THREAD

**Issue by dener3id** [ispysoftware/iSpy#256]
Please make it easier to contact you without paying, not paying doesn't mean I didn't find a bug or something that breaks things or have something that urgent and it's should be easier to contact.

**Comment by dener3id** [comment]
The please sign in thing in the faq fails to allow contacting. maybe it fails for paid too, but as unpaid it fails for me.

**Comment by dener3id** [comment]
this is the agent dvr repo right? that's were I meant to post this.

**Comment by ispysoftware** [comment]
you don't need a paid account to contact us - just login to your account and go to 
https://www.ispyconnect.com/contact.aspx
or post on the reddit forum
