### ISSUE TITLE
Using iSpy from Kubernetes

### ISSUE THREAD

**Issue by querdenker2k** [ispysoftware/iSpy#262]
Hi there,
Great software. I tried this with docker and all worked fine.
I moved to my target environment with Kubernetes and the first trouble was that I need a license (that was the message on the webinterface), so i bought a license.
But the next thing is that i still can't connect "Try another browser or check firewall isn't blocking ports..."
With docker i tested that i can access the ui with just exposing port 8090. -> that worked
I used this docker image: mekayelanik/ispyagentdvr:4.9.4.0, but i also tried this: doitandbedone/ispyagentdvr:latest
With both no success. Kubernetes uses an Ingress aka reverse proxy which maps port 8090 behind 443 and a subdomain ispy.*.de

Could somebody please help what's the problem?

**Comment by querdenker2k** [comment]
Tried all the time with chrome. But in the morning there was a tab on my phone still open which shows the ispy page. So it seems to work (but not just with chrome)

**Comment by ispysoftware** [comment]
usually this means you need the other ports open (3478, 50000-50010)
