### ISSUE TITLE
How bypass authentication for Protect API?

### ISSUE THREAD

**Issue by kennethgomez01** [ispysoftware/iSpy#264]
I was wondering how would I call URL an api directly from Action, while protecting the api links by enabling "Protect API" from Local Server menu? I was trying to start an rtmp-view by calling the api url, while calling "http://user:pass@localhost:8090/?q.json?cmd=start-rtmp-view&ident=indent&ind=0" , or using the BASIC Auth header but it all causing an error from the log.

**Comment by ispysoftware** [comment]
what are you putting in the header field and what error are you getting in the logs at /logs.html?

**Comment by kgomez6** [comment]
I just put the value for Basic Auth Header value that I got from the ispy official website, and placed this value in the Authorization Header field as format "BASIC value"


 `<html>
<body>


AM | Process: {"error":"Uncheck Protect API in server settings - local server or provide Basic Authentication using an admin user account."}
-- | --



</body>
</html>`

**Comment by kennethgomez01** [comment]
I just put the value for Basic Auth Header value that I got from the ispy official website after filling up my username and password (Admin account on my local ispy server) to generate these values, and placed this value in the Authorization Header field as format "BASIC value"


 `<html>
<body>


AM | Process: {"error":"Uncheck Protect API in server settings - local server or provide Basic Authentication using an admin user account."}
-- | --



</body>
</html>`

`ProcessAlertEvent: Cannot access a disposed object. Object name: 'System.Net.HttpWebResponse'. at System.Net.HttpWebResponse.CheckDisposed() at System.Net.HttpWebResponse.get_StatusCode() at CoreLogic.Objects.Helpers.AlertProcessor.ProcessAlertEvent(IAgentControl io, IAgentControl source, objectsActionsEntry ev, String message, String tags, String aijson, String filename, String zoneList)`

**Comment by ispysoftware** [comment]
ah looks like it's case sensitive, so should be 
Basic YOURAUTH
will make it not case sensitive

**Comment by kennethgomez01** [comment]
I tried changing it to Basic MyAuth, and the problem still occured

**Comment by kennethgomez01** [comment]
I just want to protect the API from unauthorize users, while I can still access it freely.

**Comment by ispysoftware** [comment]
working here - 
![image](https://github.com/ispysoftware/iSpy/assets/800093/b017d004-edf5-4a32-bb49-c7d5322afe6b)

![image](https://github.com/ispysoftware/iSpy/assets/800093/20da01b6-4089-43d4-9cd4-1145e947839e)


logs:
Camera 1: ProcessAlertEvent: Processing URL (http://localhost:8090/command.cgi?cmd=getStatus)
ProcessAlertEvent: Response Code: OK

**Comment by ispysoftware** [comment]
http://user:pass@localhost:8090/?q.json?cmd=start-rtmp-view&ident=indent&ind=0
.. isn't a valid URL should be

http://localhost:8090/q.json?cmd=start-rtmp-view&ident=ident&ind=0

you have an extra ? in there

**Comment by kennethgomez01** [comment]
@ispysoftware Thanks ,I think the removing the extra punctuation and adding slash on the url makes it works.
