### ISSUE TITLE
Edit device result error [v5.0.8.0]

### ISSUE THREAD

**Issue by kennethgomez01** [ispysoftware/iSpy#266]
After the update. I was unable to edit device and error code appears both in UI and logs `Object reference not set to an instance of an object.`  Update success and updated to v5.0.8.0 for AgentSpy DVR, but this code error occurs.

Specs:
OS: Ubuntu x86_64
Docker: No

**Comment by ispysoftware** [comment]
working here - needs steps to reproduce it  - try pressing shift - f5 to reload the web client
what else do the logs say?

**Comment by kennethgomez01** [comment]
after further looking at the logs every time I click on the edit device, here is the error I got, but please keep in mind tried restart my device, clear cache and data from my browser and same result I am getting after the update.

`LoadJson: Object reference not set to an instance of an object. at CoreLogic.Utilities.Helper.SummariseObject(String json, String lc, String param1, String param2, IAgentControl thisDevice) at CoreLogic.Utilities.Helper.ActionSummary(objectsActionsEntryEntry e, String lc, IAgentControl ctrl) at CoreLogic.Utilities.Helper.ActionSummary(objectsActionsEntry oae, String lc, IAgentControl ctrl) at CoreLogic.Statics.MergeActions(String json, Int32 ot, Int32 oid, String lc) at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String command, String fullcmd, String data, RTCSession session)
`

**Comment by ispysoftware** [comment]
Thanks - could you email me your configuration? (agent server menu - backup/ restore and download the zip file) - sean at ispyconnect dot com
thanks

**Comment by ispysoftware** [comment]
uploading a fix now thanks
