### ISSUE TITLE
Using Call URL action with multiple headers

### ISSUE THREAD

**Issue by AndreMuis** [ispysoftware/iSpy#268]
I'm trying to hit an endpoint with multiple headers:

<img width="786" alt="Screenshot 2023-11-18 at 5 35 14 PM" src="https://github.com/ispysoftware/iSpy/assets/920149/31a5a588-7246-4fa1-9239-d5706e94a7f8">

but I keep getting:

<img width="725" alt="Screenshot 2023-11-18 at 5 35 38 PM" src="https://github.com/ispysoftware/iSpy/assets/920149/c67e1276-0829-4cf9-8cfd-3cd02c29d529">

I'm guessing the headers aren't being split by a new line. I've tried with the "\n" and without.

**Comment by ispysoftware** [comment]
seems like dotnet doesn't like directly adding the accept header to the headers collection.
I'll update it as a special case to set the property on the object instead.
you don't need to type \n in there

**Comment by AndreMuis** [comment]
That's weird. Looking forward to the update.

**Comment by ispysoftware** [comment]
this has been updated

**Comment by AndreMuis** [comment]
Thanks!
