### ISSUE TITLE
Detector: Reolink AI / ONVIF for cameras attached to Reolink NVR

### ISSUE THREAD

**Issue by rb2k** [ispysoftware/iSpy#274]
The Reolink NVR provides 'channels' for each attached camera.
I was easily able to add them as RTMP, but I can't find a place to specify the channel for either of the detectors.

I'd like to avoid adding the cameras directly since some of them are WiFi and adding yet another client to them probably doesn't help with reliability :)

Is there a way to specify the channel of the camera for either the ONVIF or Reolink AI detector?

**Comment by ispysoftware** [comment]
Hello I'll add a channel option to the next update
