### ISSUE TITLE
Off STUN/TURN on AgentDVR Docker

### ISSUE THREAD

**Issue by X3il** [ispysoftware/iSpy#283]
Hi, can I somehow get rid of the use of STUN / TURN servers and a bunch of listening ports from them?
I don't need any functions other than recording cameras via RSTP from the DVR, I saw access to the web panel that it can work without STUN, but specifically in ispy for some reason, the presence of STUN is mandatory, which is strange.

I'm not good at programming and can certainly ask a stupid question, but I didn't find the answer here either

**Comment by ispysoftware** [comment]
set stun server to disabled on server settings - local server
you might not be able to access it after you do that though, especially over the local network
