### ISSUE TITLE
Only default and mobilenet available when running Coral object detection?

### ISSUE THREAD

**Issue by th3t1ck** [ispysoftware/iSpy#284]
I'm using the Coral Edge TPU and it is working in CPAI. However I notice when running Yolo5ObjectDetection6.2 and CoralObjectDetection2.4.0 I only have two models available. When Coral is not running then the models, such as ipcam-combined, are available but not MobileNet. Not sure if this is intended behavior or a bug. I'm on AgentDVR [5.8.0.0](http://5.8.0.0/) currently.

![66j465pmf98e1](https://github.com/user-attachments/assets/c8f87e76-ac14-443e-afad-b127d883d63b)

**Comment by ispysoftware** [comment]
you can manually set the model endpoint if you know it - the available list is provided by CPAI so if you've got a question about why only those 2 are supported then ask here:

https://github.com/codeproject/CodeProject.AI-Server/issues

**Comment by th3t1ck** [comment]
Ok. Thanks for the info and pointer to the right place to ask.
