### ISSUE TITLE
if record the vedio with audio，Ispy shutdown

### ISSUE THREAD

**Issue by best4s** [ispysoftware/iSpy#33]
Dear Master；
  if record the vedio with audio，Ispy shutdown。i do not know how to fix it.
can you help me ?

**Comment by ispysoftware** [comment]
version? log file? windows event log?

**Comment by best4s** [comment]
the application error is:

Log Name:          Application
Source:            Application Error
Date:          2017/10/28 18:53:57
Event ID:         1000
Task Category:          (100)
Level:            ERROR
Keywords:          classical
User:            ME
Computer:            BESTUU
Description:
Error application name: iSpy.exe，version: 6.8.6.0，timestamp: 0x59e85228
Error module name: Msacm32.dll，version: 6.1.7600.16385，timestamp: 0x4a5bdf8f
exception code: 0xc0000005
Error offset : 0x00000000000039c7
Error process ID: 0x14a0
Error application startup time: 0x01d34fd52bc24605
Error application path: C:\Program Files\iSpy\iSpy.exe
Error module path: C:\Windows\system32\Msacm32.dll
report ID: 4b6a75e9-bbce-11e7-8e92-241c04a0234b
event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-28T10:53:57.000000000Z" />
    <EventRecordID>32959</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DEEP-1705311143</Computer>
    <Security />
  </System>
  <EventData>
    <Data>iSpy.exe</Data>
    <Data>6.8.6.0</Data>
    <Data>59e85228</Data>
    <Data>Msacm32.dll</Data>
    <Data>6.1.7600.16385</Data>
    <Data>4a5bdf8f</Data>
    <Data>c0000005</Data>
    <Data>00000000000039c7</Data>
    <Data>14a0</Data>
    <Data>01d34fd52bc24605</Data>
    <Data>C:\Program Files\iSpy\iSpy.exe</Data>
    <Data>C:\Windows\system32\Msacm32.dll</Data>
    <Data>4b6a75e9-bbce-11e7-8e92-241c04a0234b</Data>
  </EventData>
</Event>


.NET Runtime :

Log Name:          Application
Source:            .NET Runtime
Date:            2017/10/28 18:53:57
Event ID:         1026
Task Category:          
Task Category:            ERROR
Keywords:           classical
User:            ME
Computer:            BESTUU
Description:
Error application name: iSpy.exe
Framework  version: v4.0.30319
Explanation: due to the exception of the process, the process terminates.
abnormal information: System.AccessViolationException
    NAudio.Wave.Compression.AcmInterop.acmStreamClose(IntPtr, Int32)
    NAudio.Wave.Compression.AcmStream.Dispose(Boolean)
    NAudio.Wave.WaveFormatConversionProvider.Dispose(Boolean)
    NAudio.Wave.WaveFormatConversionStream.Dispose(Boolean)
   System.IO.Stream.Close()
    iSpyApplication.Controls.VolumeLevel.AudioDeviceDataAvailable(System.Object, iSpyApplication.Sources.Audio.DataAvailableEventArgs)
    iSpyApplication.Sources.Video.MediaStream.ReadFrames()
   System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   System.Threading.ThreadHelper.ThreadStart()


event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-28T10:53:57.000000000Z" />
    <EventRecordID>32958</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DEEP-1705311143</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: iSpy.exe
Framework  version: v4.0.30319
Explanation: due to the exception of the process, the process terminates.
Abnormal information:
System.AccessViolationException
    NAudio.Wave.Compression.AcmInterop.acmStreamClose(IntPtr, Int32)
    NAudio.Wave.Compression.AcmStream.Dispose(Boolean)
   NAudio.Wave.WaveFormatConversionProvider.Dispose(Boolean)
   NAudio.Wave.WaveFormatConversionStream.Dispose(Boolean)
    System.IO.Stream.Close()
   iSpyApplication.Controls.VolumeLevel.AudioDeviceDataAvailable(System.Object, iSpyApplication.Sources.Audio.DataAvailableEventArgs)
   iSpyApplication.Sources.Video.MediaStream.ReadFrames()
   System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
    System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by best4s** [comment]
could you help me to find the problem?

**Comment by best4s** [comment]
I add 10  “rtmp://live.hkstv.hk.lxdns.com/live/hks”， to record the vedio And audio 。

after 1 hours，the ispy shutdown。

**Comment by ispysoftware** [comment]
are you running this from the source code build or the current release? I
checked in some code recently that might fix it.

**Comment by best4s** [comment]
I direct download the  iSpySetup.exe from url "http://ispyrtcdata.blob.core.windows.net/downloads/iSpy64_6_8_6_0.zip" .But it has the problem.

**Comment by ispysoftware** [comment]
yeah try the next update then let me know

**Comment by best4s** [comment]
OK .Thank you. sean tearney

**Comment by best4s** [comment]
The new Version 6.8.8.0 also has the problem。
I test it after 16 minutes. The ispy brokedown .The logs is as same as above with the same test environment.

**Comment by ispysoftware** [comment]
Hello i'm not sure what's causing it - i'm guessing that it's the first
thing to break when you overload your PC. If you can give me steps to
reproduce it then i can look into it.

**Comment by best4s** [comment]
If I were to record 14 video at the same time, 4 of them have sounds. After 22 hours，the Ispy breakdown. The log was the same as above.

If I were to record 14 video at the same time without sounds, ispy did well.

**Comment by ispysoftware** [comment]
Hello can you try the latest update. Possible fix.
