### ISSUE TITLE
FTP video uploading is broken

### ISSUE THREAD

**Issue by lehha** [ispysoftware/iSpy#35]
Last version v6.8.7.0 Platform: x64

After Alert fired (by plugin) record do in file, but not uploading to FTP. Log contain a error:

The process can not access the file "D:\Video\video\cam2\2_2017-10-31_14-53-33.mp4", because this file is being used by another process.

mscorlib
in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 
in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 
in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 
in System.IO.File.InternalReadAllBytes(String path, Boolean checkHost) 
in iSpyApplication.Controls.CameraWindow.FtpRecording(String path)

**Comment by ispysoftware** [comment]
Hello that means that something else is accessing the file - maybe explorer
search indexing or antivirus

**Comment by lehha** [comment]
No, Explorer is closed, no Antivirus installed. Search index disabled. Windows Defender also disabled.

I've remove that version and downgrade to 6.8.2.0 - and FTP work perfect.

I think there are a other reason. I dont know which. On forum another user says same thing.

**Comment by ispysoftware** [comment]
Repro'd this, will upload a fix today
