### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by lehha** [ispysoftware/iSpy#36]
Windows 7 64, iSpy version 6.8.7.0

Have a crash every 10-30 minutes. Windows error report:

Description
Invalid application path: C: \ program files (x86) \ iSpy \ iSpy.exe

Signature of the problem
Name of the problem event: CLR20r3
Signature of problem 01: ispy.exe
Signature of the problem 02: 6.8.7.0
Signature of the problem 03: 59f7be67
Signature of problem 04: System.Drawing
Signature of the problem 05: 4.0.30319.34209
Signature of the problem 06: 53489a75
Signature of the problem 07: 34
Signature of the problem 08: 1a
Signature of problem 09: System.AccessViolationException
OS version: 6.1.7600.2.0.0.256.1
Language code: 1049
Additional Information 1: ded4
Additional information 2: ded4b1be659bc76be8b782eb12ce2a27
Additional Information 3: 115c
Additional Information 4: 115ccca95720a57f0bfa62836196d695

**Comment by ispysoftware** [comment]
C: \ program files (x86) \ iSpy \ iSpy.exe

.. is an invalid path - where is it getting that from?

**Comment by lehha** [comment]
Yes, valid, Google Translate add space in path :)
iSpy monitor going crazy)

<img width="195" alt="monitor" src="https://user-images.githubusercontent.com/4051362/32307483-ad0cc848-bf91-11e7-82f4-bc5c1d399aa4.PNG">

**Comment by ispysoftware** [comment]
i'm not sure - you'll need to provide more information about what you are
doing and steps to reproduce the issue.

could you email me your object list (file - save object list) to sean at
ispyconnect dot com

Cheers!

**Comment by lehha** [comment]
Ok, will try. This issue came when use a plugin for alerting (sda_lib, payed lincense).

Without that plugin (on movement recodrind) iSpy works correctly more that 3 months without crash and restarting.

**Comment by ispysoftware** [comment]
where did you get the plugin from? you'll need to contact the plugin author
for that one..

**Comment by lehha** [comment]
Is it not yours plugin? From iplugs.eu

May be there are problem in iSpy code/function , that plugin uses. I have two report for this crash:

The name of the failed application: ispy.exe, version: 6.8.2.0, timestamp: 0x596344a6
The name of the failed module is: KERNELBASE.dll, version: 6.1.7600.16385, time stamp 0x4a5bdfe0
Exception code: 0xe0434352
Error offset: 0x000000000000aa7d
Id of the failed process: 0x16d4
The time to start a failed application: 0x01d3538512b9c2a9
The path of the failed application: C: \ program files (x86) \ ispy \ ispy.exe
The path of the failed module: C: \ Windows \ system32 \ KERNELBASE.dll
Report code: 9aff4d83-bf7b-11e7-a06d-001e8cb97c5d


and:

Application: ispy.exe
Platform version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception Information: System.Reflection.TargetInvocationException
Stack:
   in System.RuntimeMethodHandle.InvokeMethod (System.Object, System.Object [], System.Signature, Boolean)
   in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal (System.Object, System.Object [], System.Object [])
   in System.Reflection.RuntimeMethodInfo.Invoke (System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object [], System.Globalization.CultureInfo)
   in iSpyApplication.Controls.Camera.RunPlugin (System.Drawing.Bitmap)
   in iSpyApplication.Controls.Camera.VideoNewFrame (System.Object, iSpyApplication.Sources.NewFrameEventArgs)
   in iSpyApplication.Sources.Video.MediaStream.ReadFrames ()
   in System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   in System.Threading.ThreadHelper.ThreadStart ()

This reports are identical for all crash in my case.

**Comment by ispysoftware** [comment]
no not our plugin, you'll need to contact iplugs, most likely an issue with
that plugin. You can try reverting ispy to v6.5.8.0 and see if you have the
same issue.
