### ISSUE TITLE
wireless camera constantly disconnects only in iSpy

### ISSUE THREAD

**Issue by vst8800** [ispysoftware/iSpy#37]
Hi,

Unknown china made wireless camera constantly disconnecting only in iSpy. The ping to it is constant with no lost packets. Seen in its web interface while disconnected in iSpy.

In the log:

...
Error	8:15:33 PM	AV_READ_FRAME: Error number -138 occurred, FFMPEG
Error	8:15:33 PM	Camera 4: Device Lost
Error	8:15:38 PM	AV_READ_FRAME: Error number -138 occurred, FFMPEG
Error	8:15:38 PM	Camera 4: Device Lost
...

iSpy free v6.8.8.0 64-bit on Win 8.1 Pro x64.

Using http://192.168.4.140:81/videostream.cgi?loginuse=admin&loginpas=mypass as source URL as seen in web interface source code.

Tried TCP, UDP, UDP Multicast and HTTP Tunneling - same issue.

Please let me know if anything else is needed, so I can provide it.

Any help will be much appreciated.

**Comment by ispysoftware** [comment]
what version of ispy are you using? whats the timeout set to?

**Comment by vst8800** [comment]
iSpy v6.8.8.0 64-bit. Tried different timeouts now it is 2500 ms.

**Comment by ispysoftware** [comment]
can you port forward the camera so i can try it from here? sean at
ispyconnect dot com.

**Comment by vst8800** [comment]
Sure. Once I get on the physical location I will and will provide the IP and login details via e-mail.

**Comment by vst8800** [comment]
Already sent e-mail to you with the login details for the port forwarded cam as requested. Looking forward to the results of your testings.

**Comment by vst8800** [comment]
Hi again,

After I saw your advice to try to search the cam in the wizard I have done the following:

Using free Advanced IP scanner program I scanned my internal network 192.168.4.1 to 192.168.4.255.

There I found that the camera is resolved as "Shenzhen Smarteye Digital Electronics Co., Ltd".

Than I started iSpy Add "IP Camera With Wizard" set it as listed and wrote "Shenzhen Smarteye" which was found. supplied the IP, port, username and password. Few suggested URLs were found, confirmed that I want iSpy to validate them than only three were left.

Used the first one MJPEG "http://admin:mypass@192.168.4.140:81/videostream.cgi" instead of FFMPEG "http://192.168.4.140:81/videostream.cgi?loginuse=admin&loginpas=mypass".

Camera added successfully and no more disconnecting or issues.

I used an URL method found somewhere in the Internet instead using that great wizard. Which worked but not correctly.

Thank you very much for the time spent and all the great advises that led me to the resolution of my issue.

Please close the GitHub issue.
