### ISSUE TITLE
Ask for iSpyServer

### ISSUE THREAD

**Issue by xunxin03** [ispysoftware/iSpy#38]
Hi,
Thank you for making such a great project.
I have download the source and the exe to setup.
Also, I am actually very new to ISpy, I would like to know where I can get the iSpyserver source code? Are they in the Ispy source code? Or are they not open-sourced???
Thanks in advance!

**Comment by rsteckler** [comment]
If you're talking about iSpy Central, it doesn't look like it's open source.  Would be good to get a confirmation from the team, though.

**Comment by ispysoftware** [comment]
Hi no, ispycentral isn't open source.
