### ISSUE TITLE
If I  record 6 video at the same time with  6.8.8.0 ,the ispy would Video frame breaking.

### ISSUE THREAD

**Issue by best4s** [ispysoftware/iSpy#39]
Hi sean tearney；
If I  record 6 video at the same time with  6.8.8.0 ,the ispy would Video frame breaking.

**Comment by ispysoftware** [comment]
probably you've overloaded your PC

**Comment by best4s** [comment]
Dear sean tearney, could you  recommend  the cpu and os  to me？ Or the ispy use GPU ?

I hava used two cpu E5  2670 and win7 64bit system，but the result is not good.

But i use i5 cpu and win7 64bit system,the result is better than used E5 cpu.


Thank you .

**Comment by ispysoftware** [comment]
you could try using Agent instead, it has smaller cpu usage
http://www.ispyconnect.com/download-agent.aspx

**Comment by best4s** [comment]
but i don't have the source code to fix our project.

could you tell me the your im ? we could connet anytime.

**Comment by best4s** [comment]
if i use the  6.8.8.0.how it has smaller cpu usage ?

do you have the method ？

**Comment by ispysoftware** [comment]
have you read through the performance tips link at the bottom left of the
ispy application user interface?

**Comment by best4s** [comment]
With your method, I solved the problem. Thank you !
