### ISSUE TITLE
Dll references errors when building

### ISSUE THREAD

**Issue by khalilTN** [ispysoftware/iSpy#40]
Hi,
I'm was trying to build iSpy and encountred dll references errors

> Severity	Code	Description	Project	File	Line	Suppression State
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\AForge.Math.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	133	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\ispy.ico'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	65	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\AForge.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	127	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\AForge.Imaging.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	130	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\FlickrNet.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	136	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.Auth.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	139	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.Auth.PlatformServices.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	142	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.Core.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	145	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	148	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.Drive.v3.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	151	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.PlatformServices.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	154	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Google.Apis.YouTube.v3.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	157	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\iSpy.exe'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	160	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\ispy.ico'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	161	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\iSpy.exe.config'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	169	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\FFmpeg.AutoGen.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	172	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\iSpy.XmlSerializers.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	175	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\libmp3lame.32.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	178	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\log4net.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	181	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Microsoft.Kinect.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	184	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Microsoft.Threading.Tasks.Extensions.Desktop.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	187	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Microsoft.Threading.Tasks.Extensions.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	190	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\NAudio.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	193	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\NAudio.Lame.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	196	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Newtonsoft.Json.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	199	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\NSpeex.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	202	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\nVLC.Declarations.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	205	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\nVLC.Implementation.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	208	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\nVLC.LibVlcWrapper.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	211	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Renci.SshNet.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	214	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Renderers.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	217	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\RestSharp.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	220	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\SharpDX.DirectInput.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	223	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\SharpDX.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	226	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\System.Net.Http.Extensions.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	229	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\System.Net.Http.Primitives.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	232	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Windows7ToolStripRenderer.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	235	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\xiApi.NET.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	238	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Zlib.Portable.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	241	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\MySql.Data.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	247	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\avcodec-57.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	252	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\avdevice-57.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	255	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\avfilter-6.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	258	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\avformat-57.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	261	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\avutil-55.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	264	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\ffmpeg.exe'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	267	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\postproc-54.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	270	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\swresample-2.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	273	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\swscale-4.dll'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	276	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\XML\config.xml'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	281	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\XML\Log.txt'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	284	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\XML\objects.xml'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	287	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\XML\PTZ2.xml'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	290	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\XML\Sources.xml'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	293	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\XML\Translations.xml'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	296	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\backgrounds\FloorPlan_House.jpg'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	306	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\backgrounds\FloorPlan_House2.jpg'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	309	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\backgrounds\FloorPlan_Planet.jpg'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	312	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Masks\demo_mask.png'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	317	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Plugins\readme.txt'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	322	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\airhorn.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	327	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\alarm.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	330	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\alsationxsiberian_bark.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	333	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\alsation_bark.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	336	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\cairnterrierbark.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	339	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\doorbell.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	342	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\police.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	345	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\pop.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	348	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\rottweiler_bark.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	351	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\spanielgrowlbark.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	354	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\sounds\wiggle.wav'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	357	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\webserverroot\crossdomain.xml'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	362	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\webserverroot\favicon.ico'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	365	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\webserverroot\notfound.jpg'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	368	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\api.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	373	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editaction.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	376	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editaudiosource.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	379	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editcamera.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	382	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editftp.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	385	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editmicrophone.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	388	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editpelco.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	391	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editptzschedule.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	394	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editschedule.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	397	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editstorage.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	400	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\editvideosource.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	403	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\settings.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	406	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\showactions.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	409	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\showptzschedule.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	412	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\showschedule.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	415	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\0.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	420	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\1.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	423	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\2.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	426	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\3.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	429	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\4.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	432	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\5.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	435	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\audio\6.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	438	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\0.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	443	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\1.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	446	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\10.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	449	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\12.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	452	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\2.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	455	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\3.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	458	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\4.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	461	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\5.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	464	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\6.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	467	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\7.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	470	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\8.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	473	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\WebServerRoot\api\sources\video\9.json'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	476	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\webserverroot\data\mime.dat'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	481	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\bin\x86\Release\Commands\example.bat'.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	486	
Error		The system cannot find the file 'D:\Work\iSpy\iSpy-master\Wix\iSpy32\bin\Debug\iSpy32.msi'.	Bootstrap32	D:\Work\iSpy\iSpy-master\Wix\Bootstrap32\Bundle.wxs	20	
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	WixCA		1	Active
Warning		The primary reference "MySql.Data, Version=6.10.4.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".	iSpy32			
Warning		The Binary/@src attribute has been deprecated.  Please use the SourceFile attribute instead.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	9	
Warning		The 'CONFIGFILELOCATION' Property contains '[SourceDir]' in its value which is an illegal reference to another property.  If this value is a string literal, not a property reference, please ignore this warning.  To set a property with the value of another property, use a CustomAction with Property and Value attributes.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	10	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:lang' has already been declared.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	35	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:space' has already been declared.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	78	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:base' has already been declared.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	99	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:id' has already been declared.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	118	
Warning		The attributeGroup 'http://www.w3.org/XML/1998/namespace:specialAttrs' has already been declared.	iSpy32Setup	D:\Work\iSpy\iSpy-master\Wix\iSpy32\Product.wxs	136	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:lang' has already been declared.	Bootstrap32	D:\Work\iSpy\iSpy-master\Wix\Bootstrap32\Bundle.wxs	35	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:space' has already been declared.	Bootstrap32	D:\Work\iSpy\iSpy-master\Wix\Bootstrap32\Bundle.wxs	78	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:base' has already been declared.	Bootstrap32	D:\Work\iSpy\iSpy-master\Wix\Bootstrap32\Bundle.wxs	87	
Warning		The attributeGroup 'http://www.w3.org/XML/1998/namespace:specialAttrs' has already been declared.	Bootstrap32	D:\Work\iSpy\iSpy-master\Wix\Bootstrap32\Bundle.wxs	87	
Warning		The global attribute 'http://www.w3.org/XML/1998/namespace:id' has already been declared.	Bootstrap32	D:\Work\iSpy\iSpy-master\Wix\Bootstrap32\Bundle.wxs	87	

Thanks !

**Comment by ispysoftware** [comment]
looks like you're trying to build the setup package before building ispy itself. try building ispy in debug then release then the setup package

**Comment by khalilTN** [comment]
That was the cause, thanks a lot.
