### ISSUE TITLE
very large MP4 files

### ISSUE THREAD

**Issue by civilseven** [ispysoftware/iSpy#44]
Hi, any version since 6.5.8 ispy recordings are much larger.

6.5.8 - 1  hour of of 720p video from security cam is 350 MB bit rate(600k-800k)
6.9.1 - 1 hour of the same, is 4-5gigs (bitrate anywhere from (2000k-15,000k)

my cameras send x264 720p video (VBR 500k-800k).    version 6.5.8 is the only version that seems to work just fine.   please help.  i can provide further info if you need. or screenshots.    

thanks

**Comment by ispysoftware** [comment]
whats the framerate of the stream? How much movement is in it?

**Comment by civilseven** [comment]
i can set these settings on the camera, but it doesnt seem to matter issue always happens

![image](https://user-images.githubusercontent.com/36014180/35657810-7424d35e-06cc-11e8-8d93-b76feb58728b.png)

**Comment by civilseven** [comment]
6.5.8 -files for 1 hours of video are:  80 - 600 MB each and with bitrate 200k - 1300k 
6.9.1 - 3 - 6 gigs and bitrate 2000 - 20000

**Comment by ispysoftware** [comment]
yeah i meant in ispy - what framerate are you recording at? and how much
movement does the video have?

**Comment by civilseven** [comment]
1 ptz ipcam, never moves, daily activity, records at 16-18fps, and 2 fixed ipcams with daily activity, records at 10-11fps, and max fps set to 30 for all for playing and recording, cpu usage is 15-30%

**Comment by civilseven** [comment]
and thats in 6.5.8.0 and in 6.9.1.0 its the same fps's but with higher cpu 60-80%, and the much larger mp4's  i assumed because of the much higher bitrate

**Comment by ispysoftware** [comment]
I've uploaded a new version with a fix for this issue. Can you check and
let me know if it works?
Thanks

**Comment by civilseven** [comment]
tested one cam briefly this morning,  1 hour of video recorded at 2000k bitrate, file size is 912 MB, and cpu usage is also better,  its definitely an improvement from before,  however i would of really like it more being around the same as it was in 6.5.8, it think it would be best if the recording bitrate was around the same as the input streams bitrate,  or perhaps to have the option to choose the bitrate (or recording profile) would be amazing

-ive enabled all 3 cameras now, and testing all 3 and will compare all their bitrates and file size after a few hours, and will let you know.

**Comment by civilseven** [comment]
i've been keeping an eye on it, and so far i've noticed the FPS is fluctuating alot,  as low as 3fps and as high as 18fps from minute to minute, affecting all 3 cams, also no to very little movement,  cpu usage is 40 - 70%

-before in 6.5.8 all were pretty constant at 11,  (which i thought it was a little odd since the cameras are set to 25 fps, but ispy plays/records at 11)

also:

another hour of recorded, (second hour from the first one):   1881kbps, 12.13 fps, file size:  827 MB
second cam,  first hour:  2014kbps, fps 11.47, file size: 886 MB,
third cam (the ptz), first hour:  915kbps, 9.18 fps, file size:  433MB, no movment at all, audio: 67 kbps, 1 channel, 22.050khz
-ill keep it going a few more hours and advise.

**Comment by ispysoftware** [comment]
check your CPU limit in settings - usually this is because you are hitting
that and ispy lowers your framerate accordingly.
The cameras are set to 25fps but that'll be a maximum based on light levels.

**Comment by civilseven** [comment]
CPU is set to default 90. Priority: High, OS: Windows 10, CPU: AMD FX-6350 -stock speeds.

recording settings (all cams same):  Buffer: 0, and record time: 3600 
FPS still fluctuating 3-18, with average 10-14

-the PTZ cam (one with audio) is Wireless G to a dedicated accesspoint->dedicated switch, the other two cams are wired (wireless disabled while wired)

heres what the files look like for all 3 cams since upgrading to 6.9.2 and show files before with 6.5.8:

![image](https://user-images.githubusercontent.com/36014180/35708784-b1222fc0-077d-11e8-84b0-3f7d6c3d2275.png)
![image](https://user-images.githubusercontent.com/36014180/35708813-d0255640-077d-11e8-9d53-faa5d50c5e19.png)
![image](https://user-images.githubusercontent.com/36014180/35708854-088055f8-077e-11e8-8d6b-57fa2b2b3403.png)

**Comment by ispysoftware** [comment]
looks like it's due to a change in ffmpeg rather than in ispy - i'll look
into adding a bitrate field. The quality of recordings in the new version
of ispy is way better than the old version.

**Comment by civilseven** [comment]
a bitrate field, i think would be a really cool option/feature for Ispy, please let me know how it goes, id love to test and use that. also thanks so much for responding and actually fixing it so quickly for me (and everyone too). i really appreciate it,  now im not stuck on old version :) Ispy (and you) is honestly the best!

**Comment by ispysoftware** [comment]
thanks!
I've uploaded a new version here:

http://www.developerinabox.com/hosting/ispysetup.zip

- the quality slider in recording settings in the recent versions wasn't
actually hooked up to anything. I've fixed that so you should get smaller
file sizes with less quality and visually lossless larger file sizes with
maximum quality

let me know how that goes. Seems to be working here..

**Comment by civilseven** [comment]
hey man, i love it, it appears to be working very good now.  i've got the slider right in the middle and its 
perfect!  thank you soooo much you are truly awsome! 
i will continue testing it over the weekend.

**Comment by civilseven** [comment]
looking good man, it really works well!  only one thing i noticed is the timestamp ispy puts on, flashes randomly,  sometimes it happens alot and sometimes not so much.  other then that its perfect.

**Comment by civilseven** [comment]
hard to explain but somethings gotta be going on,  fps and time stamp keeps flashing randomly,  and after watching it more closely im noticing the FPS on the cameras is studdering also. and my watching the timestamp that the camera also shows i can see the second stop and them jump to catch up,  
-i tried disabling the ispy timestamp,  made no difference in the frame studder.    wish i could record it to show you

**Comment by civilseven** [comment]
tested some more
-v6.9.4,  timestamp flickers alot,  worse when recording.  fps shows studder, cams keep going offline randomly and coming back,   ping shows perfect pings, cam web player no issues.
-v6.9.2  same issue, timestamp flickers alot, worse when recording.  fps shows studder
-v6.9.1  timestamp rarely flickers, but flickers when recording,  (not as bad as higher version) fps -unable to notice studder
However, checked the record files, and i cant see that issue in the video, video in the record files are fine, no flashing of the fps, and no fps studder.  looks like is just a display issue in ispy from version 6.9.1, but gets worse in higher version, and even more worse while recording.

**Comment by civilseven** [comment]
update:
after testing more motion in the video, its very obvious the choppiness/studder of the video and how it freezes for a second or two, also the cams at still randomly going off/online.  (changing the rtsp mode didnt work).
-after reviewing the record file, issue hardly noticeable in the file playback.

**Comment by civilseven** [comment]
heres all for today
[logs.zip](https://github.com/ispysoftware/iSpy/files/1692359/logs.zip)

**Comment by ispysoftware** [comment]
hmm i'm not sure - nothing in the log files and it's working fine here, no
flickering or stuttering or anything - can you email me your object list?
(file - save object list) to sean at ispyconnect dot com.  Possibly some
configuration issue i'm missing.

**Comment by civilseven** [comment]
done

**Comment by civilseven** [comment]
used a free screen recorder, should play in VLC
[rec.zip](https://github.com/ispysoftware/iSpy/files/1692929/rec.zip)

**Comment by civilseven** [comment]
here this one better
[rec2.zip](https://github.com/ispysoftware/iSpy/files/1692938/rec2.zip)

**Comment by ispysoftware** [comment]
thanks for that, found it and think i've fixed it. Give this a go and let
me know

http://hosting.ispyconnect.com/ispysetup.zip

**Comment by civilseven** [comment]
ya it works good, thanks man! i keep tryin that, even seeing lower cpu usage too, and better fps

**Comment by civilseven** [comment]
well it was working good but ispy keep crashing randomly and doesnt reopen on its own even though the option is set to
crashed during the day yesterday, though maybe it was a one off, but happened over night again.
i dont see anything in the logs:
[logs3.zip](https://github.com/ispysoftware/iSpy/files/1699364/logs3.zip)

**Comment by civilseven** [comment]
yeah happened again, keep crashing, and doesnt automatically restart

**Comment by ispysoftware** [comment]
can you check the windows application event log?

**Comment by ispysoftware** [comment]
i rolled back one of the changes, might fix it.

**Comment by civilseven** [comment]
x64 of 6.9.6 appears to be fine no crash since install

**Comment by civilseven** [comment]
alright cool ill try 6.9.7 x64,    thanks for all the work your doin on this man, its pretty cool

**Comment by civilseven** [comment]
its working good man, you rock!

**Comment by civilseven** [comment]
thanks again sean, lemme know if you ever need a beta tester or something, id love to help!

**Comment by TheRolf** [comment]
Hello! Sorry to revive this thread, but I have a very similar issue with the latest iSpy. The recordings of two identical cameras result in files with 10x size difference. Moreover, this changes randomly, some days cam A has 10x sized files than cam B, the other day it's the other way around.
Some screenshots of current recordings:
![big](https://user-images.githubusercontent.com/18666618/80313262-24ef9700-87ea-11ea-9e62-18270569aa52.PNG)
![small](https://user-images.githubusercontent.com/18666618/80313265-2620c400-87ea-11ea-9302-3472740322cc.PNG)
I have some files from 2018, for ALL cameras this is how the filesizes looked like (they fluctuate a bit, but it can be explained with more/less movement, or changing light conditions):
![normal](https://user-images.githubusercontent.com/18666618/80313295-59635300-87ea-11ea-9b47-972e68ba7d97.png)

**Comment by civilseven** [comment]
hey, i dont use ispy anymore i use Shinoni on a Ubuntu VM now.  works way better, just bit harder to install.  has option to copy video stream rather then reencode it. uses very little cpu therefore can support way more cameras. it was way worth figuring out.  also its free too.   lemme know if you want more info or need help setting up.
cheers

    On Sunday, April 26, 2020, 12:19:31 PM EDT, TheRolf <notifications@github.com> wrote:  
 
 


Hello! Sorry to revive this thread, but I have a very similar issue with the latest iSpy. The recordings of two identical cameras result in files with 10x size difference. Moreover, this changes randomly, some days cam A has 10x sized files than cam B, the other day it's the other way around.
Some screenshots of current recordings:


I have some files from 2018, for ALL cameras this is how the filesizes looked like (they fluctuate a bit, but it can be explained with more/less movement, or changing light conditions):

**Comment by ispysoftware** [comment]
Our new platform agent does raw recording as well. Adding a Linux and Mac version soon.

**Comment by TheRolf** [comment]
@ispysoftware If you're talking about the AVI Uncompressed option: the problem with that is that it results in a 7GB file for 15 minutes. If I choose the AVI with MPEG4, the file sizes are super small, but the quality of the video suffers, it is extremely "blocky".

**Comment by ispysoftware** [comment]
I'm not. Agent records the camera stream directly without reencoding. See the downloads page on the website.

**Comment by TheRolf** [comment]
iSpy Agent looks very nice and so far the recordings are as they should be, thank you for the tip! However cameras keep dropping, and the only way to get them working is to restart the service, the "All Off and All On" buttons don't help. The cameras are quite old and not the most reliable, but with the old iSpy they managed to reconnect every time.

**Comment by ispysoftware** [comment]
Need some more info- what version are you on, what operating system, how are you connecting to them (network/usb?), have you checked the logs (in the system menu in agent)

**Comment by TheRolf** [comment]
I use MJPEG sources, I updated to the newest version. Btw you could warn the user that they should save their devices data, I had to import a backup after the update. And also that XML file doesn't seem to contain the global storage directory? 

Another question: if I set a size limit in the global storage management, will it remove the oldest files from subdirectories as well? I use a python script that moved the recrodings into daily folders, and iSpy used to remove the oldest files from those directories too, but it doesn't seem to be the case.

**Comment by ispysoftware** [comment]
Can you check the directory for an update log? It shouldn't have cleared your devices. Yes should remove oldest files. Check management is enabled. Check the logs.

**Comment by TheRolf** [comment]
The cameras are reconnecting fine, version 2.6.7.0 fixed the problem, thanks!

The update apparently installed the Agent into C:\Program Files\Agent\Agent, so a subfolder deeper, I attached the logs from there. [Agent.zip](https://github.com/ispysoftware/iSpy/files/4600684/Agent.zip)
Not sure if I clicked wrong, or the installer's code adds an extra "/Agent" string somewhere. But I think that explains the "lost" settings.

About the storage: storage management is on, 1500000MB is the limit, yet the folder is 1.57TB currently. What should I look for in the logs, regarding this issue?

**Comment by ispysoftware** [comment]
storage management runs every hour so it's possible to go over during that hour - in the logs looks for "storage", should be some entries.

whan you updated agent did you do it via the update button on the web interface or by running the installer again?

**Comment by TheRolf** [comment]
It has been a few hours and still not deleting the old files. I downloaded the log from the server menu on localhost, it is a json file. There is no "storage" anywhere in it. Are there supposed to be other log files somewhere?
By the way I get that this XML style log is useful because of its structure, however reading it is pretty difficult for a human. Moreover, it has entries like the one below, not specifying the camera, so it's not very informative:
{"Created":"2020-05-08T22:27:00.8835035+02:00","Entry":"Recording Closed","Type":"Message"}

**Comment by ispysoftware** [comment]
Are you using the latest version? 'cause the latest version should definitely be logging messages about storage management. Have you double checked it is enabled on the settings tab?

**Comment by TheRolf** [comment]
Sorry I didn't realise there are updates this frequently.
Now I get a 401 Unauthorized error. It only connects if I use Internal decoder instead of ffmpeg, OR if I have "username:password@" in the URL of the camera source. Previously I had the "normal" link for the camera and the credentials set in iSpy's menu, and it also worked using the ffmpeg decoder.

**Comment by ispysoftware** [comment]
It'll only use GPU if you are not recording raw and a GPU encoder is available on the system and the GPU can encode the stream (as determined by ffmpeg) and you have GPU selected on the menu option. Raw is always best if you are using ffmpeg to connect to the camera as it doesn't need to be encoded at all.

Also, previously ffmpeg wasn't available for mjpeg sources, I just added that.

**Comment by TheRolf** [comment]
I try to set up the following: iSpy deleting the oldest recordings, so that the recordings' folder is below 1.5TB, but I do not care about whether a specific camera's recordings take more space than another.
I tried setting the global storage management ON, and a limit of 1 500 000 MB, 9999999 hours, while having the cameras' individual storage managements OFF. Then something like {"Created":"2020-05-11T23:53:25.9080782+02:00","Entry":"Running storage management on c:\\folder\\","Type":"Message"} appears in the logs, but no files get deleted.
I tried putting the same values to each camera's storage management page, and same thing happens. Interestingly, the new recordings from the original folder are also kept.

Btw it should handle large values better: at first I put 999999999 to these fields, it saved successfully but every hour it attempted to delete old recordings and failed while raising date/int related exceptions.

**Comment by ispysoftware** [comment]
Hello maybe use the contact us form https://www.ispyconnect.com/contact.aspx
- this has gotten way off topic for this issue.

**Comment by ispysoftware** [comment]
I think the problem is that 1.5TB is 1500000MB which is 1572864000000 bytes
which is too big for an int32 value - i'll update Agent to use an Int64 for
the max size.

**Comment by ispysoftware** [comment]
Actually scratch that, should still be ok..  send me a message via the
website
