### ISSUE TITLE
please help me change setting to copy x264 video stream instead of re-encoding it

### ISSUE THREAD

**Issue by civilseven** [ispysoftware/iSpy#45]
All my security cameras already send x264 720p video. I use Ispy to display the video feeds on screen and record them into hour long files.

I would ultimately like to know how i can just disable encoding and to just copy the existing video stream into the output mp4 file.

With some experiments, I can achieve exactly what i want with this ffmpeg command:

ffmpeg -rtsp_flags prefer_tcp -i rtsp://192.168.1.12/11 -c copy -an -segment_time 60 -f segment -strftime 1 "%Y-%m-%d_%H-%M-%S.mp4"

more info:
re-encoding my x264 streams uses about 15% cpu per camera.  copying the video stream instead uses less than 1% cpu, seems much more efficient.  however if it just has to re-encode it, then at least make it re-encode at a similar bitrate.   *see other issue I submitted for recording issue with newer versions, where it re-encodes the video at much higher bitrate then the source.

Can we/i somehow modify the Ispy source code to accomplish this? That would honestly be the best.

Anything you can suggest/offer to have me try would be great.

Thanks,

**Comment by ispysoftware** [comment]
hello it can't just copy it as it has to extract all the frames and process
them for motion etc. Then they need to be re-encoded into a compatible
format that will play over the web.

**Comment by civilseven** [comment]
i thought maybe could somehow make it just play and record the feeds 24/7 into 1 hour files, right away to disk without any processing, like the functionality of the command but in the convince ispy

**Comment by ispysoftware** [comment]
no unfortunately not, web compatible files have different encoding settings
to raw h264 streams

**Comment by civilseven** [comment]
ok cool i understand thanks for explaining
