### ISSUE TITLE
FEATURE SUGGESTIONS: Allow Sound Card Selection For Alert Sounds And Override Volume

### ISSUE THREAD

**Issue by bvillersjr** [ispysoftware/iSpy#47]
Many thanks for the near commercial grade, open source, free software! This is a very impressive chunk of work.

I would like to be able to choose the sound card in the Alert-->Play Sound dialog so that different audible alerts/sirens for different cameras can be played on different speakers. Currently it appears to be hardcoded to the Windows Default Audio Soundcard/Speakers.

Also, in order to ensure that the alert is heard, I would like to have maybe another drop down option (I assume maybe these are plugins) that would allow me to set the Windows Volume level of a given sound card before I play a sound to it. This is especially important with Bluetooth speakers etc.. because some of them do lame things like reset their volume level to something moderate when they reconnect/disconnect or power cycle due to a power outage, etc.. Also, for those that run iSpy in the background of their one and only PC, they don't want the volume cranked all day long such that normal windows sounds and web page popup videos pierce the eardrums, but they do want to hear these important security alerts. I recently missed an alarm due to either Windows changing the sound card volume level on reboot or a Bluetooth speaker changing its volume level on reboot, both related to power outages in which ispy restarted with the PC, but I didnt know the volume changed as a result.

I have never before contributed to an open source project, so I honestly do not know the rules of the game or how to even go about helping withouot stepping on toes etc. I do however have a great deal of experience in windows sound, generating near-realtime audio streams, mixing, etc.. due to a software I developed call SimVibe. I'm more than capable of contributing quality code that meets these objectives if someone is willing to "hold my hand" so to speak with regard to getting setup to contribute and doing so without borking something for you guys.

**Comment by ispysoftware** [comment]
Hello no worries! You are of course welcome to contribute :) Any specific
questions just ask. The audio engine ispy is using is called NAudio.

Sean
