### ISSUE TITLE
Proposal: New iSpy Version (or Feature)

### ISSUE THREAD

**Issue by civilseven** [ispysoftware/iSpy#48]
Hi Sean, 

**Proposal: New Version**

"iSpy Lite" / "iSpyConnect Lite"

Create a "Lite" version of Ispy, (or some kind of special version or Fork) that plays video (like iSpy currently does) but when recording, it does not re-encode or process any frames (no motion detection capabilities, no alerts, no playing over the web) but simply copies the original ffmpeg/x264 ip camera video stream into a mp4 file.

-no processing at all of the input video, no motion detection capability, no alerts, no compatibility for playing over the web. Simply acts like a server, listens and records (copy) the video to files in set durations (ie: 1 hours files) 24/7 forever, and automatically stops and restarts recording when there's network timeout or connection interruption.

-with all the same features as iSpy, like easily adding cameras, the scheduling feature for easy recording, the user friendly interface, able to resize stream windows and position them into tiles, etc.

I think this kind of program/feature would be very useful, not just for me but many other people needing to constantly record (24/7) many camera feeds at once. A benefit of not processing the frames (no motion detection) will use very little CPU and can run on almost any type of PC and also be able to record many more streams simultaneously in their original quality. But mainly the ability to just copy the video without re-encoding.

**Alternate Proposal: New Feature**

Perhaps even incorporate this into existing iSpy.

Option to disable processing, in turn disabling possibilities for motion detection, alerts, and compatibility for playing over the web. To enable ability to just copy the video instead of re-encoding it. 

Or even keep the ability to re-encode if user chooses to copy or re-encode the video (for whatever reason, ie: needing a compatible format viewing over the web, or just wanting different codec (other then the camera default) or just smaller/larger files.

**Comments:**

RE: ffmpeg: I've tested using the following command, which works exactly how i'd like iSpy to, with great results, but the command alone isn't good enough. If there is network timeout (camera or router reboots) for any reason it stops, and never restarts.

ffmpeg -i rtsp://192.168.1.112:554/11 -c copy -an -segment_time 3600 -f segment -strftime 1 "E:\Footage\Back\%Y-%m-%d_%H-%M-%S.mp4"

I use iSpy to play/watch the video streams from my ip cameras, and also to record their video, which works great for 1-3 streams. However, too many streams (4+) is way too CPU intensive for no reason when recording streams 24/7 without needing motion detection or any alerts. 

I wish that it could just copy the video stream to a file -like that ffmpeg command can do which provides great videos in their original quality. But running that command alone has no error recovery or able to restart recording when network connection timeouts/resets, like iSpy can do. iSpy is such a great program for recording, I think this kind of version/option/feature would truly make iSpyConnect the best out there.

Thanks,

**Comment by ispysoftware** [comment]
Hello please correct me if i'm wrong but all that ffmpeg command is doing
is saving the stream to disk - it's not decoding it and playing it back
which makes it kind of pointless for surveillance.

**Comment by civilseven** [comment]
yes that's exactly it. the cameras themselves provide me with motion detection alerts, with screenshots and timestamps, to my email,  then if i want i can use that to watch the footage in question saved to my pc's hard drive- which keeps 30 days worth of each cameras video.  also i have an phone app for the cameras that allow me to see all their live feeds on my cell phone from anywhere.

**Comment by civilseven** [comment]
found some other program that is able,

**Comment by civilseven** [comment]
found some other program that seems to have this kind of feature,  but its not as good as ispy interface, and some other things
 itd be cool if ispy had this kind of option available (screenshot):
![image](https://user-images.githubusercontent.com/36014180/40591025-ae6d631c-61d7-11e8-95c0-0c6859c59aae.png)
when i have 5 ip cam streams playing and recording (copying), cpu usage is 10-14%.
in ispy 3/5 of the same streams, use 50% cpu. 
pros: it works
cons:  that app costs money, trial version for 30 days,  , it doesnt allow me to customize the save destination for each cam, same them all to the same directory.
