### ISSUE TITLE
Adding milliseconds to the filename of the video being saved

### ISSUE THREAD

**Issue by helpmelearnplease** [ispysoftware/iSpy#49]
Hello,
While saving the video file in iSPY after recording, the file name has the timestamp down to seconds, here i am trying to have it up to milliseconds. What has to be done and which part of the code has to be edited?
P.S: I want this to happen for all future recordings.

**Comment by ispysoftware** [comment]
Change the filename to add milliseconds

string filename =

$"{date.Year}-{Helper.ZeroPad(date.Month)}-{Helper.ZeroPad(date.Day)}_{Helper.ZeroPad(date.Hour)}-{Helper.ZeroPad(date.Minute)}-{Helper.ZeroPad(date.Second)}";

in camerawindow.cs

**Comment by helpmelearnplease** [comment]
Where can i find the camerawindow.cs file in the code base?

**Comment by helpmelearnplease** [comment]
@ispysoftware I made the changes and when i am trying to open the project in Visual studio 2017 , Nothing appears on screen.

**Comment by ispysoftware** [comment]
you'll need to contact visual studio support

**Comment by helpmelearnplease** [comment]
string filename =

$"{date.Year}-{Helper.ZeroPad(date.Month)}-{Helper.ZeroPad(date.Day)}_{Helper.ZeroPad(date.Hour)}-{Helper.ZeroPad(date.Minute)}-{Helper.ZeroPad(date.Second)}-{Helper.ZeroPad(date.Millisecond)}";

Is this the right format to have Milliseconds?

**Comment by ispysoftware** [comment]
yes i think so
