### ISSUE TITLE
Problem with VLC plugin

### ISSUE THREAD

**Issue by weatherwarlock** [ispysoftware/iSpy#50]
Hi. 
While use VLC plugin(from any source) have problem with Hue: see red as purple and orange as blue. People with blue faces.
For example with source "Desktop" get a ordinary picture, but through VLC plugin get incorrect.
Thtough VLC player(3.0.3) with default settings, everything displays correctly.

Thanks.
![example](https://user-images.githubusercontent.com/40421890/41646659-d9f8ada2-748d-11e8-8d3f-d95fb355f469.jpg)

**Comment by ispysoftware** [comment]
Hello this is a bug in VLC - they've switched the channels around. I think
they might have fixed it in 3.0.2 but otherwise use a 2.x version

**Comment by ispysoftware** [comment]
Hello no, it needs to be recoded so it's web compatible for mobile devices.
Next update will (hopefully) have GPU encoding.

**Comment by weatherwarlock** [comment]
You can make it an option. When the stream is already going h264/h265.
For example: 
"18 June 2018: New Xeoma 18.6.14:
Switched format for archive recordings made with direct saving to the archive without decoding from MP4 to MKV. It will reduce the processor load (thanks to no need to decode the sound stream in this case), but also increase the audio quality to the camera’s original quality;"
And on the same machine, the same devices I have 25-30% CPU usages with only 10-17% GPU usages(built-in Intel Iris Pro Graphics 580)
Well, let's wait, we'll see. Thank you.

Best regards, Sergey.
