### ISSUE TITLE
Recordings messed up with 7.0.9.0.

### ISSUE THREAD

**Issue by biship** [ispysoftware/iSpy#51]
I've run iSpy x64 for over a year, and recently upgraded to 7.0.9.0.
I record on motion detect, and now get weird errors in most of my recordings, for all of my cameras.
See attached file. Starts around 16s mark.

I know I wasn't getting this previously, and I know this worked fine on 6.9.8.0.
I can view the feed fine and without this issue when on the cameras http interface

[2_2018-06-25_16-27-26.zip](https://github.com/ispysoftware/iSpy/files/2135177/2_2018-06-25_16-27-26.zip)

Edit: I am using ffmpeg (quality 8/10) recording, and have tried with and without gpu.

**Comment by ispysoftware** [comment]
Hello can you try setting the transport to TCP when you edit the video
source properties (ffmpeg tab)

**Comment by biship** [comment]
Ok, I've switched them to TCP. I will them run for a few hours and get back to you - thanks.

**Comment by biship** [comment]
Yes, I think that's fixed it.  I was also getting some ghosting on 7.0.9.0 which I thought I might get again, but do not see that either. Thanks.
