### ISSUE TITLE
All Videos Vs. CPU usage

### ISSUE THREAD

**Issue by Urodela** [ispysoftware/iSpy#52]
Hi!
I am using version 7.0.9.0 (x64) and had an exceptionally good CPU usage of only 8% while the iSpy window is minimized and no recordings in the background (idle, waiting for movements).

But after a while I noticed that some videos were missing. I thought maybe there was a problem with motion detection but no, according to the log file there is another problem:

> Message  11:26:46  using software encoder
> Message  11:26:46  recordingstarted: Garden message: 192.168.0.1loadclip.mp4%3Foid%3D2%26ot%3D2%26fn%3D2_2018-06-28_11-26-46.mp4%26auth%3D639481bb-a86b-1c29-124c-5ddb66dc8026
> Message  11:26:53  recordingstopped: Garden message: 192.168.0.1loadclip.mp4%3Foid%3D2%26ot%3D2%26fn%3D2_2018-06-28_11-26-46.mp4%26auth%3D639481bb-a86b-1c29-124c-5ddb66dc8026
> Error  11:26:53  cam: aborted writing thread
> Message  11:27:19  using software encoder
> Message  11:27:19  recordingstarted: Garden message: 192.168.0.1loadclip.mp4%3Foid%3D2%26ot%3D2%26fn%3D2_2018-06-28_11-27-19.mp4%26auth%3D639481bb-a86b-1c29-124c-5ddb66dc8026
> Message  11:27:24  recordingstopped: Garden message: 192.168.0.1loadclip.mp4%3Foid%3D2%26ot%3D2%26fn%3D2_2018-06-28_11-27-19.mp4%26auth%3D639481bb-a86b-1c29-124c-5ddb66dc8026
> Message  11:29:29  using software encoder
> Message  11:29:30  recordingstarted: Garden message: 192.168.0.1loadclip.mp4%3Foid%3D2%26ot%3D2%26fn%3D2_2018-06-28_11-29-29.mp4%26auth%3D639481bb-a86b-1c29-124c-5ddb66dc8026
> Error  11:29:34  Garden: Das Objekt wird bereits an anderer Stelle verwendet. ( bei System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData) bei System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format) bei iSpyApplication.Realtime.MediaWriter.WriteFrame(Bitmap frame, DateTime timestamp) bei iSpyApplication.Controls.CameraWindow.WriteFrame(FrameAction fa, Double& maxAlarm, FrameAction& peakFrame) bei iSpyApplication.Controls.CameraWindow.Record())

_Translation FYI: "Das Objekt wird bereits an anderer Stelle verwendet." = "The object is already being used elsewhere." I don't know why it is in German, the settings are set to English._

Anyway, meanwhile there was an update to 7.1.1.0 (x64) which i did but the error persisted. And not only that, the CPU usage practically doubled to 16% in "idle mode" which is exactly as high as v6.8.5.0 (x86) which I used before!

Is there a way to get both? Low CPU usage and all videos? :)
greetings

PS: Both cameras are connected via USB and the microphone is cloned for both cameras and i use background modeling as detector if that's important.

**Comment by ispysoftware** [comment]
Hello yeah looking into it..
