### ISSUE TITLE
Color issue when VLC plug is used as video source

### ISSUE THREAD

**Issue by ixsander** [ispysoftware/iSpy#53]
I used VLC plug as video source for one of my webcam. The color rendered by libVLC is weird.  Blue turns to brown. Green turns to blue, etc.

I didn't add any special arguments for VLC plugin.

Thanks,

**Comment by ispysoftware** [comment]
hello use the latest version of vlc or a 2.x version- they swapped the
channels over recently

**Comment by ixsander** [comment]
I used 3.0.3 and also tried 2.2.8 windows 64bit versions. Unfortunately, both give the same result.

**Comment by ixsander** [comment]
Sorry, I wasn't aware of this issue below:
https://github.com/ispysoftware/iSpy/issues/50
This is a duplicate.
