### ISSUE TITLE
Not able to open Forms in design view

### ISSUE THREAD

**Issue by rameedev** [ispysoftware/iSpy#56]
Dear iSpyconnect team,

I have downloaded the entire code and was able to build and run the software without any hitch. I am trying to edit the MainForm in design view but the form is not opening in design mode and throwing errors.

I have attached the error screen shot when opening MainForm in design view. Not sure what is the Issue.

Please provide feedback. Thanks !!
![form_error](https://user-images.githubusercontent.com/9818433/43711453-6466650c-9990-11e8-90c4-9e9a17af60ec.png)

**Comment by ispysoftware** [comment]
you'll need to build release and debug and then try opening it again

**Comment by rameedev** [comment]
Thanks for the reviewing my question. I was opening the 64 bit solution file , tried opening solution file (iSpy.sln) and the form opened in design mode. Not sure about the weird behavior but i am fine as there is a way to edit forms in Design mode.

Thanks
