### ISSUE TITLE
ISpy crashes can no longer load XML

### ISSUE THREAD

**Issue by ijourneaux** [ispysoftware/iSpy#59]
I am using the latest version of ISpy 64bit.  Starting a couplf of updates ago, ISPY seesm to crash and and when it starts back up it complains that it can't load the XML files. THe cameras I have added are no longer listed. I have to re-add the cameras to ge the system up and running again.
I haven't been able to locate a log file with anything useful. 

What would be needed to troubleshoot.

**Comment by ispysoftware** [comment]
Check the windows event log.
Try resetting the application - start - all programs - ispy - reset ispy
