### ISSUE TITLE
iSpy -- Live Video Resolution

### ISSUE THREAD

**Issue by rameedev** [ispysoftware/iSpy#60]
Team,

We are using this software for testing against the Bosch Camera's (Dinion IP 4000i & 5000i). Both the bullet and ptz camera provide hd video when we look at them using the browser interface and also through the Bosch VMS.

We are trying to integrate this iSpy and we are facing issues with Live Video Resolution. There is a significant difference b/w the video from the browser/vms interface to what is shown in iSpy.

I have set the max frame rate to 30 , the machine being tested has enough compute power (16 GB ram & i7 processor , OS-Windows 10 Pro) Anyways we are testing with only 2 camera's.

Please let us know if anything additional needs to be setup.

Thanks

**Comment by ispysoftware** [comment]
click on video options (first tab when you edit the camera), check "no resize" at the bottom

**Comment by rameedev** [comment]
Awesome. Thanks that resolved the issue.
