### ISSUE TITLE
High CPU usage audio recording only

### ISSUE THREAD

**Issue by petesky** [ispysoftware/iSpy#61]
Dear ISPY - i record only audio (MS HD3000) but whenver trigger is reached the audio consimes a lot cpu even on i7. How is it possible to reduce it ?

**Comment by ispysoftware** [comment]
Thanks, recreated it, will fix.

**Comment by ispysoftware** [comment]
Hello this has been fixed in the latest update.

**Comment by petesky** [comment]
Thank you very much.
