### ISSUE TITLE
Pan Velocity and Speed spaces

### ISSUE THREAD

**Issue by RogerHardiman** [ispysoftware/iSpy#62]
<deleted>

**Comment by ispysoftware** [comment]
Hi Roger, why did you close this? It was a valid issue - will work on it thanks.

**Comment by RogerHardiman** [comment]
Hi. After checking the ONVIF specs there was a little more to the issue but did not have time to do a longer reply. So I closed the ticket, to re-open later.


When doing PTZ you are supposed to ask the Camera for the Velocity and Speed value ranges via GetNode or GetConfigurationOptions

Cameras return some XML with a URI and Min and Max values
Most cameras return the 'Default URI' with a Min of -1 and a Max of +1 for the Velocity.
There is a Min of 0 and a Max of 1 for the Speed.

For example here is some code taken from the RPOS Open Source ONVIF Camera Project for GetConfigurationOptions (with similar code in GetNode)

Here is the source code from the RPOS ONVIF Camera project where I generated the GetConfigurationOptions XML

    var ptzConfigurationOptions = {
          Spaces : {
              ContinuousPanTiltVelocitySpace : [{
                URI : 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
                XRange : {
                  Min : -1,
                  Max : 1
                },
                YRange : {
                  Min : -1,
                  Max : 1
                }
              }],

Cameras can change the URI from the Default Velocity Space and have a different name.
They can change the rage (eg Velocity from -20 to +20 and Speed from 0 to 20)

In that situation you have to re-calculate the X and Y speed velocity values you use in the ContinuousMove command


Same thing applies to Zoom too.

Given time I'd have a go fixing iSpy myself but I'm rather busy at the moment.

Thanks

**Comment by RogerHardiman** [comment]
That's great. Many thanks for the quick turnaround.

Will you have a beta release to try (I've not built iSpy from source before).
Currently using it on a Mac, but could switch over to a Windows machine

**Comment by ispysoftware** [comment]
i need to test it out, the problem with onvif is you fix it for one camera and it breaks it for 2 more... maybe later in the week.
