### ISSUE TITLE
Hardware Max out

### ISSUE THREAD

**Issue by rameedev** [ispysoftware/iSpy#63]
I am doing a VMS setup for one of the campuses and there will be close to 50-60 cameras(1 PTZ every 10 bullet's). 
These are latest bosch HD camera's with 2.1 megapixel resolution.

End client wants the below,
2 systems one of them with only live feed and the other with live feed and recording enabled.
Motion detect enabled at high sensitivity.
Live view to show feed at high clarity (guessing 30 fps) and no resizing set to true.

Test System.
	Windows 10 pro 64 bit
	16 GB ram.
	intel i7 4810MQ processor (4 cores).
	4 bullet camera's giving live feed at HD resolution
	
Test Scenario - 1
4 bullet camera's
Max framerate -- 30 fps
Motion detection trigger set at high sensitivity
Motion Detection Process every -- 200 ms
No Resize set to  -  true
No Recording.
CPU Usage  --  (32 - 35 %)

Test Scenario - 2
4 bullet camera's
Max framerate -- 15 fps
Motion detection trigger set at high sensitivity
Motion Detection Process every -- 1000 ms
No Resize set to  -  true
No Recording.
CPU Usage  --  (15 - 20 %)

Even if i take the 2nd scenario in case of adding 40 camera's the CPU will max out. In both the cases RAM is not at all an issue.
Not sure if i have to go for a server class system maybe like an E7 processor.

I would like to extract the max in the current system to see as many camera's as possible. 

Please advise  if there is a 'best possible' setting for framerate , motion detection sensitivity setting etc or a favourable hardware setup based on the above.

Thanks All

**Comment by ispysoftware** [comment]
hello there's an issue with jpeg feeds and cpu usage that i'm fixing right
now - not sure if it applies to you though. Best usage for 10's of cameras
cpu wise is JPEG feeds and low framerates.

**Comment by rameedev** [comment]
Did some teaking by reading the ispy guide and also other blogs on performance tuning. Below is what i did (nothing new) to get more performance.

Reduced FPS from 30 to 10-12
Removed Motion Detection for camera's that was not required to do MD.
Added specific MD zones for camera's that did MD.
Removed Suppress Noise settings.
Reduced MD sensitivity.
