### ISSUE TITLE
test cpu and gpu，could we Reduce CPU usage ？

### ISSUE THREAD

**Issue by best4s** [ispysoftware/iSpy#65]
Dear master；
     This software is great, it helps me solve many problems about  video recording, thank you!
For the sake of high-quality video files, the CPU will be very high, and the GPU acceleration will reduce about 20%, but the GPU utilization rate is only about 7%, and it seems that the GPU  is not helpful to video recording, can you make GPU do more work?
Or can you add some additional hardware to Reduce CPU usage?

**Comment by ispysoftware** [comment]
gpu usage is down to ffmpeg and your video card drivers
