### ISSUE TITLE
Hardware Performance Comparison

### ISSUE THREAD

**Issue by rameedev** [ispysoftware/iSpy#66]
Hello All,

We are testing iSpy (64 Bit Version , Release Mode) software on 2 different type of hardware and the results are a bit confusing. Please advise what could be going on....

**Load Factors**
	1) Camera Make -- Bosch IP 5000 IR.
 	2) In total there are 50 - 60 camera's running at 15 FPS.
	3) Motion Detection is set for around 15-20 % of the entire camera list
	4) No video recording , only Live view of 60 camera's in a Grid View
	
**Hardware -1**
1) Dell WorkStation with 32 GB RAM
2) Processor --  Intel i7-7700 3.60 GHz,4 cores
3) Windows 10 Pro edition , 64 Bit
4) Connected to display unit through hdmi cable

**Hardware-2**
1) Windows Server with 32 GB RAM
2) Processor -- Intel Xeon Silver 4110 , 2.0 GHz, 16 Cores
3) Software running on physical box, no virtualization done.
4) Connected to VGA display unit.

In the tests we are seeing the workstation is able to handle upto 60 camera's with cpu usage hovering b/w 50-60% whereas the server dies down with only 20-25 camera with cpu usage reaching 80-90% constantly.
 
In case of Workstation GPU is in-built so I check the box to use GPU for encoding during adding a camera but in case of the Server GPU is not available. 

Not sure if this point is making all the difference but the server has twice the number of cores so assuming it should balance out. Also the RAM usage in Server is constantly hitting 70 % but not in the case of Workstation. 

Please advise or give me your inputs what additionally can be done to run it on the Server Box.
Thanks

**Comment by rameedev** [comment]
Sorry for the delayed response, we were doing more testing to get more data. 
To answer your above question all the cores were utilized in both the hardware.

**In the server however when adding the camera->inside the Motion Detection tab value for 'Process Every' was set to 200 ms and we increased it to 2000 and also removed the suppress noise check box.** This had some effect and we were able to increase the camera's but the server is still not able to match the Workstation.

We are now dealing with a different problem in the Workstation that is very critical for us. In the workstation we have loaded about 45-50 cameras and about 9 camera's are PTZ.

We have both the Normal Grid view and Grid view for Alert to show video pop up only during a motion detection. 
Our thought process is why show all the camera feeds when we can show them only when there is a MD. **The Alerts grid view works fine for 15 minutes and then hangs.**

**The GPU that is being used is NVIDIA Quadro P600 and this is constantly at 100%** , during the Add camera process we have checked the 'Use GPU' option .

For all the camera's we have restricted the FPS to 15 and 720P but still we are seeing FPS greater than 15 (lot of the time shows b/w 20 - 25 in the camera window).

I want to summarize the issues below , please let us know if you want me to open different issues for below.

1) The Alert grid freezes after 15 minutes. From the total 50 camera's motion detection occurs simultaneously probably in around 5-10 camera's.

2) The FPS displayed in the camera regulary increases from the set limit to 15. We have also restricted this in the camera configuration.

Note --  The CPU and Memory looks fine and instead of the Alert Grid when Normal grid is used video feeds is seen for the camera's. In either of the case the GPU is constantly hitting 90- 100 %.

Please advise and thanks a lot.

**Comment by ispysoftware** [comment]
you'll need to run it from source and use the threads window in visual studio to investigate where it is hanging -  if it's because your GPU is maxing out then not much I can do about it - do you see the same behaviour on the workstation?

**Comment by rameedev** [comment]
The above behaviour is in the Workstation and not in the server. We are now looking to load test only at the Workstation level only.

**Hardware -1**
   1) Dell WorkStation with 32 GB RAM
   2) Processor -- Intel i7-7700 3.60 GHz,4 cores
   3) Windows 10 Pro edition , 64 Bit
   4) GPU -- NVIDIA Quadro P600
   4) Connected to display unit through hdmi cable.

In total 45 camera's out of which 8 are PTZ. All camera's added with 'Use GPU' checked option. (I see this is not there in latest version.)

**Issues**

1)  GPU is at full load (90-100 %) , Would it help if I re-add 50% of the camera's without checking the 'Use GPU' option so that load is transferred to CPU.

2) For the Grid view we are using the 'On Alert'  show video option. This we see is freezing after 15 minutes launching of the application. For this problem I am guessing this is because of the GPU which is in full load and hence not able to show the pop up video. So it might help to have 50% of the camera off the GPU.

Let me know your thoughts.

Thanks
