### ISSUE TITLE
PTZ Control Issue

### ISSUE THREAD

**Issue by rameedev** [ispysoftware/iSpy#67]
Hi,

I have a an old version of iSpy , downloaded sometime in September of 2018. I test and deploy the application by building the source code. The issue I am seeing is the PTZ controller.

Sometimes the PTZ controller works fine and sometimes it just hangs as in doesn't do anything. I am not sure why is this behaviour.

I am using the latest Bosch HD IP camera (Model - AUTODOME_IP_5000iIR).

I am assuming you are using Onvif commands for this and not the SDK. If you can tell me what could be the possible causes and solution that would be great. I cant seem to be signing of on this requirement.

Thanks

**Comment by ispysoftware** [comment]
have you checked the log files? (View - log files)

**Comment by rameedev** [comment]
Thanks.

I have asked for the the log files when they are exactly using the PTZ Control for ptz camera. Just to make sure what you are syaing.

1) try disconnect and reconnect the camera -- Are you referring to remove the camera from the network and re-attaching it or is it just using the option to Switch (On or Off) in iSpy ??

2) set the onvif tokens to not expire --  Is this something we can do using Onvif Device Manager or in browser settings , which option should i be looking at.

3) ispy you can set a reconnect interval to make ispy get a new token every x minutes -- Is this the option we get when selecting 'Options' under add/ edit camera

**Comment by ispysoftware** [comment]
1) no just off/on in ispy
2) try both, their web ui might not expose it
3) yes
