### ISSUE TITLE
Bundled VLC interferes with pre-existing installations (Windows)

### ISSUE THREAD

**Issue by N3X15** [ispysoftware/iSpy#68]
When installing iSpy, the bundled VLC's registry keys overwrite any pre-existing installations, to the point of confusing the windows Add/Remove Program dialogue, as well as third-party tools like chocolatey.

Possible workarounds would be not installing VLC if it's already installed, or using a separate set of registry keys.

**Comment by ispysoftware** [comment]
iSpy doesn't bundle any VLC registry keys - what keys are you talking about?

**Comment by N3X15** [comment]
The uninstall keys, specifically.  I just checked with procmon and it doesn't.  Must have been something else doing it.
