### ISSUE TITLE
GPL code in source

### ISSUE THREAD

**Issue by akutruff** [ispysoftware/iSpy#69]
Searched the code for mention of GPL.  Didn't examine the code itself, but I suggest replacing to maintain LGPL status as this would make the project GPL.

/*-------------------------------------------------------------------------------
 *	Author: Tamir Khason, 2004
 *	Email: tamir@khason.biz
 *	Web: http://www.dotnet.us/
 * 
 *	Freeware: Please do not remove this header
 *
 *	File: D.cs
 *
 *	Description:	PELCO D Protocol Implementation dot.NET Way
 * This is GPL software. Do with it as you want, but feed us back any improvements. 
 * 
 * This is a simple class to control a PELCO PTZ cameras, matrix switching systems and
 * receiver/drivers via RS422/485 'D' protocol. 
 * It supports all of the commands including UP, DOWN, IN, OUT, LEFT,
 * RIGHT, NEAR, FAR, as well as all other extended commands.  
 * 
 * To use this, you need to put a RS232->RS422 adapter on the output
 * of your desired serial port. 
 * 
 * The Pelco doesn't return ANY usefull info back, so you only really need 2-wire support 
 * (one way) communications out.
 * 
 * 
 * Version: 1.4
 * ------------------------------------------------------------------------------*/

**Comment by akutruff** [comment]
I'm reading specs and will publish an original implementation in a project on github under the MIT license.  I'll leave it for someone else to integrate into iSpy itself.  Shouldn't take me too long.

**Comment by ispysoftware** [comment]
cool thanks please let me know when you're done - do you have a pelco camera to test with?

**Comment by akutruff** [comment]
Quite welcome.  This project is amazing and am excited to start working on
it.

No I don’t, unfortunately.  I’m looking at a MIT licensed reference
implementation in Node, but beyond unit tests it’s going to be rough for me
to verify.  I was hoping someone could help me out with the verification.

**Comment by ispysoftware** [comment]
Thanks! I'll spend some time on re-writing them, shouldn't take long - i don't have a camera to test with either unfortunately

**Comment by ispysoftware** [comment]
pelco code has been re-written

**Comment by akutruff** [comment]
Well you beat me to it. Nice
