### ISSUE TITLE
Video's Blurring out

### ISSUE THREAD

**Issue by rameedev** [ispysoftware/iSpy#72]
I have an ispy deployement for around 90-100 fixed camera's split across 2 workstation with very good cpu ,decent nvidia graphics card and enough memory( > 16 GB).

The camera's are high end Bosch HD camera's , the application was working fine for last 4-5 months and suddenly now I see the video being blurred on workstation that has ispy running for around 35-40 camera's. 

I wanted to know how to trouble shoot this issue because the application worked fine for 4-5 months and only now we are seeing this issue. When checking the task manager the cpu is not crossing more than 20% , memory consumption is around 5GB , nividia consumption is around 65-75%

**Comment by ispysoftware** [comment]
usually a network issue - check for noise on the network or something taking up bandwidth. I've seen this happen before because someone plugged in a microwave near a router.
