### ISSUE TITLE
German translation buggy. How can I fix it?

### ISSUE THREAD

**Issue by syberstef** [ispysoftware/iSpy#73]
Hi,
how can I fix the german translation?
I found many issues.

Best regards

**Comment by ispysoftware** [comment]
hello, you can edit the translations in xml/translations.xml - if you improve the german please send it to me and i'll update it.

**Comment by syberstef** [comment]
Hi. Thank you for your answer.
It it possible to reload software language from this xml file?

So I can change it and check it live again?

**Comment by ispysoftware** [comment]
yes - there's the xml file in tranlsations directory which is the master copy and that's copied to 
C:\Users\User\AppData\Roaming\ispy\xml
-if you edit that file and restart ispy you should see the changes.

**Comment by syberstef** [comment]
Thank you! Today I translated all I can but there is so many english content if you switch iSpy to "German" that are currently not in your language file. I will send you screenshots or do you know this and can add it? After that I can translate all the rest.

**Comment by syberstef** [comment]
I have also found out some bugs. Most important bug is, that you can deactivate menubar but there is no way to activate it again. Please fix it.

<img width="1919" alt="Menubar" src="https://user-images.githubusercontent.com/50325809/57390481-bec6ca00-71bc-11e9-9d1b-f1042ad01710.png">

**Comment by ispysoftware** [comment]
right click on the background of ispy, click Display - File Menu. Add a screenshot if you like with your language issue as i'm not sure what you are asking.

**Comment by syberstef** [comment]
Hi. I finished translation and made screenshots. Please take a look.

Best regards

Stefan
<img width="737" alt="1" src="https://user-images.githubusercontent.com/50325809/57705563-79931400-7664-11e9-925e-6cfc75f9e49c.png">
<img width="844" alt="2" src="https://user-images.githubusercontent.com/50325809/57705564-79931400-7664-11e9-828f-136721985021.png">
<img width="593" alt="3" src="https://user-images.githubusercontent.com/50325809/57705565-7a2baa80-7664-11e9-8075-fe6753e2a684.png">
<img width="835" alt="4" src="https://user-images.githubusercontent.com/50325809/57705566-7a2baa80-7664-11e9-968b-b3f6169f4afc.png">
<img width="729" alt="5" src="https://user-images.githubusercontent.com/50325809/57705567-7a2baa80-7664-11e9-8dac-4b125557d5a3.png">
<img width="670" alt="6" src="https://user-images.githubusercontent.com/50325809/57705569-7a2baa80-7664-11e9-8040-6cc564cc6f88.png">
<img width="812" alt="7" src="https://user-images.githubusercontent.com/50325809/57705570-7a2baa80-7664-11e9-804b-cafeabaedaca.png">
<img width="956" alt="8" src="https://user-images.githubusercontent.com/50325809/57705571-7ac44100-7664-11e9-8e67-6d31faad92fc.png">
<img width="860" alt="9" src="https://user-images.githubusercontent.com/50325809/57705572-7ac44100-7664-11e9-8356-b939902668b3.png">
<img width="1661" alt="10" src="https://user-images.githubusercontent.com/50325809/57705573-7ac44100-7664-11e9-89b1-ea92960c2a40.png">
<img width="604" alt="11" src="https://user-images.githubusercontent.com/50325809/57705574-7ac44100-7664-11e9-9865-331cb5e7d5a1.png">
<img width="702" alt="12" src="https://user-images.githubusercontent.com/50325809/57705576-7ac44100-7664-11e9-8264-e7a57cf361d3.png">
<img width="988" alt="13" src="https://user-images.githubusercontent.com/50325809/57705578-7ac44100-7664-11e9-8ae4-5df5ddd399ef.png">
<img width="1920" alt="14" src="https://user-images.githubusercontent.com/50325809/57705579-7b5cd780-7664-11e9-81a3-da82d00a814d.png">
<img width="726" alt="15" src="https://user-images.githubusercontent.com/50325809/57705582-7bf56e00-7664-11e9-8081-c29edd9abdeb.png">
<img width="992" alt="16" src="https://user-images.githubusercontent.com/50325809/57705583-7bf56e00-7664-11e9-85c0-6d705ab08772.png">
<img width="1920" alt="17" src="https://user-images.githubusercontent.com/50325809/57705584-7bf56e00-7664-11e9-983e-9c7059dc8e5b.png">
<img width="736" alt="18" src="https://user-images.githubusercontent.com/50325809/57705586-7bf56e00-7664-11e9-962e-0da3581feeb5.png">
<img width="1065" alt="19" src="https://user-images.githubusercontent.com/50325809/57705588-7bf56e00-7664-11e9-95e8-17bea853ff7c.png">
<img width="796" alt="20" src="https://user-images.githubusercontent.com/50325809/57705590-7bf56e00-7664-11e9-90b2-308ca5799b15.png">
<img width="741" alt="21" src="https://user-images.githubusercontent.com/50325809/57705592-7c8e0480-7664-11e9-82dc-2a3fbd06d312.png">
<img width="651" alt="22" src="https://user-images.githubusercontent.com/50325809/57705593-7c8e0480-7664-11e9-991b-2c9d3450a61c.png">
<img width="651" alt="23" src="https://user-images.githubusercontent.com/50325809/57705594-7c8e0480-7664-11e9-941e-1fdf929629b3.png">
<img width="651" alt="24" src="https://user-images.githubusercontent.com/50325809/57705595-7c8e0480-7664-11e9-8449-0d16ff358d89.png">
<img width="844" alt="25" src="https://user-images.githubusercontent.com/50325809/57705596-7c8e0480-7664-11e9-9369-3c8e40ee2365.png">
<img width="931" alt="26" src="https://user-images.githubusercontent.com/50325809/57705598-7d269b00-7664-11e9-9021-694f323d0362.png">
<img width="953" alt="27" src="https://user-images.githubusercontent.com/50325809/57705600-7d269b00-7664-11e9-924c-7f533238b5e3.png">
<img width="886" alt="28" src="https://user-images.githubusercontent.com/50325809/57705601-7d269b00-7664-11e9-8c7f-cfc62c1dc375.png">
<img width="912" alt="29" src="https://user-images.githubusercontent.com/50325809/57705602-7d269b00-7664-11e9-881d-55ecce356621.png">
<img width="946" alt="30" src="https://user-images.githubusercontent.com/50325809/57705603-7d269b00-7664-11e9-9314-b6207aef8c1d.png">
<img width="907" alt="31" src="https://user-images.githubusercontent.com/50325809/57705604-7dbf3180-7664-11e9-9396-a3fe48a82f6a.png">
<img width="1920" alt="32" src="https://user-images.githubusercontent.com/50325809/57705605-7dbf3180-7664-11e9-84b0-86efeef2a3f5.png">
<img width="1920" alt="33" src="https://user-images.githubusercontent.com/50325809/57705606-7dbf3180-7664-11e9-9289-c23b1f4601ff.png">
<img width="1098" alt="34" src="https://user-images.githubusercontent.com/50325809/57705607-7dbf3180-7664-11e9-9fef-492386203484.png">
<img width="1920" alt="35" src="https://user-images.githubusercontent.com/50325809/57705609-7dbf3180-7664-11e9-8a45-80c5f6959e7a.png">
<img width="555" alt="36" src="https://user-images.githubusercontent.com/50325809/57705612-7e57c800-7664-11e9-86a1-7788570ccd0b.png">
<img width="1087" alt="37" src="https://user-images.githubusercontent.com/50325809/57705614-7e57c800-7664-11e9-9116-b13c5fa5ac05.png">
<img width="895" alt="38" src="https://user-images.githubusercontent.com/50325809/57705616-7e57c800-7664-11e9-9760-5c58efac2aa9.png">
[Translations.zip](https://github.com/ispysoftware/iSpy/files/3178218/Translations.zip)

**Comment by syberstef** [comment]
Hi Sean,

hope you are fine.
Did you read my post?

Best regards
Stefan

**Comment by ispysoftware** [comment]
yes i checked in some updates to github today. Some of them are too much work.
The button applies the schedule not activates it - it's working - it just applies the schedule so if something should be off it turns it off etc.
To remove a detection area just click and drag it out of the control
That box you have open with the gray background is a control to control a bigger window than is visible on the screen - try dragging the area around with the mouse.
resize resizes the video to whatever is specified in video options
gain is a multiplier - so if ispy detects 1% motion and gain is 10 then it'll register as 10% motion instead

**Comment by syberstef** [comment]
Hi Sean,

thank you for your answer.

Please use following german translations!

Zeitplan aktivieren -> Zeitplan anwenden

resize -> Auflösung ändern

Markieren Sie die zu überwachsenden Bereiche durch Klicken und Ziehen mit der Maus.
Um einzelne Bereiche zu löschen, klicken Sie den zu löschenden Bereich mit der Maus an und ziehen Sie ihn aus dem Bild.

Gain -> Empfindlichkeit verstärken

Please use following description below.

Sie können die Empfindlichkeit, mit der iSpy eine Bewegung erkennt, verstärken, in dem Sie im Bereich "Empfindlichkeit verstärken" eine höhere Zahl angeben. Wenn iSpy normalerweise eine Bewegung mit 1 % erkennt, wird diese um den Faktor, den Sie unter "Empfindlichkeit verstärken" eingetragen haben, verstärkt.

<img width="710" alt="1" src="https://user-images.githubusercontent.com/50325809/58174464-4ffa6e00-7c9e-11e9-839b-0016b63d57b2.png">

<img width="702" alt="2" src="https://user-images.githubusercontent.com/50325809/58174467-512b9b00-7c9e-11e9-961f-bee10b3f93d5.png">

**Comment by ispysoftware** [comment]
this has been updated
