### ISSUE TITLE
iSpy Portable

### ISSUE THREAD

**Issue by Urodela** [ispysoftware/iSpy#74]
Hello! It's more of a question than a issue, but i don't know where else to ask. I'm sorry if I'm at the wrong place for that.

The Question: is there a way to get iSpy completely portable? So that i have all files from the "c:\Users\USERNAME\AppData\Roaming\iSpy\" folder in the iSpy folder for example?

Thank you for your time!
Good Day!

**Comment by ispysoftware** [comment]
hello yes if you build ispy and just zip up the files from the output location you can put them wherever you like

**Comment by ispysoftware** [comment]
ispy uses Environment.SpecialFolder.ApplicationData to save files 
you might be able to set that via a batch file that runs ispy - i'm not sure, haven't tried it myself.

https://stackoverflow.com/questions/14203749/how-to-set-config-output-to-special-folder-localapplicationdata

**Comment by Urodela** [comment]
Thank you for bringing this to my attention... It worked. I will test it for a few days, see if there are any problems.

Here is the content of the batch file:

```
set ISPYPORTDIR=%~dp0
if not "" == "%ISPYPORTDIR%" if #%ISPYPORTDIR:~-1%# == #\# set ISPYPORTDIR=%ISPYPORTDIR:~0,-1%
set USERPROFILE=%ISPYPORTDIR%\userdata
set APPDATA=%ISPYPORTDIR%\userdata\AppData\Roaming>nul
set ALLUSERSPROFILE=%ISPYPORTDIR%\userdata\AppData\Roaming>nul
set PROGRAMDATA=%ISPYPORTDIR%\userdata\AppData\Roaming>nul
start "" /D"%ISPYPORTDIR%\" /belownormal /affinity FC "ispy.exe"
```

With the exception of /belownormal, everything is running as expected. Does iSpy force /normal on startup maybe? Well, it works for now anyway. Maybe an official "portable" version is an idea for the future?

Okay, thanks for the helpful hint!
Have a nice day!

**Comment by ispysoftware** [comment]
our agent app is fully portable - http://www.ispyconnect.com/download-agent.aspx

**Comment by ispysoftware** [comment]
our agent app is fully portable -
http://www.ispyconnect.com/download-agent.aspx

**Comment by wonderwareguru** [comment]
> our agent app is fully portable - http://www.ispyconnect.com/download-agent.aspx

Hi Sean, you stated that iSpy is portable, however, it requires admin rights to setup. Do we first setup iSpy on a machine with admin rights, and then move it to a thumb drive? Thanks

**Comment by ispysoftware** [comment]
instead of installing it just downloading and running the installer just download the files and run it manually
you can get the latest file location from
https://www.ispyconnect.com/api/Agent/DownloadLocation4?platform=Windows64&fromVersion=0
