### ISSUE TITLE
Ispy usage issues

### ISSUE THREAD

**Issue by jpanni** [ispysoftware/iSpy#75]
hello teacher !
     Thank you very much for providing the ispy software, we found that in the process of using ispy card frame, bolt reconnection is serious,  now we are recorded three road high-definition video (1920 * 1080), according to frame number and record the frame number is 10 frames, recording the CPU usage rate was 23%, the computer I/O read/write speed is only 1 ~ 2 m/S, started recording is also normal, The recording works well at first,  and then it gets delayed,  then followed by serious when can appear offline for reconnection, can you help to solve?
     Our boss will be on a business trip to Australia in the near future. Is it convenient to see you?  we hope to reach some business cooperation with you, could you please leave your contact information? 
     Our email address is xxxxxxxxxxx@163.com.

**Comment by ispysoftware** [comment]
hello, it depends where the bottleneck is - click on the performance tips button in bottom left of ispy

**Comment by jpanni** [comment]
Hello, teacher!
    My test machine is the main board of the server, and the CPU used is e5-2630. Compared with desktop computer (i5-4440), it seems that there is a certain relationship with the memory size of the graphics card.
    The video card memory of the test machine (e5-2630) is 16M, and the 3-way hd video recording is disconnected and reconnected. The desktop computer (i5-4440) has a memory of 384M, which can record the 3-way hd picture very well.
    I also have enough memory, is ispy related to the memory of the video card? I have no independent video card here, no actual test.
