### ISSUE TITLE
iSpy crashes, when I check "use GPU" for RTSP stream decoding

### ISSUE THREAD

**Issue by greentree20131221** [ispysoftware/iSpy#76]
Dear Sir!
iSpy is great! It is really the best VMS open source. 
Everytime I use this sofware, I'm grateful to you.
I have many IP cameras, so I want iSpy to decode and record video streams from about half of them, using GPU.
But, if I check "use GPU" and press "Test", it crashes every time after 2~3 min.
I tested it against NVIDIA GT 720, GTX 960, Intel Graphics UHD 630.
And if I check "use GPU" in a PC with multiple GPUs, which GPU is used?
Please advise me.
Thanks.
(My gmail address is greentree20131221@gmail.com.)

**Comment by ispysoftware** [comment]
you'll need to check the event log and try and get some info to debug it. ispy uses ffmpeg which does the GPU stuff and there are a lot of layers involved with drivers etc. GPU selection hasn't been added yet.

**Comment by greentree20131221** [comment]
Thank you very much for your speedy reply.

My operations are as follows.
1. Delete the previous all setting files(C:\Users\Administrator\AppData\Roaming\iSpy\*.*)
2. Open iSpy.
3. In iSpy, Select Add/IP camera/FFMPEG(H264)/URL.
4. Type the IP camera RTSP strea URL.
rtsp://xxx.xxx.xxx.178:95/user=xxxxx&password=xxxxx&channel=2&stream=0.sdp
5. Select RTSP Mode to "Audo", check "use GPU".
6. Press "OK".
7. Then, iSpy freezes for about 10s, and restarts.

I collected log files from 3 PCs.
But they are a little different.
**A. Intel UHD 630**
**Exception:**	8:24:37 AM	Server: Only one usage of each socket address (protocol/network address/port) is normally permitted
Only one usage of each socket address (protocol/network address/port) is normally permitted
System
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.Sockets.Socket.Bind(EndPoint localEP) at System.Net.Sockets.TcpListener.Start(Int32 backlog) at iSpyApplication.Server.LocalServer.StartServer()
**B. NVIDIA GT 720+Intel HD 530, GTX 960**
**Message**	9:42:53 AM	Camera 0: Using hardware decoder: AV_HWDEVICE_TYPE_DXVA2

I attached 3 log files.

Also, I'll send the rtsp stream url to your mail so that you can test it in your PC.

Thanks.
[Logs.zip](https://github.com/ispysoftware/iSpy/files/3312528/Logs.zip)

**Comment by greentree20131221** [comment]
Dear Sir.
I tested this RTSP stream URL.
rtsp://
50.79.235.178:95/user=admin&password=123456password&channel=2&stream=0.sdp
Thanks.
Best Regards,
Green Tree.
