### ISSUE TITLE
Cannot change MotionDetector because Camera is null

### ISSUE THREAD

**Issue by mjbedford2017** [ispysoftware/iSpy#77]
Hello. Love the software. I have been evaluating the project using the source and noticed a potential bug. During testing, I am using video files as my source instead of connecting to a live camera. I don't know if this has something to do with it. Here is how to reproduce. 

1. Add new camera, select the video file.
2. The options window will automatically pop up for the first time. 
3. The event for the motion detector drop down, DdlMovementDetectorSelectedIndexChanged1  (Line 1414 of AddCamera.cs) but the call to SetDetector will never get called because the test before this checks if the currently selected value in the dropdown is different than the stored or configured detector type. In most cases it is not different yet because I did not have a chance to change it. So, SetDetector at line 1425 will never get called. 
4. After this first time the settings window pops up and the DdlMovementDetectorSelectedIndexChanged1 get called, the Disable method (line 4125 of CameraWindow.cs) gets called and the very last line of this method sets the Camera property to null this time around. 
5. Now, if you do try to change the motion detector type by using the drop down, DdlMovementDetectorSelectedIndexChanged1 will still get called but the first test it does at line 1420 checks to see if CameraControl.Camera != null. However, it is now null because step 4 set it to null. Therefore, you can never change and apply the detector and SetDetector still does not ever get called. 

Can you look in to this?

Thanks!

**Comment by ispysoftware** [comment]
hello sorry for the delay. I'll push an update to git - can you check it and let me know if it resolves your issue?

**Comment by mjbedford2017** [comment]
Hello. Yes, that seems to have done it. Thank you!
