### ISSUE TITLE
VLC playback is dropping too many frames

### ISSUE THREAD

**Issue by mjbedford2017** [ispysoftware/iSpy#79]
Hello, ultimately, I will be using iSpy to connect to real cameras (Axis H.264) cameras. However, while testing, I am using video files that were recorded from these very same cameras. 

I have written some code that does object detection using machine learning and object tracking using OpenCv trackers (in this case, I am using EmguCv for the .Net wrapper). 

The tracker is somewhat sensitive to missed or dropped frames as it needs to predict the movement and see if a subsequent frames object fits the prediction to continue tracking. 

I have a test app that I have written that uses OpenCv (EmguCv) VideoCapture class to read the video file and then the .QueryFrame method in a loop to pull in new frames one by one and process them as explained above. The test app works perfectly. 

However, I have tried to take the exact same code and make it a plugin for iSpy and when I do this, I get different behavior. The tracker keeps dropping out and having to re-detect and track again later. Also, I can see in the video that frames seem to skip. Because of these skipped frames, this is what is causing the tracker to fail. When I load the video directly into VLC, i do see in the log that frames are being skipped because of timing issues. 

This does not seem to happen when I use OpenCV for VideoCapture though as everything works perfectly. 

I have tried playing with the VLC buffer size which you have defaulted to 3 seconds. I like the idea of a buffer in general because if processing temporarily slows down, I don't want to miss frames, I just want to process them a little later than they came in. However, changing this value from 0 seconds to 15 seconds, did not help. Any other settings to try that might help?

Is there some fundamental issue with nVLC? I noticed it is quite old and not maintained any longer. 

Would it be possible to add an OpenCV component and option to use for video capture and processing?

**Comment by ispysoftware** [comment]
check the framerate limiters when you edit the camera  (first tab)- that can cause frames to be dropped - set that to like 50 or something

**Comment by mjbedford2017** [comment]
Thank you for the reply. I had tried that and just to be sure, tried it again. It is the maximum framerate on the first tab, I set that to 60 and I still have the issue. 

While waiting to hear from you, I downloaded the source code and create a very rough class that implements IVideoSource and made it look similar to VLCStream except I switched it around to use OpenCV VideoCapture. When I did this and use this class, the problem goes away. So, while it could be that OpenCV does a better job of decoding H.264 frames, there are two other things that can be causing the issue. 

1. My object detection sometimes bogs down and cannot run at the full frame rate. I thought that with the object lock on the NewFrame event handler and the video queue being used, the system could handle this by simply queuing up the frames and still processing them serially while not dropping any. For my system and most systems that might bog down from time to time, it is important that this happens. However, maybe something is broken and instead of queuing up the frames, it drops them?
2. In my OpenCV implementation that I create tonight, I am not using the ConcurrentQueue by enqueue and dequeue out to the NewFrame event handler. While I think this is important long term for the reasons mentioned above, for now I am simply Invoking the event directly, without running through the queue first. 

Like I said, when doing the above, the OpenCV implementation works perfectly. It is smooth and doesn't appear to drop frames so the object tracking works perfectly. If I run VLC or FFMPEG on the same exact video file, even with max frame rate set high, there are issues. 

Here is what I did for now to get the OpenCV stream class working. Again, it is temporary. I took a copy of the VLCStream class. In the WorkerThread method, I instantiate an EmguCV VideoCapture variable with the source video file. Then, I changed the EventManager like this:

`       private ConcurrentQueue<Bitmap> _videoQueue;
        private ConcurrentQueue<byte[]> _audioQueue;
        private bool useQueue = false;

        private void EventManager()
        {
            Bitmap frame;
            while (!_abort.WaitOne(5) && !MainForm.ShuttingDown)
            {
                try
                {
                    var da = DataAvailable;
                    var nf = NewFrame;

                    if(useQueue)
                    {
                        if (_videoQueue.TryDequeue(out frame))
                        {
                            if (frame != null)
                            {
                                using (var b = (Bitmap)frame.Clone())
                                {
                                    //new frame
                                    nf?.Invoke(this, new NewFrameEventArgs(b));
                                }
                            }
                        }
                    }
                    else
                    {
                        //Read our new OpenCv frame
                        var newFrame = videoCapture.QueryFrame();

                        if(newFrame != null)
                        {
                            //Post it!
                            var frameArgs = new NewFrameEventArgs(newFrame.Bitmap, newFrame.ToImage<Bgr, byte>());
                            nf?.Invoke(this, frameArgs);
                        }
                        //Delay on frame rate
                        var frameRate = _source.settings.maxframerate;

                        var framePause = Convert.ToInt32(1000 / frameRate);
                        _pause.WaitOne(framePause);
                    }



                    byte[] audio;
                    if (!_audioQueue.TryDequeue(out audio)) continue;
                    da?.Invoke(this, new DataAvailableEventArgs(audio));

                    var sampleBuffer = new float[audio.Length];
                    _sampleChannel.Read(sampleBuffer, 0, audio.Length);

                    _waveProvider.AddSamples(audio, 0, audio.Length);

                    if (WaveOutProvider != null && Listening)
                    {
                        WaveOutProvider.AddSamples(audio, 0, audio.Length);
                    }
                }
                catch (Exception ex)
                {
                    Logger.LogException(ex, "OpenCv");
                }
            }
            try
            {
                while (_videoQueue != null && _videoQueue.TryDequeue(out frame))
                {
                    frame?.Dispose();
                }
            }
            catch
            {
                // ignored
            }
        }`

**Comment by ispysoftware** [comment]
it's probably dropping frames from the check to ShouldEmitFrame in videobase.cs - that does a bunch of stuff with averaging framerates and quite possibly has a bug in it. You could try putting a debug.writeline on the shouldemitframe check to see if it's dropping them there.

**Comment by ispysoftware** [comment]
.. There's a setting in main settings to set the max CPU - if your code is using high CPU ispy will drop frames to bring it down - try setting your CPU limit to 100 (see ThrottleFramerate in videobase.cs)

**Comment by mjbedford2017** [comment]
Hello again. Both good thoughts. I know it is not the CPU usage though. I happens all the time, consistently, even when only playing one video and CPU usage at 9%. 

With that said, I tried your other theory. You are right, ShouldEmitFrame is dropping the frames quite often. Here is what I did to log it in the debug window.

`        private void FrameCallback(Bitmap frame)
        {
            var nf = NewFrame;
            if (!ShouldEmitFrame)
                Debug.WriteLine("----------No frame emitted---------");
            if (nf == null || _abort.WaitOne(0) || !ShouldEmitFrame)
            {
                frame.Dispose();
                return;
            }
            _videoQueue.Enqueue((Bitmap)frame.Clone());
        }`

And when I did that, I got this in the output window: 

> Fli fps: 12
----------No frame emitted---------
Boxes Count: 0. 
----------No frame emitted---------
New Image Event fps: 14
Fli fps: 14
----------No frame emitted---------
Boxes Count: 0. 
----------No frame emitted---------
Boxes Count: 0. 
Fli fps: 12
New Image Event fps: 13
----------No frame emitted---------
----------No frame emitted---------
Boxes Count: 1. 
Box Size: 510x98y|130w152h. 
Blobs Count: 0. 
Blob found with no match. Creating blob with new Id: 4 
----------No frame emitted---------
Fli fps: 13
----------No frame emitted---------

You can see, it happens pretty often. Now I have to figure out why.

**Comment by mjbedford2017** [comment]
I have a theory but I need you to confirm since you wrote the code. From what it looks like, ShouldEmitFrames makes a decision on if a frame should be used based on the frame rate. If it feels that it is delivering frames faster than the desired frame rate, it will drop them in order to achieve the desired frame rate. 

One issue with this approach, besides dropping and missing frames, is that I noticed VLC tends to play the video back faster than it should (like it is 2x or 4x speed). For example, my video was recorded at 15fps which as you know is a bit on the slow side but video should still look like it is naturally moving to the eye. However, when I play this video in VLC, it moves very fast. 

If for this reason or many other reasons, the video goes above my setting (which I have set to match the fps of the video, 15) it will drop frames. 

The difference with how OpenCv does it, as I implemented it, is that the software must query for the next frame and so I added a delay, which is set to the desired frame rate, in between querying for a new frame. This gets me the desired frame rate, without dropping any. 

So, if my theories are all correct, what is the best way to solve this problem?

**Comment by ispysoftware** [comment]
add:

if (RealFramerate < TargetFrameRate) return true;

to line 68 of videobase.cs - set the max framerate high. Let me know if that helps.

**Comment by mjbedford2017** [comment]
That seems to have fixed the issue of dropping frames in general. I don't get the issue where ShouldEmitFrame is false and I am not logging that frames are not being emitted. So, this is good and I will mark as closed (assuming you are going to permanently fix it in the repository)?

**Comment by ispysoftware** [comment]
yep will do
