### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by SeriosCem** [ispysoftware/iSpy#80]
Good day sean tearney, I get an error when compiling the project. I installed everything exactly as in the instructions for the git hub. And wix tools and turned on the recovery of NuGet packages. project. But errors are not only for this. In visual studio 2015 I write that there is no namespace, etc.
i give you some screenshots.
[http://piccy.info/view3/13295441/aaa902db329aef1b3ad8c29b7b720f12/](url)
[http://piccy.info/view3/13295442/e20fc8203743bb1ced1a8fdcf49a43ac/](url)
[http://piccy.info/view3/13295443/598abc228820fedcedd5a2465a0ac0b3/](url)

**I really hope that you tell me what the problem is.
Visual Studio 2015 : Windows 7 x64**

**Comment by SeriosCem** [comment]
### Another problem with the namespace


                 `using (var ar = new AudioReader(newFormat.SampleRate, newFormat.Channels))
                        {
                            ar.ReadSamples(fileName, (b, c) =>
                            {
                                waveStream.Write(b, 0, c);
                                return waveStream.Length >= BUFFER_LIMIT;
                            });
                        }`

**Comment by SeriosCem** [comment]
### If I delete this line, another error appears.

Error exiting the "xcopy" command C: \ BySec \ iSpy \ dlls \ x64 \ *. * "" C: \ BySec \ iSpy \ bin \ x64 \ Debug \ "/ Y
call "D: \ projects \ ispy \ signing \ iSpy64.bat"

**Comment by SeriosCem** [comment]
My adress mail - cemen200395@gmail.com
Telegram: @Sirendium
Skype - +380501087576

**Comment by SeriosCem** [comment]
Video - https://youtu.be/6KRHoUZ_0Zk

**Comment by ispysoftware** [comment]
you need to remove the signing post build event as the code signing isn't part of the open source project. Leave the xcopy command in there.

**Comment by SeriosCem** [comment]
I do not understand you. What specifically should I delete?

**Comment by SeriosCem** [comment]
Everything worked out! Thank you

**Comment by xsamir** [comment]
> Everything worked out! Thank you

How did u fixed the problem?
Is there's a certain file to be deleted?
