### ISSUE TITLE
I can't open the main window in design mode.

### ISSUE THREAD

**Issue by SeriosCem** [ispysoftware/iSpy#81]
I can't open the main window in design mode.
Please help me.

**Comment by SeriosCem** [comment]
<a href="http://piccy.info/view3/13298204/0de4d98d130d894143ab977bf1b283b8/1200/" target="_blank"><img src="http://i.piccy.info/i9/f0a0141cd75cdb93a98756fbf661526a/1563785032/54957/1328814/1111_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-07-22-08-43/i9-13298204/800x330-r" target="_blank"><img src="http://i.piccy.info/a3/2019-07-22-08-43/i9-13298204/800x330-r/i.gif" alt="" border="0" /></a>

**Comment by SeriosCem** [comment]
### Also bootstrap is not compiled.

<a href="http://piccy.info/view3/13298207/1c389f684eee7ed1af28af04554e208c/1200/" target="_blank"><img src="http://i.piccy.info/i9/1e04d67ac413baf92d2e3aefbcdb4ac0/1563785115/42396/1328814/1111_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-07-22-08-45/i9-13298207/800x230-r" target="_blank"><img src="http://i.piccy.info/a3/2019-07-22-08-45/i9-13298207/800x230-r/i.gif" alt="" border="0" /></a>

**Comment by SeriosCem** [comment]
I open ispy64
Windows 7 x64 bit
Visual Studio 2015

**Comment by ispysoftware** [comment]
You need to build it for debug first. I have the same issue sometimes and use the designer for 32 bit project instead.  They share the same code.
The bootstrap files are all included in the solution. Possibly using absolute paths that need to be converted to relative for your PC.

**Comment by SeriosCem** [comment]
Build in debug mode?

**Comment by SeriosCem** [comment]
How to convert these ways?

**Comment by SeriosCem** [comment]
32 bit project does not start.

**Comment by SeriosCem** [comment]
C: \ iSpyMonitor \ iSpyMonitor.csproj: ошибка: не удалось загрузить файл проекта. Не удалось найти часть пути "C: \ iSpyMonitor \ iSpyMonitor.csproj". C: \ iSpyMonitor \ iSpyMonitor.csproj

**Comment by SeriosCem** [comment]
C: \ iSpyMonitor \ iSpyMonitor.csproj: error: the project file could not be loaded. Could not find part of the path "C: \ iSpyMonitor \ iSpyMonitor.csproj". C: \ iSpyMonitor \ iSpyMonitor.csproj

**Comment by SeriosCem** [comment]
But when I open a 64 bit project, this does not happen.

**Comment by SeriosCem** [comment]
Do you have Skype? I could run a screencast.

**Comment by SeriosCem** [comment]
My skype - +380501087576
Call at any time. I work almost without interruptions and sleep.

**Comment by ispysoftware** [comment]
iSpyMonitor isn't part of the source code - the pre built executable is in the /Supporting folder

**Comment by SeriosCem** [comment]
And what should be done with this file?

**Comment by ispysoftware** [comment]
remove the reference to the ispymonitor project
you dont need to do anything with that file - it's packaged into the setup project

**Comment by SeriosCem** [comment]
Tell me how to delete the link. And will it help?At the moment, the most important thing for me is to open the main window.

**Comment by SeriosCem** [comment]
The secondary task is of course the bootstrap.

**Comment by SeriosCem** [comment]
My boss is interested in whether we can get a license for the application. He is not going to sell it, all for personal purposes.

**Comment by SeriosCem** [comment]
He will also ask you to send the source code for the plugins.

**Comment by SeriosCem** [comment]
Most likely he is willing to pay, if required.

**Comment by SeriosCem** [comment]
Error "sgen.exe" ended with code 1. iSpy64

**Comment by SeriosCem** [comment]
This error appears when I try to compile in x86

**Comment by SeriosCem** [comment]
I solved the problem with the discovery. But the bootstrap is still with errors.

**Comment by SeriosCem** [comment]
How to change the text of the form?

**Comment by ispysoftware** [comment]
@SeriosCem see XML/translations.xml

**Comment by SeriosCem** [comment]
Main window how to change text?

**Comment by SeriosCem** [comment]
I opened this file, I can not find ...

**Comment by ispysoftware** [comment]
the app uses translations from the xml/translations.xml file - to change the text you need to modify the corresponding translation. To find what translation you need to change see the RenderResources() method in mainform.cs

**Comment by SeriosCem** [comment]
Thank you very much.
Do you have plugin source code?

**Comment by SeriosCem** [comment]
Or to create a plug-in some constructor.

**Comment by SeriosCem** [comment]
Our company is ready to pay the money.

**Comment by SeriosCem** [comment]
I need to change the name of the text in the form.Because when I change in the designer it remains - "iSpy and version"

**Comment by SeriosCem** [comment]
<a href="http://piccy.info/view3/13303109/e012bea6f59eb1bb12a31cbc4319538e/" target="_blank"><img src="http://i.piccy.info/i9/199394b17985dfae592537b81b41faa3/1564025006/3798/1328814/2.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-07-25-03-23/i9-13303109/101x29-r" target="_blank"><img src="http://i.piccy.info/a3/2019-07-25-03-23/i9-13303109/101x29-r/i.gif" alt="" border="0" /></a>

**Comment by SeriosCem** [comment]
Already suffer with this problem .....

**Comment by ispysoftware** [comment]
see SetTitle in helper.cs

**Comment by SeriosCem** [comment]
How to compile the installer?

**Comment by SeriosCem** [comment]
How to change the text label in the form of settings?

**Comment by SeriosCem** [comment]
I changed the name of the exe file. And so there will be such errors.

<a href="http://piccy.info/view3/13307452/6e5a24f9ae1134aeb5e24cad60314800/1200/" target="_blank"><img src="http://i.piccy.info/i9/9930e9b6e50cbcbf092bf22cfa6fe66e/1564257507/27101/1328814/1_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2019-07-27-19-58/i9-13307452/800x185-r" target="_blank"><img src="http://i.piccy.info/a3/2019-07-27-19-58/i9-13307452/800x185-r/i.gif" alt="" border="0" /></a>

**Comment by SeriosCem** [comment]
Changed the icon and file name.

**Comment by ispysoftware** [comment]
If this is for private use only why are you changing the filename and icons? You know this is copyrighted right?

**Comment by SeriosCem** [comment]
We want to buy a license from you. Let's discuss it on Skype.

**Comment by SeriosCem** [comment]
+380501087576

**Comment by SeriosCem** [comment]
This is for personal use.

**Comment by SeriosCem** [comment]
I need a program for my college. How much will a license cost?

**Comment by SeriosCem** [comment]
I use the program for programming Olympiad.In my college, we all present projects; my project is our own VMS.
