### ISSUE TITLE
MC400L PTZ Control not working

### ISSUE THREAD

**Issue by andi448** [ispysoftware/iSpy#84]
Hello guys,

I've got trouble to get my PTZ control working with my MC400L dome camera.
The camera model is set to ::ONVIF because I can't find anything near MC400L.

Do you have any hints for me?

**Comment by ispysoftware** [comment]
Is your camera onvif compatible?
see adding support for unlisted cameras here:
https://www.ispyconnect.com/userguide-ptz.aspx

**Comment by andi448** [comment]
The web interface listed ONVIF on port 80 without authentication and I can see a stream, but can't control and use the PTZ.
Thanks I'll look into it.

**Comment by andi448** [comment]
Is it really needed to add the camera via JPEG, MPEG or VLC? Or does ONVIF work also?

The next problem is, that I can't control my cam via the web interface because it's crap and not implemented. It was possible via a Chinese app but that's not available anymore. That's why I wanted to add it to your software. 

Is there any chance to get the control commands out of the camera?

**Comment by ispysoftware** [comment]
try using onvifdm - if that can control ptz on your camera then ispy should be able to 

https://sourceforge.net/projects/onvifdm/

**Comment by andi448** [comment]
For pity that's what I tried originally and it also isn't working.

**Comment by ispysoftware** [comment]
You'd need to ask the manufacturer

**Comment by andi448** [comment]
That's the next problem, there is no real manufacturer.
I even don't have any name on the camera, nor is anything noted in the web interface...

Is there are way to get into the system files to get these commands by myself?

**Comment by ispysoftware** [comment]
i'd start by trying out the existing profiles in the PTZ menu when you edit the camera - make sure you set your username/ password. One of them is likely to work.

**Comment by andi448** [comment]
Thanks for your advice.
If I added my camera via ONVIF, do I have to add in the PTZ menu (...) also the URL and port or just username and password?

I just want to get sure, that everything is configured correctly to test every config.

**Comment by ispysoftware** [comment]
it should auto detect the url but put the username and password in there

**Comment by andi448** [comment]
Alright, after testing every single available camera model in the list, I didn't get it to work.

But I did a lot of research and found a new firmware version and now everything works fine with odm and iSpy.

Thank you very much though.
