### ISSUE TITLE
Random/Intermittent error loading FFMPEG dll after running for some time

### ISSUE THREAD

**Issue by mjbedford2017** [ispysoftware/iSpy#86]
Hello. 

I noticed an error that comes up intermittently and at times after a day or several days of running properly. I have iSpy x64 v7.2.2.0 installed and running with 6 cameras. Like I mentioned, when I start it, it will come up just fine and show all cameras, no errors in the logs. 

Then, at some random period that can be days later, I lose ALL 6 cameras and they all log this error:

Error	12:02:31 AM	L3-1: Unable to load DLL 'avutil.56': The specified module could not be found. ( at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName) at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name) at System.Collections.Generic.List`1.ForEach(Action`1 action) at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName) at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name) at System.Collections.Generic.List`1.ForEach(Action`1 action) at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName) at FFmpeg.AutoGen.ffmpeg.<>c__DisplayClass5_0.<.cctor>b__0(String name) at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__5_274(String short_name, String filename, String mime_type) at iSpyApplication.Realtime.MediaWriter.Open(String fileName, Int32 width, Int32 height, AVCodecID videoCodec, Int32 framerate, AVCodecID audioCodec, DateTime created, Int32 crf) in C:\Dev\iSpy\Realtime\MediaWriter.cs:line 138 at iSpyApplication.Controls.CameraWindow.Record() in C:\Dev\iSpy\Controls\CameraWindow.cs:line 3277)

What could cause this to happen to all 6 cameras at the same time at some random point? The program then will hang. If I restart it, everything comes back up again just fine, no errors until the next time it intermittently does this again. 

Thanks!

Mike

**Comment by ispysoftware** [comment]
Hi Mike, have you run scan disk to check for errors? That error is coming
from the file system basically saying it can't load the dll - maybe there
is an issue with the disk or it's gone to sleep mode or power settings are
shutting down the drive?
