### ISSUE TITLE
Ftp timestamp is not the same of start time video recorded

### ISSUE THREAD

**Issue by Classsic** [ispysoftware/iSpy#87]
Hi, I try to upload the videos to sftp server, with timestamp like this:
`cam1_{0:yyyy-MM-dd}_{0:HH-mm-ss}.mp4`
But, the file upload have some seconds of difference compare to the video file saved on localrecord ( a few more seconds).
Is there a way to get the start time of video,and no the timestamp of is  uploaded?
thanks.

**Comment by ispysoftware** [comment]
I've checked in a fix for this (add buffer time to recording timestamp)

**Comment by Classsic** [comment]
I’m sorry but  don’t understand. You will fixed on future release?
