### ISSUE TITLE
iSpy will crash when resizing windows pretty consistently

### ISSUE THREAD

**Issue by mjbedford2017** [ispysoftware/iSpy#90]
Hello, I have seven cameras running in iSpy. I need to re-arrange my windows so I tend to move them around and resize them. I have noticed that iSpy will pretty consistently crash when I am resizing a window to a pretty small size. So, to duplicate, have several camera windows and resize one of them by grabbing and dragging the bottom right corner to make it smaller. Keep making it smaller and smaller and it will crash at some point. 

Also, to note for re-producing the error, it seems to be a drawing error with GDI. I know this can be graphics related. I am running one NVidia RTX2060 card with the latest driver version. It is at all defaults, I have not adjusted or tweaked any of my graphics settings (nor am I overclocking or anything like that). 

When it crashes, iSpy does not log the crash. The only thing is there is a log in Windows event viewer and here is the log:

Application: ispy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Drawing.SafeNativeMethods+Gdip.GdipDrawImageRectI(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, Int32, Int32, Int32, Int32)
   at System.Drawing.Graphics.DrawImage(System.Drawing.Image, Int32, Int32, Int32, Int32)
   at iSpyApplication.Controls.CameraWindow.OnPaint(System.Windows.Forms.PaintEventArgs)
   at System.Windows.Forms.Control.PaintWithErrorHandling(System.Windows.Forms.PaintEventArgs, Int16)
   at System.Windows.Forms.Control.WmPaint(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by mjbedford2017** [comment]
Scratch that....not just affected by resizing. Also just happened to me when I was moving windows around and started to click on the edit gear in one of the camera windows. It crashed again for that. Seems to be the same error in event viewer. Pasted below. If I just leave iSpy alone, don't touch the camera windows, it does not happen.

Application: ispy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Drawing.SafeNativeMethods+Gdip.GdipDrawImageRectI(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, Int32, Int32, Int32, Int32)
   at System.Drawing.Graphics.DrawImage(System.Drawing.Image, Int32, Int32, Int32, Int32)
   at iSpyApplication.Controls.CameraWindow.OnPaint(System.Windows.Forms.PaintEventArgs)
   at System.Windows.Forms.Control.PaintWithErrorHandling(System.Windows.Forms.PaintEventArgs, Int16)
   at System.Windows.Forms.Control.WmPaint(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by ispysoftware** [comment]
haven't been able to reproduce this - I have a 2080Ti - it could be driver related or something to do with system load.  Are you able to run iSpy from source code?

**Comment by mjbedford2017** [comment]
I can run from source code, yes. Are you suggesting that I do that so I can see more details about the crash? For this system, I am running the latest version that I downloaded just a few days ago from your website and I actually installed the application. 

My layout was set to having all of the camera windows (all 7 of them) in the main view. I was then dragging them or moving them around to arrange them. So, it could be related to load I guess.

It could be graphics related though I have the latest version of the driver. I had posted another question to you about minimizing the windows. I am now doing the auto layout and minimize. Yes, that does work just fine. I will be curious to see if the problem goes away when I have all windows minimized and just try to move around or resize one of them at a time.

Also, I have a thought. Could this be related to something my plugin is doing? It is drawing on the image it receives from ProcessFrame and returning it. I don't see how moving the camera window or resizing it would affect the plugin but I guess maybe?

My CPU runs at about 20% average based on what I am doing. I am more inclined to think it is load with all of the camera windows open. I am going to try to minimize all but one and see if this happens when only working with one at a time.

**Comment by ispysoftware** [comment]
Yes it could be something to do with the plugin

**Comment by ispysoftware** [comment]
if you run it from source, check that the rectangle being passed into the draw method is valid - possibly some layout logic is resulting in NaN values somewhere and that's what's causing the issue.

**Comment by mjbedford2017** [comment]
Hello Sean, thank you for the prompt replies and assistance. Can you give me just a tad bit more to go off of? I have two questions/comments to help me find the root cause besides what you have already given me. 
1. I don't doubt that it could be my plugin, though it is odd that it only seems to happen when resizing or dragging the camera windows. For more on this, I left iSpy running today for 12 hours and counting and no crash at all. But, I did not touch it either. As soon as I started moving camera windows around, it crashed within 30 seconds. So, if it is the plugin, I would assume this is because iSpy or something is doing something that it shouldn't be doing to the bitmap while the camera window is being altered? Is there some protection I can add in the "ProcessFrame" method that iSpy calls to hand me a Bitmap?

2. In your last comment, what rectangle and draw method are you referring to so I can locate what you are talking about? Also, while I am looking at it, is there any protection I can add here as well like checking the Bitmap before processing/drawing? etc...

Thanks!!!

**Comment by ispysoftware** [comment]
hello sorry for the delay - christmas and all that. Maybe try turning off the plugin and then moving the windows around see if that fixes it?
The plugin could be causing an issue by returning a corrupted bitmap, possibly due to a sizing issue.

In Controls/camera.cs ispy passes in a bitmap and expects a bitmap to be returned - if that bitmap is invalid or corrupted then it'll crash - check line 537. If you are doing things in threads it could well be a timing issue.
