### ISSUE TITLE
A way to minimize the camera window pane without switching it off?

### ISSUE THREAD

**Issue by mjbedford2017** [ispysoftware/iSpy#91]
Hello, I have many video feeds, 14 of them in this case. The feeds run recording and a plugin, so I don't want them to be switched off ever. However, the main window gets a little "busy" with all of those camera windows showing the video streams. I don't necessarily need to see them all at the same time as I am not using this for real time viewing of the feeds like security would do. I just need them to all run in the background and still record and do plugins. Is there a way (and if not, I would suggest it) where I can manually hide or minimize a camera window when I don't want to physically view the feed? This would be a handy feature where I could only select to watch the stream or several streams I want, for troubleshooting or monitoring but have the others not streaming to the camera window and minimized when I don't want to physically watch them. I think this will also save on some resources by not having to "draw" the frame every time in the camera window if I am not even going to watch them. 

Thoughts?

**Comment by ispysoftware** [comment]
Our agent platform runs as a service and only displays the cameras you want to view. It's windows 10 though. Most dev work is going on Agent. In ispy you can click view - layout - auto layout objects - minimize which will minimize the cameras - you can then expand the ones you want or use a grid view

**Comment by mjbedford2017** [comment]
Clicking View > Layout > Auto Layout Objects > Minimize is perfect. This is what I was looking for. Then, if I want to see one, I can double click it and it pops up. Double click again and it minimizes. This works great. 

I will close this one but can you just follow up and tell me if minimizing the windows does help performance a bit just because the Bitmap does not have to be drawn on the Camera Window?

Thanks!

**Comment by ispysoftware** [comment]
Yes it bypasses rendering the bitmaps
