### ISSUE TITLE
Need to record with H265 video codec

### ISSUE THREAD

**Issue by surendran-syx** [ispysoftware/iSpy#94]
how to record  camera original stream?.
ispy always record with H264 video codec.
Need to record camera stream without re-encoding.

**Comment by ispysoftware** [comment]
our new platform, Agent can do this - http://www.ispyconnect.com/download.aspx

**Comment by surendran-syx** [comment]
Agent not worked on offline. can we integrate this raw data recording feature in Ispy windows application.

**Comment by ispysoftware** [comment]
What do you mean not worked on offline? What didn't work?

**Comment by surendran-syx** [comment]
we could not install Agent setup with offline. when try to install it show error "Exception:An error occurred while sending the request.,    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.WsWrapper.<DownloadLocation>d__2.MoveNext()"  in Agent_setup_log. But we successfully install the same setup with online.  That's why i mention like that.

**Comment by ispysoftware** [comment]
Oh right. You can use the installer on a computer with an internet connection then just copy the files over if you want. We don't have plans to add raw recording to ispy as ispy needs a Web compatible format for playback.
