### ISSUE TITLE
Problem detecting ONVIF cameras

### ISSUE THREAD

**Issue by RogerHardiman** [ispysoftware/iSpy#95]
I have a mix of ONVIF devices on my LAN, from Hik, Axis and Avigilon (plus a few Raspberry Pis running the RPOS Open Source ONVIF Camera Library (I'm an author)

I'll dig into iSpy properly but this Issue Report is just to document that many new cameras are not detected by the iSpy ONVIF Discovery probe.

Commenting out the discovery filter in Discovery.cs improves things

> //            foreach (var ctn in CtNs)
> //                findCriteria.ContractTypeNames.Add(ctn); 

Gut feeling is that cameras look for "dn:NetworkVideoTransmitter" so for the XML Qualified Name we need a XML Namespace of 'dn'

Anyway I'll dig about when I get time and compare it to my discovery code (server side) I wrote for the RPOS Open Source ONVIF NVT code.

But just wanted to create this Issue Report to remind me.

Thanks, Roger

**Comment by ispysoftware** [comment]
Thanks Roger, does adding

new XmlQualifiedName("dn:NetworkVideoTransmitter", @"http://www.onvif.org/ver10/network/wsdl")

..to the CtN list help?
