### ISSUE TITLE
giant memory leak

### ISSUE THREAD

**Issue by spyhunter99** [ispysoftware/iSpy#99]
![image](https://user-images.githubusercontent.com/1975321/77325607-fb28e900-6cee-11ea-838c-52d9589b013f.png)

that's over a few seconds, after a few minutes it's at 30GB+

found this with the last release and with the current master branch

**Comment by ispysoftware** [comment]
That's the frame action class which is the video buffer. It's supposed to be there. If you don't want it set the buffer to zero in the recording tab. If you have a problem you'll need to provide steps to reproduce it. A screenshot isn't much use.

**Comment by spyhunter99** [comment]
well i started up the app with a single onvif camera, within seconds it's taking a 1GB of ram, within 10 mins it's 30GB. 
previously this worked without a leak, but i upgraded my motherboard, cpu and ram and now it eats up ram worse than chrome. same os

**Comment by ispysoftware** [comment]
Are you sure it's using 30gb? If you added more RSM it will take longer to run a garbage collection, that's an os thing. It shouldn't use 30gb though. I'm guessing its probably 300mb or something. There is no memory leak in the app. That version of ispy has been stable for years. Youre either reading the number wrong or your os has some issue.

**Comment by spyhunter99** [comment]
i looked over the code too and nothing popped out as a possible memory leak
either. But it was definitely 30GB. i'll get you a screen shot in a second

**Comment by spyhunter99** [comment]
here's about 10GB after running for a few minutes
![image](https://user-images.githubusercontent.com/1975321/77836593-ec4a9800-712d-11ea-811c-d5d80bcf2275.png)

**Comment by spyhunter99** [comment]
here's 14 GB
![image](https://user-images.githubusercontent.com/1975321/77836621-24ea7180-712e-11ea-9b0f-455c3ad81b30.png)

**Comment by spyhunter99** [comment]
previous configuration was also 32GB, i just swapped the cpu (8 threads to 16), motherboard and ram (faster but same quantity). This is quite bizarre to me too. Perhaps i should uninstall, purge any settings/configuration bits and reinstall?

**Comment by spyhunter99** [comment]
it's been steady at 15 GB for the past hour. Still seems pretty high

**Comment by ispysoftware** [comment]
if you've got a whole heap of memory then the computer will only reclaim it when it's needed. Your camera looks like it's super high resolution as well, is it 4K? You might want to setup resize for that or choose a lower res endpoint as 4k is massive overkill for most security cameras.
